default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: auto_repair_development

test:
  <<: *default
  database: auto_repair_test

production:
  <<: *default
  database: auto_repair_production
  username: auto_repair
  password: <%= ENV["AUTO_REPAIR_DATABASE_PASSWORD"] %>
