<?php

namespace Database\Seeders;

use App\Models\Plate;
use App\Models\Order;
use App\Models\VersionHistory;
use App\Models\Maintenance;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedPlates();
        $this->seedOrders();
        $this->seedVersionHistories();
        $this->seedMaintenances();
    }

    private function seedPlates(): void
    {
        $plates = [
            [
                'plate_code' => 'TG-2024-001',
                'pattern_name' => '古典云纹图案',
                'pattern_description' => '传统中式祥云纹，线条流畅，适用于古典文学类书籍封面，烫金效果典雅大气',
                'applicable_books' => "《红楼梦》精装版\n《西游记》收藏版\n《三国演义》典藏版",
                'plate_width' => 180.00,
                'plate_height' => 240.00,
                'plate_thickness' => 1.50,
                'material' => '黄铜',
                'usage_count' => 4520,
                'max_usage' => 5000,
                'status' => '正常',
                'location' => 'A区-01-03',
                'manufacture_date' => '2024-03-15',
                'last_used_at' => '2026-06-10 14:30:00',
                'next_maintenance_date' => '2026-07-01',
                'remark' => '图案细节丰富，需要注意压力均匀',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'pattern_name' => '欧式古典花边',
                'pattern_description' => '巴洛克风格卷草纹边框，四角点缀花卉装饰，适合精装画册和艺术类书籍',
                'applicable_books' => "《艺术哲学》\n《西方美术史》\n《世界名画鉴赏》",
                'plate_width' => 210.00,
                'plate_height' => 285.00,
                'plate_thickness' => 2.00,
                'material' => '黄铜',
                'usage_count' => 2850,
                'max_usage' => 6000,
                'status' => '正常',
                'location' => 'A区-02-07',
                'manufacture_date' => '2024-05-20',
                'last_used_at' => '2026-06-15 09:15:00',
                'next_maintenance_date' => '2026-08-15',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-003',
                'pattern_name' => '书法字体烫金版',
                'pattern_description' => '毛笔楷书"珍藏本"三字，书法家题写，笔锋苍劲有力，专供珍藏版书籍使用',
                'applicable_books' => "《鲁迅全集》珍藏本\n《茅盾文学奖获奖作品集》",
                'plate_width' => 120.00,
                'plate_height' => 60.00,
                'plate_thickness' => 1.50,
                'material' => '黄铜',
                'usage_count' => 1280,
                'max_usage' => 8000,
                'status' => '正常',
                'location' => 'B区-03-12',
                'manufacture_date' => '2025-01-10',
                'last_used_at' => '2026-05-28 16:45:00',
                'next_maintenance_date' => '2026-09-10',
                'remark' => '小字部分容易堵版，需要频繁清洁',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'pattern_name' => '出版社Logo烫金版',
                'pattern_description' => '文华出版社标准Logo，包含图形和中英文名称组合，120线精细雕刻',
                'applicable_books' => "全社通用书脊\n扉页烫印",
                'plate_width' => 45.00,
                'plate_height' => 45.00,
                'plate_thickness' => 1.20,
                'material' => '黄铜',
                'usage_count' => 18650,
                'max_usage' => 20000,
                'status' => '待保养',
                'location' => 'C区-01-01',
                'manufacture_date' => '2025-02-28',
                'last_used_at' => '2026-06-16 11:00:00',
                'next_maintenance_date' => '2026-06-10',
                'remark' => '高频使用版，建议尽快安排深度保养，检查边缘磨损情况',
            ],
            [
                'plate_code' => 'TG-2025-022',
                'pattern_name' => '几何简约装饰线',
                'pattern_description' => '现代简约风格，多条平行装饰线，搭配极简主义设计书籍',
                'applicable_books' => "《设计中的设计》\n《极简主义生活》\n现代诗集系列",
                'plate_width' => 160.00,
                'plate_height' => 3.00,
                'plate_thickness' => 1.00,
                'material' => '锌版',
                'usage_count' => 3200,
                'max_usage' => 4000,
                'status' => '正常',
                'location' => 'B区-05-08',
                'manufacture_date' => '2025-06-12',
                'last_used_at' => '2026-06-01 10:20:00',
                'next_maintenance_date' => '2026-08-20',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'pattern_name' => '儿童读物卡通版',
                'pattern_description' => '可爱小熊图案，线条圆润，专为低龄儿童读物设计',
                'applicable_books' => "《小熊成长记》系列\n《睡前故事精选》\n《幼儿启蒙绘本》",
                'plate_width' => 100.00,
                'plate_height' => 100.00,
                'plate_thickness' => 1.50,
                'material' => '镁版',
                'usage_count' => 5600,
                'max_usage' => 5000,
                'status' => '维修中',
                'location' => '维修区',
                'manufacture_date' => '2025-08-05',
                'last_used_at' => '2026-05-20 15:30:00',
                'next_maintenance_date' => '2026-06-05',
                'remark' => '使用次数超过设计上限，图案出现磨损模糊，正在进行修复重做',
            ],
            [
                'plate_code' => 'TG-2026-002',
                'pattern_name' => '花卉装饰图案',
                'pattern_description' => '牡丹花纹浮雕效果，层次丰富，用于婚庆纪念册和高端礼品书',
                'applicable_books' => "《新婚纪念册》定制\n《金婚回忆录》",
                'plate_width' => 150.00,
                'plate_height' => 200.00,
                'plate_thickness' => 2.50,
                'material' => '黄铜',
                'usage_count' => 180,
                'max_usage' => 5000,
                'status' => '正常',
                'location' => 'A区-03-15',
                'manufacture_date' => '2026-01-18',
                'last_used_at' => '2026-04-22 09:00:00',
                'next_maintenance_date' => '2026-10-18',
                'remark' => '定制版，使用频率较低',
            ],
            [
                'plate_code' => 'TG-2026-007',
                'pattern_name' => '地图轮廓烫金版',
                'pattern_description' => '中国地图轮廓简化版，带省级行政区划界线，适用于地理类和旅游类书籍',
                'applicable_books' => "《中国地理百科》\n《中国旅游指南》\n《自驾游地图集》",
                'plate_width' => 200.00,
                'plate_height' => 180.00,
                'plate_thickness' => 1.50,
                'material' => '黄铜',
                'usage_count' => 420,
                'max_usage' => 5000,
                'status' => '正常',
                'location' => 'B区-02-04',
                'manufacture_date' => '2026-03-08',
                'last_used_at' => '2026-06-12 14:00:00',
                'next_maintenance_date' => '2026-09-08',
                'remark' => '细小线条较多，注意控制烫金温度',
            ],
            [
                'plate_code' => 'TG-2023-045',
                'pattern_name' => '圣经经文烫金版',
                'pattern_description' => '哥林多前书13章"爱的诗篇"节选，古英语字体排版',
                'applicable_books' => "《圣经》珍藏版\n《灵修日引》",
                'plate_width' => 140.00,
                'plate_height' => 180.00,
                'plate_thickness' => 1.50,
                'material' => '黄铜',
                'usage_count' => 25800,
                'max_usage' => 25000,
                'status' => '已报废',
                'location' => '报废品库',
                'manufacture_date' => '2023-09-10',
                'last_used_at' => '2026-03-15 11:45:00',
                'next_maintenance_date' => null,
                'remark' => '2026年4月报废，图案严重磨损，已更换新版 TG-2026-011',
            ],
            [
                'plate_code' => 'TG-2024-052',
                'pattern_name' => '星空星座图',
                'pattern_description' => '北半球冬季星空图，标注主要星座连线，用于科普类书籍封面',
                'applicable_books' => "《天文学入门》\n《星空观测指南》\n《宇宙探秘》",
                'plate_width' => 190.00,
                'plate_height' => 190.00,
                'plate_thickness' => 1.50,
                'material' => '黄铜',
                'usage_count' => 1580,
                'max_usage' => 5000,
                'status' => '正常',
                'location' => 'C区-03-20',
                'manufacture_date' => '2024-11-22',
                'last_used_at' => '2026-02-14 16:00:00',
                'next_maintenance_date' => '2026-07-22',
                'remark' => '极细线条较多，已出现个别星点模糊，下次保养需要重点检查',
            ],
        ];

        foreach ($plates as $plate) {
            Plate::create($plate);
        }
    }

    private function seedOrders(): void
    {
        $orders = [
            [
                'plate_code' => 'TG-2024-001',
                'order_number' => 'OR-2026-0612-001',
                'book_title' => '《红楼梦》精装版',
                'customer_name' => '文华书局北京发行部',
                'quantity' => 2000,
                'order_date' => '2026-06-12',
                'delivery_date' => '2026-06-20',
                'status' => '进行中',
                'unit_price' => 2.80,
                'remark' => '需配套烫银书脊',
            ],
            [
                'plate_code' => 'TG-2024-001',
                'order_number' => 'OR-2026-0515-023',
                'book_title' => '《三国演义》典藏版',
                'customer_name' => '古籍出版社',
                'quantity' => 1500,
                'order_date' => '2026-05-15',
                'delivery_date' => '2026-05-28',
                'status' => '已完成',
                'unit_price' => 2.80,
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'order_number' => 'OR-2026-0610-015',
                'book_title' => '《西方美术史》',
                'customer_name' => '艺术之光出版社',
                'quantity' => 3000,
                'order_date' => '2026-06-10',
                'delivery_date' => '2026-06-25',
                'status' => '进行中',
                'unit_price' => 3.50,
                'remark' => '大尺寸封面，注意对齐',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'order_number' => 'OR-2026-0420-008',
                'book_title' => '《艺术哲学》',
                'customer_name' => '商务印书馆',
                'quantity' => 1000,
                'order_date' => '2026-04-20',
                'delivery_date' => '2026-05-05',
                'status' => '已完成',
                'unit_price' => 3.20,
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-003',
                'order_number' => 'OR-2026-0520-033',
                'book_title' => '《鲁迅全集》珍藏本',
                'customer_name' => '人民文学出版社',
                'quantity' => 500,
                'order_date' => '2026-05-20',
                'delivery_date' => '2026-06-05',
                'status' => '已完成',
                'unit_price' => 5.00,
                'remark' => '限量编号版，工艺要求极高',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'order_number' => 'OR-2026-0616-077',
                'book_title' => '扉页通用烫印',
                'customer_name' => '文华出版社各编辑部',
                'quantity' => 8000,
                'order_date' => '2026-06-16',
                'delivery_date' => '2026-06-30',
                'status' => '进行中',
                'unit_price' => 0.50,
                'remark' => '批量订单，分批交付',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'order_number' => 'OR-2026-0601-045',
                'book_title' => '书脊烫印批量',
                'customer_name' => '发行部',
                'quantity' => 5000,
                'order_date' => '2026-06-01',
                'delivery_date' => '2026-06-12',
                'status' => '已完成',
                'unit_price' => 0.50,
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-022',
                'order_number' => 'OR-2026-0605-012',
                'book_title' => '《设计中的设计》再版',
                'customer_name' => '山东人民出版社',
                'quantity' => 2500,
                'order_date' => '2026-06-05',
                'delivery_date' => '2026-06-18',
                'status' => '已完成',
                'unit_price' => 1.80,
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'order_number' => 'OR-2026-0510-066',
                'book_title' => '《小熊成长记》第3辑',
                'customer_name' => '童趣出版社',
                'quantity' => 6000,
                'order_date' => '2026-05-10',
                'delivery_date' => '2026-05-25',
                'status' => '已延期',
                'unit_price' => 1.50,
                'remark' => '铜版磨损导致质量问题，已退回重做',
            ],
            [
                'plate_code' => 'TG-2026-002',
                'order_number' => 'OR-2026-0415-021',
                'book_title' => '《金婚回忆录》定制',
                'customer_name' => '私人定制订单',
                'quantity' => 50,
                'order_date' => '2026-04-15',
                'delivery_date' => '2026-04-25',
                'status' => '已完成',
                'unit_price' => 15.00,
                'remark' => 'VIP客户定制，全流程质检',
            ],
            [
                'plate_code' => 'TG-2026-007',
                'order_number' => 'OR-2026-0612-035',
                'book_title' => '《中国旅游指南》2026版',
                'customer_name' => '中国旅游出版社',
                'quantity' => 4000,
                'order_date' => '2026-06-12',
                'delivery_date' => '2026-06-28',
                'status' => '进行中',
                'unit_price' => 2.20,
                'remark' => '配合暑期旅游旺季发行',
            ],
            [
                'plate_code' => 'TG-2024-052',
                'order_number' => 'OR-2026-0210-003',
                'book_title' => '《天文学入门》修订版',
                'customer_name' => '科学普及出版社',
                'quantity' => 1500,
                'order_date' => '2026-02-10',
                'delivery_date' => '2026-02-20',
                'status' => '已完成',
                'unit_price' => 2.50,
                'remark' => '',
            ],
        ];

        foreach ($orders as $order) {
            $plate = Plate::where('plate_code', $order['plate_code'])->first();
            if ($plate) {
                Order::create([
                    'plate_id' => $plate->id,
                    'order_number' => $order['order_number'],
                    'book_title' => $order['book_title'],
                    'customer_name' => $order['customer_name'],
                    'quantity' => $order['quantity'],
                    'order_date' => $order['order_date'],
                    'delivery_date' => $order['delivery_date'],
                    'status' => $order['status'],
                    'unit_price' => $order['unit_price'],
                    'remark' => $order['remark'],
                ]);
            }
        }
    }

    private function seedVersionHistories(): void
    {
        $histories = [
            [
                'plate_code' => 'TG-2024-001',
                'version_code' => 'V1.0',
                'batch_number' => 'B20240315-A',
                'change_type' => '初始创建',
                'change_description' => '根据设计稿DS-2024-028制作，古典云纹图案，设计师：李明',
                'operator' => '张师傅',
                'changed_at' => '2024-03-15 10:00:00',
                'plate_width' => 180.00,
                'plate_height' => 240.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2024-001',
                'version_code' => 'V1.1',
                'batch_number' => 'B20240820-B',
                'change_type' => '图案修改',
                'change_description' => '客户反馈祥云线条过细，加宽0.15mm，增强烫印辨识度',
                'operator' => '张师傅',
                'changed_at' => '2024-08-20 14:30:00',
                'plate_width' => 180.00,
                'plate_height' => 240.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2024-001',
                'version_code' => 'V1.2',
                'batch_number' => 'B20250510-C',
                'change_type' => '维护记录',
                'change_description' => '深度清洁抛光，修复轻微磨损边缘，校准定位孔',
                'operator' => '李工',
                'changed_at' => '2025-05-10 09:15:00',
                'plate_width' => 180.00,
                'plate_height' => 240.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'version_code' => 'V1.0',
                'batch_number' => 'B20240520-A',
                'change_type' => '初始创建',
                'change_description' => '欧式巴洛克花边，设计稿DS-2024-065，厚度2mm黄铜版',
                'operator' => '王师傅',
                'changed_at' => '2024-05-20 11:00:00',
                'plate_width' => 210.00,
                'plate_height' => 285.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'version_code' => 'V1.1',
                'batch_number' => 'B20251115-B',
                'change_type' => '修复重做',
                'change_description' => '左上角花卉图案因外力导致变形，局部修复重做',
                'operator' => '王师傅',
                'changed_at' => '2025-11-15 16:00:00',
                'plate_width' => 210.00,
                'plate_height' => 285.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2025-003',
                'version_code' => 'V1.0',
                'batch_number' => 'B20250110-A',
                'change_type' => '初始创建',
                'change_description' => '名家题写"珍藏本"三字，原大扫描1200dpi精雕',
                'operator' => '李工',
                'changed_at' => '2025-01-10 15:20:00',
                'plate_width' => 120.00,
                'plate_height' => 60.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'version_code' => 'V1.0',
                'batch_number' => 'B20250228-A',
                'change_type' => '初始创建',
                'change_description' => '出版社社标Logo，VI规范SOP-001版本',
                'operator' => '张师傅',
                'changed_at' => '2025-02-28 09:00:00',
                'plate_width' => 45.00,
                'plate_height' => 45.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'version_code' => 'V1.1',
                'batch_number' => 'B20250905-B',
                'change_type' => '维护记录',
                'change_description' => '使用量破万，进行全面检查和抛光处理',
                'operator' => '李工',
                'changed_at' => '2025-09-05 10:45:00',
                'plate_width' => 45.00,
                'plate_height' => 45.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'version_code' => 'V1.2',
                'batch_number' => 'B20260412-C',
                'change_type' => '维护记录',
                'change_description' => '边缘圆角有磨损，抛光修复并重新校准',
                'operator' => '张师傅',
                'changed_at' => '2026-04-12 14:00:00',
                'plate_width' => 45.00,
                'plate_height' => 45.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'version_code' => 'V1.0',
                'batch_number' => 'B20250805-A',
                'change_type' => '初始创建',
                'change_description' => '儿童读物卡通小熊图案，镁版快速打样后正式制作',
                'operator' => '王师傅',
                'changed_at' => '2025-08-05 13:30:00',
                'plate_width' => 100.00,
                'plate_height' => 100.00,
                'material' => '镁版',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'version_code' => 'V1.1',
                'batch_number' => 'B20260601-B',
                'change_type' => '修复重做',
                'change_description' => '超量使用导致图案磨损30%以上，正在全面修复重做',
                'operator' => '王师傅',
                'changed_at' => '2026-06-01 11:00:00',
                'plate_width' => 100.00,
                'plate_height' => 100.00,
                'material' => '镁版',
            ],
            [
                'plate_code' => 'TG-2026-007',
                'version_code' => 'V1.0',
                'batch_number' => 'B20260308-A',
                'change_type' => '初始创建',
                'change_description' => '中国地图简化版，1:4000万比例尺，经民政部门审核通过',
                'operator' => '李工',
                'changed_at' => '2026-03-08 10:30:00',
                'plate_width' => 200.00,
                'plate_height' => 180.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2023-045',
                'version_code' => 'V1.0',
                'batch_number' => 'B20230910-A',
                'change_type' => '初始创建',
                'change_description' => '圣经经文烫金版，古英语字体排版设计',
                'operator' => '张师傅',
                'changed_at' => '2023-09-10 09:00:00',
                'plate_width' => 140.00,
                'plate_height' => 180.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2023-045',
                'version_code' => 'V1.1',
                'batch_number' => 'B20241215-B',
                'change_type' => '维护记录',
                'change_description' => '使用15000次保养，精细清洁',
                'operator' => '李工',
                'changed_at' => '2024-12-15 15:30:00',
                'plate_width' => 140.00,
                'plate_height' => 180.00,
                'material' => '黄铜',
            ],
            [
                'plate_code' => 'TG-2024-052',
                'version_code' => 'V1.0',
                'batch_number' => 'B20241122-A',
                'change_type' => '初始创建',
                'change_description' => '北半球冬季星图，依据IAU标准星图绘制',
                'operator' => '李工',
                'changed_at' => '2024-11-22 14:00:00',
                'plate_width' => 190.00,
                'plate_height' => 190.00,
                'material' => '黄铜',
            ],
        ];

        foreach ($histories as $history) {
            $plate = Plate::where('plate_code', $history['plate_code'])->first();
            if ($plate) {
                VersionHistory::create([
                    'plate_id' => $plate->id,
                    'version_code' => $history['version_code'],
                    'batch_number' => $history['batch_number'],
                    'change_type' => $history['change_type'],
                    'change_description' => $history['change_description'],
                    'operator' => $history['operator'],
                    'changed_at' => $history['changed_at'],
                    'plate_width' => $history['plate_width'],
                    'plate_height' => $history['plate_height'],
                    'material' => $history['material'],
                ]);
            }
        }
    }

    private function seedMaintenances(): void
    {
        $maintenances = [
            [
                'plate_code' => 'TG-2024-001',
                'maintenance_type' => '日常清洁',
                'description' => '使用专用铜版清洁剂清洗表面残留金粉，检查无明显磨损',
                'operator' => '刘班长',
                'maintenance_date' => '2026-04-01',
                'next_maintenance_date' => '2026-07-01',
                'cost' => 50.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2024-001',
                'maintenance_type' => '防锈处理',
                'description' => '梅雨季前全面防锈处理，涂抹专用保护剂',
                'operator' => '刘班长',
                'maintenance_date' => '2026-05-10',
                'next_maintenance_date' => '2026-07-01',
                'cost' => 120.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2024-008',
                'maintenance_type' => '日常清洁',
                'description' => '常规清洁保养，花边缝隙中金粉清理干净',
                'operator' => '刘班长',
                'maintenance_date' => '2026-05-15',
                'next_maintenance_date' => '2026-08-15',
                'cost' => 80.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-003',
                'maintenance_type' => '日常清洁',
                'description' => '字体凹陷处细致清洁，使用软毛刷配合专用溶剂',
                'operator' => '赵师傅',
                'maintenance_date' => '2026-06-01',
                'next_maintenance_date' => '2026-09-10',
                'cost' => 60.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'maintenance_type' => '深度保养',
                'description' => '使用量接近18000次，需要全面检查磨损情况并抛光',
                'operator' => '李工',
                'maintenance_date' => '2026-05-20',
                'next_maintenance_date' => '2026-06-10',
                'cost' => 350.00,
                'status' => '已完成',
                'remark' => '建议尽快更换新版，此版磨损接近临界',
            ],
            [
                'plate_code' => 'TG-2025-015',
                'maintenance_type' => '抛光修复',
                'description' => '待执行：Logo边缘圆角有明显磨损，需要抛光修复',
                'operator' => null,
                'maintenance_date' => '2026-06-20',
                'next_maintenance_date' => null,
                'cost' => 0.00,
                'status' => '待处理',
                'remark' => '逾期未完成保养，安排在本周六处理',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'maintenance_type' => '日常清洁',
                'description' => '常规清洁',
                'operator' => '赵师傅',
                'maintenance_date' => '2026-04-15',
                'next_maintenance_date' => '2026-06-05',
                'cost' => 50.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2025-031',
                'maintenance_type' => '更换重做',
                'description' => '使用量超标，图案严重模糊，已送外加工重做',
                'operator' => '王师傅（外协）',
                'maintenance_date' => '2026-06-01',
                'next_maintenance_date' => '2026-09-01',
                'cost' => 1800.00,
                'status' => '进行中',
                'remark' => '预计6月25日完成交付',
            ],
            [
                'plate_code' => 'TG-2026-007',
                'maintenance_type' => '防锈处理',
                'description' => '新出厂铜板首次防锈处理',
                'operator' => '刘班长',
                'maintenance_date' => '2026-03-10',
                'next_maintenance_date' => '2026-09-08',
                'cost' => 100.00,
                'status' => '已完成',
                'remark' => '',
            ],
            [
                'plate_code' => 'TG-2024-052',
                'maintenance_type' => '日常清洁',
                'description' => '星点位置极细清洁，防止堵版',
                'operator' => '赵师傅',
                'maintenance_date' => '2026-04-22',
                'next_maintenance_date' => '2026-07-22',
                'cost' => 90.00,
                'status' => '已完成',
                'remark' => '猎户座区域有4个星点需要重点关注',
            ],
        ];

        foreach ($maintenances as $maint) {
            $plate = Plate::where('plate_code', $maint['plate_code'])->first();
            if ($plate) {
                Maintenance::create([
                    'plate_id' => $plate->id,
                    'maintenance_type' => $maint['maintenance_type'],
                    'description' => $maint['description'],
                    'operator' => $maint['operator'],
                    'maintenance_date' => $maint['maintenance_date'],
                    'next_maintenance_date' => $maint['next_maintenance_date'],
                    'cost' => $maint['cost'],
                    'status' => $maint['status'],
                    'remark' => $maint['remark'],
                ]);
            }
        }
    }
}
