<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        $materials = [
            [
                'name' => '白乳胶',
                'code' => 'PVA',
                'description' => '最常见的水基胶黏剂，由聚醋酸乙烯酯制成。黏度适中，干燥速度中等，透明度较好。是图书修补的基础材料。',
                'type' => 'base',
                'color' => '#f5f5dc',
                'viscosity_factor' => 1.0,
                'drying_time_factor' => 1.0,
                'transparency_factor' => 1.0,
                'base_viscosity' => 60.0,
                'base_drying_time' => 50.0,
                'base_transparency' => 75.0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'name' => '骨胶',
                'code' => 'GLUE',
                'description' => '由动物骨骼熬制的传统胶黏剂。黏度极高，干燥后非常坚固，但干燥时间长，透明度较低。常用于古籍修复。',
                'type' => 'base',
                'color' => '#d4a574',
                'viscosity_factor' => 1.0,
                'drying_time_factor' => 1.0,
                'transparency_factor' => 1.0,
                'base_viscosity' => 95.0,
                'base_drying_time' => 70.0,
                'base_transparency' => 40.0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'name' => '浆糊',
                'code' => 'STARCH',
                'description' => '由淀粉熬制的传统浆糊。黏度较低，干燥时间长，但温和不损伤纸张。是最古老的图书修补材料之一。',
                'type' => 'base',
                'color' => '#e8e4c9',
                'viscosity_factor' => 1.0,
                'drying_time_factor' => 1.0,
                'transparency_factor' => 1.0,
                'base_viscosity' => 45.0,
                'base_drying_time' => 80.0,
                'base_transparency' => 55.0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'name' => '阿拉伯树胶',
                'code' => 'GUM',
                'description' => '从金合欢树提取的天然树胶。成膜后透明度极高，干燥速度适中，黏度较低。常用于书画装裱和高级纸张修复。',
                'type' => 'base',
                'color' => '#f0e68c',
                'viscosity_factor' => 1.0,
                'drying_time_factor' => 1.0,
                'transparency_factor' => 1.0,
                'base_viscosity' => 50.0,
                'base_drying_time' => 55.0,
                'base_transparency' => 95.0,
                'is_unlocked_by_default' => false,
                'unlock_level_id' => 3,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'name' => '明胶',
                'code' => 'GELATIN',
                'description' => '从动物皮骨中提取的蛋白质胶。成膜透明有韧性，黏度适中，干燥较快。是专业级图书修复材料。',
                'type' => 'base',
                'color' => '#fffacd',
                'viscosity_factor' => 1.0,
                'drying_time_factor' => 1.0,
                'transparency_factor' => 1.0,
                'base_viscosity' => 70.0,
                'base_drying_time' => 45.0,
                'base_transparency' => 85.0,
                'is_unlocked_by_default' => false,
                'unlock_level_id' => 4,
                'order' => 5,
                'is_active' => true,
            ],
            [
                'name' => '纯净水',
                'code' => 'WATER',
                'description' => '最基础的稀释剂。加入水可以降低胶水黏度，加快干燥速度，略微提高透明度。但加太多会降低胶水强度。',
                'type' => 'additive',
                'color' => '#e0f7fa',
                'viscosity_factor' => 0.3,
                'drying_time_factor' => 0.6,
                'transparency_factor' => 1.1,
                'base_viscosity' => 0,
                'base_drying_time' => 0,
                'base_transparency' => 0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'name' => '明矾',
                'code' => 'ALUM',
                'description' => '具有收敛作用的矿物添加剂。能显著增加胶水黏度，减缓干燥速度，但会降低透明度并可能使纸张发黄。',
                'type' => 'additive',
                'color' => '#f5f5f5',
                'viscosity_factor' => 2.0,
                'drying_time_factor' => 1.5,
                'transparency_factor' => 0.7,
                'base_viscosity' => 0,
                'base_drying_time' => 0,
                'base_transparency' => 0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'name' => '甘油',
                'code' => 'GLYCERIN',
                'description' => '一种保湿剂。加入后会降低黏度，显著减慢干燥速度，但能大幅提高透明度并使胶膜更柔韧。',
                'type' => 'additive',
                'color' => '#fafad2',
                'viscosity_factor' => 0.6,
                'drying_time_factor' => 1.8,
                'transparency_factor' => 1.4,
                'base_viscosity' => 0,
                'base_drying_time' => 0,
                'base_transparency' => 0,
                'is_unlocked_by_default' => true,
                'unlock_level_id' => null,
                'order' => 12,
                'is_active' => true,
            ],
            [
                'name' => '酒精',
                'code' => 'ALCOHOL',
                'description' => '乙醇溶剂。能大幅加快干燥速度，降低黏度，但对透明度有轻微影响。注意：易燃，需小心使用。',
                'type' => 'additive',
                'color' => '#f0ffff',
                'viscosity_factor' => 0.4,
                'drying_time_factor' => 0.3,
                'transparency_factor' => 0.9,
                'base_viscosity' => 0,
                'base_drying_time' => 0,
                'base_transparency' => 0,
                'is_unlocked_by_default' => false,
                'unlock_level_id' => 2,
                'order' => 13,
                'is_active' => true,
            ],
            [
                'name' => '硼酸',
                'code' => 'BORIC',
                'description' => '一种交联剂和防腐剂。能大幅提高黏度，增强胶膜耐水性，同时具有防腐作用。但会降低透明度。',
                'type' => 'additive',
                'color' => '#f8f8ff',
                'viscosity_factor' => 2.5,
                'drying_time_factor' => 1.2,
                'transparency_factor' => 0.6,
                'base_viscosity' => 0,
                'base_drying_time' => 0,
                'base_transparency' => 0,
                'is_unlocked_by_default' => false,
                'unlock_level_id' => 5,
                'order' => 14,
                'is_active' => true,
            ],
        ];

        foreach ($materials as $material) {
            DB::table('materials')->updateOrInsert(
                ['code' => $material['code']],
                $material
            );
        }
    }
}
