# Generated by Django 5.0.6 on 2026-06-04 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='检查类型')),
                ('department', models.CharField(max_length=100, verbose_name='科室')),
                ('estimated_duration', models.IntegerField(default=30, verbose_name='预计时长(分钟)')),
            ],
            options={
                'verbose_name': '检查类型',
                'verbose_name_plural': '检查类型',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='住址')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=20, unique=True, verbose_name='预约编号')),
                ('original_appointment_time', models.DateTimeField(verbose_name='原预约时间')),
                ('current_appointment_time', models.DateTimeField(verbose_name='当前预约时间')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(choices=[('scheduled', '待检查'), ('in_progress', '检查中'), ('completed', '已完成'), ('rescheduled', '已改期'), ('cancelled', '已取消'), ('expired', '已过期')], default='scheduled', max_length=20, verbose_name='预约状态')),
                ('report_status', models.CharField(choices=[('pending', '待出报告'), ('generated', '报告已生成'), ('ready', '待领取'), ('claimed', '已领取'), ('stalled', '报告滞留'), ('returned', '已退回'), ('verified', '已复核')], default='pending', max_length=20, verbose_name='报告状态')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='检查室')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('examination_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workstation.examinationtype', verbose_name='检查类型')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workstation.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '检查预约',
                'verbose_name_plural': '检查预约',
                'ordering': ['-current_appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_type', models.CharField(choices=[('identity_mismatch', '身份信息不匹配'), ('report_stalled', '报告滞留'), ('reschedule_abnormal', '改期异常'), ('other', '其他异常')], max_length=30, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='处理状态')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('review_summary', models.TextField(blank=True, verbose_name='复盘总结')),
                ('preventive_measures', models.TextField(blank=True, verbose_name='预防措施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_abnormals', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_records', to='workstation.appointment', verbose_name='预约记录')),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('reschedule', '改期'), ('claim', '领取'), ('review', '复核'), ('abnormal', '异常处理')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(verbose_name='操作详情')),
                ('evidence', models.TextField(blank=True, verbose_name='佐证材料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workstation.appointment', verbose_name='预约记录')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('self', '本人领取'), ('authorized', '授权领取'), ('mail', '邮寄')], max_length=20, verbose_name='领取方式')),
                ('claimant_name', models.CharField(max_length=50, verbose_name='领取人姓名')),
                ('claimant_id_card', models.CharField(max_length=18, verbose_name='领取人身份证号')),
                ('claimant_phone', models.CharField(max_length=11, verbose_name='领取人电话')),
                ('verification_result', models.CharField(choices=[('match', '身份匹配'), ('mismatch', '身份不匹配'), ('pending', '待验证')], default='pending', max_length=20, verbose_name='身份验证结果')),
                ('verification_notes', models.TextField(blank=True, verbose_name='验证说明')),
                ('correction_path', models.TextField(blank=True, verbose_name='补正路径')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='是否阻断领取')),
                ('review_status', models.CharField(choices=[('pending', '待复核'), ('approved', '已确认'), ('rejected', '已退回')], default='pending', max_length=20, verbose_name='复核状态')),
                ('review_notes', models.TextField(blank=True, verbose_name='复核意见')),
                ('evidence', models.TextField(blank=True, verbose_name='佐证材料')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='workstation.appointment', verbose_name='预约记录')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '报告领取记录',
                'verbose_name_plural': '报告领取记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_time', models.DateTimeField(verbose_name='原时间')),
                ('new_time', models.DateTimeField(verbose_name='新时间')),
                ('reason', models.CharField(choices=[('patient', '患者原因'), ('hospital', '医院原因'), ('other', '其他原因')], max_length=20, verbose_name='改期原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='详细原因')),
                ('evidence', models.TextField(blank=True, verbose_name='佐证材料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='改期时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='workstation.appointment', verbose_name='预约记录')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedules', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '改期记录',
                'verbose_name_plural': '改期记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
