# Generated by Django 5.0 on 2026-06-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待初审'), ('first_review', '初审中'), ('first_approved', '初审通过'), ('first_rejected', '初审驳回'), ('arbitration', '仲裁中'), ('approved', '申诉通过'), ('rejected', '申诉驳回'), ('supplement', '待补证')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('pending', '待处理'), ('revoked', '撤销扣罚'), ('maintained', '维持扣罚'), ('supplement', '要求补证')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField()),
                ('expected_delivery_time', models.DateTimeField()),
                ('actual_delivery_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', '待配送'), ('delivering', '配送中'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('timeout', '超时配送'), ('location_drift', '定位漂移'), ('customer_complaint', '客户投诉'), ('food_damage', '餐品损坏'), ('service_issue', '服务问题')], max_length=30)),
                ('description', models.TextField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建扣罚'), ('appeal', '提交申诉'), ('first_review_pass', '初审通过'), ('first_review_reject', '初审驳回'), ('arbitration_pass', '仲裁通过'), ('arbitration_reject', '仲裁驳回'), ('supplement', '要求补证'), ('resubmit', '补充证据'), ('trajectory_recalc', '轨迹重算')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appeal.appeal')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('in', '收到'), ('out', '发送')], max_length=10)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_evidences', to='appeal.appeal')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidences/')),
                ('evidence_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('chat', '聊天记录'), ('trajectory', '轨迹数据'), ('other', '其他')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='appeal.appeal')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待申诉'), ('appealing', '申诉中'), ('resolved', '已解决')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.order')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.penaltyrule')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='penalty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appeal.penalty'),
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('id_card', models.CharField(max_length=18)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('active', '在职'), ('suspended', '停职'), ('resigned', '离职')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='penalty',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.rider'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.rider'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.site'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.site'),
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.site'),
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('accuracy', models.FloatField()),
                ('is_recalculated', models.BooleanField(default=False)),
                ('recalculated_at', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeal.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.rider')),
            ],
        ),
    ]
