# Generated by Django 5.0 on 2026-06-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='观察日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体温(℃)')),
                ('appetite', models.CharField(choices=[('normal', '正常'), ('decreased', '减少'), ('none', '无')], max_length=20, verbose_name='食欲')),
                ('mental_state', models.CharField(choices=[('active', '活跃'), ('normal', '正常'), ('lethargic', '萎靡')], max_length=20, verbose_name='精神状态')),
                ('excretion', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], max_length=20, verbose_name='排泄情况')),
                ('abnormal_symptoms', models.TextField(blank=True, null=True, verbose_name='异常症状')),
                ('feeding_record', models.TextField(verbose_name='饲养记录')),
                ('water_intake', models.CharField(max_length=100, verbose_name='饮水情况')),
                ('environment_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='环境温度(℃)')),
                ('environment_humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='环境湿度(%)')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_records', to='batches.batch', verbose_name='批次')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='观察员')),
            ],
            options={
                'verbose_name': '观察记录',
                'verbose_name_plural': '观察记录',
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='ObservationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='observations.observationrecord', verbose_name='观察记录')),
            ],
            options={
                'verbose_name': '观察照片',
                'verbose_name_plural': '观察照片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='observationrecord',
            index=models.Index(fields=['batch'], name='observation_batch_i_018cac_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrecord',
            index=models.Index(fields=['observation_date'], name='observation_observa_a29def_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrecord',
            index=models.Index(fields=['is_abnormal'], name='observation_is_abno_0f75d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='observationrecord',
            unique_together={('batch', 'observation_date')},
        ),
    ]
