import type { Level } from "~/lib/types";

export const LEVELS: Level[] = [
  {
    id: 1,
    name: "初识音栓",
    description: "认识最基础的主音栓和笛音栓，从简单的单音栓开始",
    difficulty: 1,
    availableStops: ["principal-8", "flute-8", "gedackt-8", "bourdon-16"],
    targetCombinations: [
      ["principal-8"],
      ["flute-8"],
      ["gedackt-8"],
      ["bourdon-16"],
      ["principal-8", "flute-8"],
    ],
    passingScore: 60,
    stars: { threeStar: 90, twoStar: 75 },
    phraseNotes: [60, 64, 67, 72],
  },
  {
    id: 2,
    name: "双栓组合",
    description: "学习两种不同音色的组合，感受音色融合",
    difficulty: 2,
    availableStops: ["principal-8", "principal-4", "flute-8", "flute-4", "gedackt-8"],
    targetCombinations: [
      ["principal-8", "principal-4"],
      ["flute-8", "flute-4"],
      ["principal-8", "flute-8"],
      ["gedackt-8", "flute-4"],
      ["principal-4", "flute-4"],
      ["principal-8", "gedackt-8"],
    ],
    passingScore: 65,
    stars: { threeStar: 92, twoStar: 78 },
    phraseNotes: [60, 62, 64, 65, 67, 69, 71, 72],
  },
  {
    id: 3,
    name: "弦乐登场",
    description: "引入弦乐音栓，体会弦乐与主音、笛音的配合",
    difficulty: 2,
    availableStops: ["principal-8", "flute-8", "salicional-8", "cello-8", "violin-4"],
    targetCombinations: [
      ["salicional-8"],
      ["cello-8"],
      ["salicional-8", "cello-8"],
      ["principal-8", "salicional-8"],
      ["flute-8", "violin-4"],
      ["salicional-8", "violin-4"],
      ["principal-8", "cello-8"],
    ],
    timeLimit: 45,
    passingScore: 70,
    stars: { threeStar: 93, twoStar: 80 },
    phraseNotes: [57, 60, 64, 67, 69, 72],
  },
  {
    id: 4,
    name: "簧音挑战",
    description: "簧音栓具有独特的音色，考验你的听觉分辨力",
    difficulty: 3,
    availableStops: ["principal-8", "flute-8", "oboe-8", "trumpet-8", "clarinet-8"],
    targetCombinations: [
      ["oboe-8"],
      ["trumpet-8"],
      ["clarinet-8"],
      ["principal-8", "trumpet-8"],
      ["flute-8", "clarinet-8"],
      ["oboe-8", "clarinet-8"],
      ["principal-8", "oboe-8"],
    ],
    timeLimit: 40,
    passingScore: 70,
    stars: { threeStar: 92, twoStar: 80 },
    phraseNotes: [60, 64, 67, 71, 72, 76],
  },
  {
    id: 5,
    name: "三栓组合",
    description: "三种音栓的组合，音色更加丰富",
    difficulty: 3,
    availableStops: ["principal-8", "principal-4", "flute-8", "flute-4", "salicional-8", "cello-8"],
    targetCombinations: [
      ["principal-8", "principal-4", "flute-8"],
      ["flute-8", "flute-4", "salicional-8"],
      ["principal-8", "salicional-8", "cello-8"],
      ["principal-4", "flute-4", "salicional-8"],
      ["principal-8", "flute-8", "cello-8"],
      ["flute-8", "salicional-8", "cello-8"],
    ],
    timeLimit: 50,
    passingScore: 72,
    stars: { threeStar: 90, twoStar: 80 },
    phraseNotes: [60, 62, 64, 65, 67, 69, 71, 72],
  },
  {
    id: 6,
    name: "混合音栓",
    description: "混合音栓增加和声效果，让音色更宏大",
    difficulty: 4,
    availableStops: ["principal-8", "principal-4", "flute-8", "mixture-iii", "mixture-v", "salicional-8"],
    targetCombinations: [
      ["principal-8", "mixture-iii"],
      ["principal-4", "mixture-iii"],
      ["principal-8", "flute-8", "mixture-iii"],
      ["principal-8", "principal-4", "mixture-v"],
      ["salicional-8", "mixture-iii"],
      ["principal-8", "flute-8", "mixture-v"],
    ],
    timeLimit: 45,
    passingScore: 75,
    stars: { threeStar: 92, twoStar: 82 },
    phraseNotes: [48, 55, 60, 64, 67, 72],
  },
  {
    id: 7,
    name: "高级组合",
    description: "综合所有类型的音栓，挑战你的记忆极限",
    difficulty: 4,
    availableStops: ["principal-8", "principal-4", "flute-8", "salicional-8", "oboe-8", "trumpet-8", "clarinet-8", "mixture-iii"],
    targetCombinations: [
      ["principal-8", "oboe-8"],
      ["salicional-8", "oboe-8"],
      ["principal-8", "principal-4", "trumpet-8"],
      ["flute-8", "clarinet-8", "mixture-iii"],
      ["principal-8", "salicional-8", "trumpet-8"],
      ["principal-8", "oboe-8", "mixture-iii"],
    ],
    timeLimit: 50,
    passingScore: 75,
    stars: { threeStar: 90, twoStar: 82 },
    phraseNotes: [60, 64, 67, 71, 74, 76, 79],
  },
  {
    id: 8,
    name: "大师挑战",
    description: "四栓及以上组合，只有真正的管风琴大师才能通关",
    difficulty: 5,
    availableStops: ["principal-8", "principal-4", "principal-2", "flute-8", "flute-4", "salicional-8", "oboe-8", "trumpet-8", "mixture-iii", "mixture-v"],
    targetCombinations: [
      ["principal-8", "principal-4", "principal-2", "mixture-v"],
      ["principal-8", "flute-8", "oboe-8", "trumpet-8"],
      ["flute-8", "flute-4", "salicional-8", "mixture-iii"],
      ["principal-8", "principal-4", "oboe-8", "mixture-iii"],
      ["principal-8", "flute-8", "salicional-8", "trumpet-8", "mixture-v"],
      ["principal-8", "principal-4", "flute-8", "oboe-8", "trumpet-8"],
    ],
    timeLimit: 60,
    passingScore: 80,
    stars: { threeStar: 95, twoStar: 87 },
    phraseNotes: [48, 55, 60, 64, 67, 71, 72, 76],
  },
];
