import type { SectionType, Micrograph, MineralOptics, InterferenceColor, Cleavage, Association, SampleBox } from '~/types/mineral';

export const seedBoxes: Omit<SampleBox, 'id' | 'createdAt'>[] = [
  {
    name: '稀有矿物薄片盒 A',
    code: 'BOX-RARE-2024-A',
    rows: 10,
    columns: 10,
    location: '标本柜 3 层 2 号',
    description: '收藏稀有矿物标准薄片，含伟晶岩、热液脉型矿床标本',
  },
  {
    name: '教学标本盒 B',
    code: 'BOX-TEACH-2024-B',
    rows: 8,
    columns: 8,
    location: '教学实验室 101',
    description: '教学用常见造岩矿物薄片，供学生实习使用',
  },
];

export const seedSections: Omit<SectionType, 'id' | 'createdAt' | 'updatedAt' | 'currentVersion' | 'isDeleted'>[] = [
  {
    sampleNumber: 'PKU-GEO-2024-001',
    mineralName: '锂辉石',
    mineralFormula: 'LiAlSi₂O₆',
    crystalSystem: '单斜晶系',
    locality: '新疆可可托海 3 号矿脉',
    collectionDate: '2023-08-15',
    collector: '张研究员',
    thinSectionNumber: 'TS-Li-001',
    thicknessMicrometers: 30,
    coverSlip: true,
    mountingMedium: '环氧树脂',
    grainSizeMm: 2.5,
    rockType: '花岗伟晶岩',
    alterationDegree: 10,
    sampleBoxId: 1,
    boxPosition: 'A1',
    notes: '宝石级粉红色锂辉石，含钠长石、锂云母包体。取自伟晶岩核心带，结晶粗大，晶形完整。',
  },
  {
    sampleNumber: 'PKU-GEO-2024-002',
    mineralName: '蓝线石',
    mineralFormula: 'Al₈BSi₄O₁₉(OH)',
    crystalSystem: '正交晶系',
    locality: '内蒙古四子王旗',
    collectionDate: '2023-06-20',
    collector: '李教授',
    thinSectionNumber: 'TS-Du-001',
    thicknessMicrometers: 28,
    coverSlip: true,
    mountingMedium: '冷杉胶',
    grainSizeMm: 0.8,
    rockType: '变质岩',
    alterationDegree: 5,
    sampleBoxId: 1,
    boxPosition: 'A2',
    notes: '典型蓝线石放射状集合体，产于富铝变质岩中。纤维状晶体，长约 0.5-1mm。',
  },
  {
    sampleNumber: 'PKU-GEO-2024-003',
    mineralName: '符山石',
    mineralFormula: 'Ca₁₀Mg₂Al₄(SiO₄)₅(Si₂O₇)₂(OH)₄',
    crystalSystem: '四方晶系',
    locality: '安徽铜官山',
    collectionDate: '2023-09-10',
    collector: '王博士',
    thinSectionNumber: 'TS-Ve-001',
    thicknessMicrometers: 35,
    coverSlip: true,
    mountingMedium: '环氧树脂',
    grainSizeMm: 1.2,
    rockType: '矽卡岩',
    alterationDegree: 15,
    sampleBoxId: 1,
    boxPosition: 'B1',
    notes: '黄绿色符山石，产于接触变质矽卡岩中。与石榴子石、透辉石共生。',
  },
  {
    sampleNumber: 'PKU-GEO-2024-004',
    mineralName: '十字石',
    mineralFormula: 'FeAl₄(Si₂O₇)₂O₄(OH)₂',
    crystalSystem: '单斜晶系',
    locality: '河北涞源',
    collectionDate: '2023-07-25',
    collector: '张研究员',
    thinSectionNumber: 'TS-St-001',
    thicknessMicrometers: 32,
    coverSlip: true,
    mountingMedium: '加拿大树胶',
    grainSizeMm: 1.5,
    rockType: '区域变质岩',
    alterationDegree: 20,
    sampleBoxId: 1,
    boxPosition: 'B2',
    notes: '特征十字双晶，中压相变质带指示矿物。包含石英、白云母包体。',
  },
  {
    sampleNumber: 'PKU-GEO-2024-005',
    mineralName: '红柱石',
    mineralFormula: 'Al₂SiO₅',
    crystalSystem: '正交晶系',
    locality: '北京周口店',
    collectionDate: '2023-05-18',
    collector: '教学实习队',
    thinSectionNumber: 'TS-An-001',
    thicknessMicrometers: 25,
    coverSlip: true,
    mountingMedium: '冷杉胶',
    grainSizeMm: 2.0,
    rockType: '接触变质角岩',
    alterationDegree: 8,
    sampleBoxId: 2,
    boxPosition: 'A1',
    notes: '典型接触变质产物，含碳质包体形成空晶石构造。为教学示范标本。',
  },
  {
    sampleNumber: 'PKU-GEO-2024-006',
    mineralName: '堇青石',
    mineralFormula: 'Mg₂Al₃(AlSi₅O₁₈)',
    crystalSystem: '正交晶系',
    locality: '云南个旧',
    collectionDate: '2023-10-05',
    collector: '李教授',
    thinSectionNumber: 'TS-Cd-001',
    thicknessMicrometers: 30,
    coverSlip: true,
    mountingMedium: '环氧树脂',
    grainSizeMm: 1.8,
    rockType: '热变质角岩',
    alterationDegree: 25,
    sampleBoxId: 2,
    boxPosition: 'A2',
    notes: '强多色性堇青石，含大量赤铁矿、锆石包体。部分已蚀变为绢云母。',
  },
];

export const seedOptics: Omit<MineralOptics, 'id'>[] = [
  {
    sectionId: 1,
    relief: 1.5,
    refractiveIndexMin: 1.660,
    refractiveIndexMax: 1.676,
    birefringence: 0.016,
    opticSign: 'positive',
    opticAxisAngle: 58,
    extinctionType: 'oblique',
    extinctionAngle: 15,
    pleochroism: '明显',
    pleochroismColors: 'X=无色; Y=淡紫色; Z=深粉红色',
    absorptionFormula: 'Z > Y > X',
    twinningType: 'simple',
    twinningDescription: '罕见{100}简单双晶',
    zoning: 0,
    inclusionsDescription: '含钠长石、锂云母等矿物包体，呈定向排列',
  },
  {
    sectionId: 2,
    relief: 1.8,
    refractiveIndexMin: 1.695,
    refractiveIndexMax: 1.720,
    birefringence: 0.025,
    opticSign: 'negative',
    opticAxisAngle: 72,
    extinctionType: 'parallel',
    pleochroism: '强',
    pleochroismColors: 'X=无色; Y=淡蓝色; Z=深蓝色',
    absorptionFormula: 'Z > Y > X',
    twinningType: 'none',
    zoning: 0,
    inclusionsDescription: '偶见金红石针状包体',
  },
  {
    sectionId: 3,
    relief: 1.7,
    refractiveIndexMin: 1.705,
    refractiveIndexMax: 1.732,
    birefringence: 0.027,
    opticSign: 'negative',
    opticAxisAngle: 45,
    extinctionType: 'parallel',
    pleochroism: '弱',
    pleochroismColors: 'X=淡黄; Y=黄绿; Z=橄榄绿',
    absorptionFormula: 'Z ≈ Y > X',
    twinningType: 'simple',
    twinningDescription: '{110}简单双晶常见',
    zoning: 1,
    inclusionsDescription: '含细粒磁铁矿包体',
  },
  {
    sectionId: 4,
    relief: 1.6,
    refractiveIndexMin: 1.736,
    refractiveIndexMax: 1.747,
    birefringence: 0.011,
    opticSign: 'positive',
    opticAxisAngle: 88,
    extinctionType: 'symmetrical',
    pleochroism: '弱',
    pleochroismColors: 'X=无色; Y=淡黄; Z=金黄',
    absorptionFormula: 'Z > Y ≈ X',
    twinningType: 'cyclic',
    twinningDescription: '特征十字贯穿双晶，双晶面{031}和{231}',
    zoning: 0,
    inclusionsDescription: '含石英、白云母、钛铁矿包体',
  },
  {
    sectionId: 5,
    relief: 1.1,
    refractiveIndexMin: 1.629,
    refractiveIndexMax: 1.653,
    birefringence: 0.024,
    opticSign: 'negative',
    opticAxisAngle: 86,
    extinctionType: 'parallel',
    pleochroism: '弱',
    pleochroismColors: 'X=无色; Y=肉红色; Z=无色',
    absorptionFormula: 'Y > X ≈ Z',
    twinningType: 'simple',
    twinningDescription: '{101}简单双晶',
    zoning: 0,
    inclusionsDescription: '含碳质包体，呈定向排列构成空晶石构造',
  },
];

export const seedInterferenceColors: Omit<InterferenceColor, 'id'>[] = [
  {
    sectionId: 1,
    mineralGrainId: 'G-001',
    order: 1,
    colorName: '一级灰白',
    colorHex: '#E8E8E8',
    estimatedBirefringence: 0.016,
    thicknessMicrometers: 30,
    grainOrientation: 'inclined',
    isAnomalous: 0,
    accessoryPlateUsed: '石膏试板',
    notes: '干涉色较均匀，双折率符合锂辉石标准值',
  },
  {
    sectionId: 1,
    mineralGrainId: 'G-002',
    order: 2,
    colorName: '二级蓝',
    colorHex: '#4169E1',
    estimatedBirefringence: 0.028,
    thicknessMicrometers: 30,
    grainOrientation: 'parallel',
    isAnomalous: 0,
    notes: '接近平行光轴面切面，显示最高干涉色',
  },
  {
    sectionId: 2,
    mineralGrainId: 'G-001',
    order: 1,
    colorName: '一级黄白',
    colorHex: '#FFFFE0',
    estimatedBirefringence: 0.020,
    thicknessMicrometers: 28,
    grainOrientation: 'inclined',
    isAnomalous: 0,
    notes: '纤维状集合体，整体显示蓝-黄异常干涉色',
  },
  {
    sectionId: 2,
    mineralGrainId: 'G-002',
    order: 2,
    colorName: '二级红',
    colorHex: '#DC143C',
    estimatedBirefringence: 0.025,
    thicknessMicrometers: 28,
    grainOrientation: 'parallel',
    isAnomalous: 1,
    anomalousDescription: '靛蓝-古铜色异常干涉色，可能与化学成分变化有关',
    notes: '异常干涉色明显，需结合成分分析',
  },
  {
    sectionId: 3,
    mineralGrainId: 'G-001',
    order: 2,
    colorName: '二级绿',
    colorHex: '#32CD32',
    estimatedBirefringence: 0.027,
    thicknessMicrometers: 35,
    grainOrientation: 'inclined',
    isAnomalous: 0,
    accessoryPlateUsed: '云母试板',
    notes: '干涉色鲜艳，反映较高双折率',
  },
  {
    sectionId: 4,
    mineralGrainId: 'G-001',
    order: 1,
    colorName: '一级灰黄',
    colorHex: '#DAA520',
    estimatedBirefringence: 0.011,
    thicknessMicrometers: 32,
    grainOrientation: 'inclined',
    isAnomalous: 0,
    notes: '十字双晶四象限显示不同干涉色',
  },
  {
    sectionId: 5,
    mineralGrainId: 'G-001',
    order: 2,
    colorName: '二级蓝绿',
    colorHex: '#40E0D0',
    estimatedBirefringence: 0.024,
    thicknessMicrometers: 25,
    grainOrientation: 'inclined',
    isAnomalous: 0,
    notes: '干涉色受碳质包体影响，局部较暗',
  },
];

export const seedCleavages: Omit<Cleavage, 'id'>[] = [
  {
    sectionId: 1,
    mineralGrainId: 'G-001',
    quality: 'perfect',
    numberOfDirections: 2,
    angleBetweenDirections: 87,
    cleavageTrace: '{110}完全解理，两组近于直交',
    partingDescription: '不发育',
    fractureType: '贝壳状断口',
    notes: '解理缝细而清晰，间距均匀',
  },
  {
    sectionId: 2,
    mineralGrainId: 'G-001',
    quality: 'good',
    numberOfDirections: 1,
    cleavageTrace: '{100}完全解理，纤维状延伸方向',
    notes: '平行纤维延长方向发育良好解理',
  },
  {
    sectionId: 3,
    mineralGrainId: 'G-001',
    quality: 'distinct',
    numberOfDirections: 4,
    angleBetweenDirections: 45,
    cleavageTrace: '{110}不完全解理，四组呈菱形',
    partingDescription: '可见{001}裂理',
    notes: '柱面解理不完全，晶形完好时可见',
  },
  {
    sectionId: 4,
    mineralGrainId: 'G-001',
    quality: 'good',
    numberOfDirections: 1,
    cleavageTrace: '{010}中等解理，平行晶体延长',
    fractureType: '参差状断口',
    notes: '解理与双晶纹斜交',
  },
  {
    sectionId: 5,
    mineralGrainId: 'G-001',
    quality: 'distinct',
    numberOfDirections: 1,
    cleavageTrace: '{110}不完全解理，与柱面斜交',
    notes: '解理被碳质包体截断现象明显',
  },
];

export const seedAssociations: Omit<Association, 'id'>[] = [
  {
    sectionId: 1,
    associatedMineral: '钠长石',
    relationshipType: '包裹体',
    texturalRelation: '定向排列于主矿物中',
    abundancePercent: 8,
    grainSizeMm: 0.1,
    parageneticStage: '晚期',
    notes: '出溶成因钠长石微晶，沿一定方向排列',
  },
  {
    sectionId: 1,
    associatedMineral: '锂云母',
    relationshipType: '共生',
    texturalRelation: '充填于主矿物裂隙',
    abundancePercent: 5,
    grainSizeMm: 0.05,
    parageneticStage: '热液期',
    notes: '沿裂隙分布的鳞片状集合体',
  },
  {
    sectionId: 1,
    associatedMineral: '石英',
    relationshipType: '基质',
    texturalRelation: '他形粒状填隙',
    abundancePercent: 15,
    grainSizeMm: 0.5,
    parageneticStage: '主期',
    notes: '伟晶岩主要造岩矿物',
  },
  {
    sectionId: 2,
    associatedMineral: '黑云母',
    relationshipType: '共生',
    texturalRelation: '片状集合体伴生',
    abundancePercent: 12,
    grainSizeMm: 0.3,
    parageneticStage: '主变质期',
    notes: '绿泥石化明显',
  },
  {
    sectionId: 2,
    associatedMineral: '石英',
    relationshipType: '基质',
    texturalRelation: '他形粒状',
    abundancePercent: 20,
    grainSizeMm: 0.2,
    parageneticStage: '主变质期',
    notes: '与蓝线石同期形成',
  },
  {
    sectionId: 2,
    associatedMineral: '金红石',
    relationshipType: '包裹体',
    texturalRelation: '针状包体',
    abundancePercent: 1,
    grainSizeMm: 0.02,
    parageneticStage: '同生',
    notes: '细小针状金红石，显示三向排列',
  },
  {
    sectionId: 3,
    associatedMineral: '钙铝榴石',
    relationshipType: '共生',
    texturalRelation: '自形晶伴生',
    abundancePercent: 25,
    grainSizeMm: 1.0,
    parageneticStage: '早期矽卡岩期',
    notes: '淡绿色钙铝榴石，晶形完好',
  },
  {
    sectionId: 3,
    associatedMineral: '透辉石',
    relationshipType: '共生',
    texturalRelation: '粒状镶嵌',
    abundancePercent: 18,
    grainSizeMm: 0.8,
    parageneticStage: '早期矽卡岩期',
    notes: '淡绿色透辉石，可见双晶',
  },
  {
    sectionId: 4,
    associatedMineral: '白云母',
    relationshipType: '共生',
    texturalRelation: '片状伴生',
    abundancePercent: 15,
    grainSizeMm: 0.5,
    parageneticStage: '主变质期',
    notes: '新鲜白云母，解理发育',
  },
  {
    sectionId: 4,
    associatedMineral: '石英',
    relationshipType: '基质',
    texturalRelation: '他形填隙',
    abundancePercent: 30,
    grainSizeMm: 0.3,
    parageneticStage: '主变质期',
    notes: '细粒石英集合体',
  },
  {
    sectionId: 5,
    associatedMineral: '碳质',
    relationshipType: '包裹体',
    texturalRelation: '定向排列',
    abundancePercent: 3,
    parageneticStage: '同生',
    notes: '构成典型空晶石构造',
  },
  {
    sectionId: 5,
    associatedMineral: '绢云母',
    relationshipType: '蚀变产物',
    texturalRelation: '沿边部及裂隙分布',
    abundancePercent: 8,
    parageneticStage: '退变质期',
    notes: '轻微蚀变，不影响主矿物特征',
  },
];

export const seedMicrographs: Omit<Micrograph, 'id'>[] = [
  {
    sectionId: 1,
    mode: 'ppl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/1/ppl_40x.svg',
    exposureMs: 50,
    capturedAt: '2024-01-15T10:30:00Z',
    capturedBy: '显微镜操作员 A',
    notes: '单偏光下显示粉红色多色性',
  },
  {
    sectionId: 1,
    mode: 'xpl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/1/xpl_40x.svg',
    analyzerAngle: 0,
    accessoryPlate: '无',
    exposureMs: 60,
    capturedAt: '2024-01-15T10:32:00Z',
    capturedBy: '显微镜操作员 A',
    notes: '正交偏光下显示一级灰白至二级蓝干涉色',
  },
  {
    sectionId: 1,
    mode: 'xpl',
    magnification: 100,
    scaleBarMicrometers: 200,
    imagePath: '/images/sections/1/xpl_100x.svg',
    analyzerAngle: 0,
    accessoryPlate: '石膏试板',
    exposureMs: 80,
    capturedAt: '2024-01-15T10:35:00Z',
    capturedBy: '显微镜操作员 A',
    notes: '加入石膏试板确定光性符号为正',
  },
  {
    sectionId: 2,
    mode: 'ppl',
    magnification: 100,
    scaleBarMicrometers: 200,
    imagePath: '/images/sections/2/ppl_100x.svg',
    exposureMs: 45,
    capturedAt: '2024-01-16T14:20:00Z',
    capturedBy: '显微镜操作员 A',
    notes: '单偏光下显示蓝色多色性及放射状集合体形态',
  },
  {
    sectionId: 2,
    mode: 'xpl',
    magnification: 100,
    scaleBarMicrometers: 200,
    imagePath: '/images/sections/2/xpl_100x.svg',
    analyzerAngle: 0,
    exposureMs: 55,
    capturedAt: '2024-01-16T14:22:00Z',
    capturedBy: '显微镜操作员 A',
    notes: '正交偏光下显示异常干涉色',
  },
  {
    sectionId: 3,
    mode: 'ppl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/3/ppl_40x.svg',
    exposureMs: 55,
    capturedAt: '2024-01-17T09:15:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '单偏光下显示黄绿色及典型柱状晶形',
  },
  {
    sectionId: 3,
    mode: 'xpl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/3/xpl_40x.svg',
    analyzerAngle: 0,
    exposureMs: 65,
    capturedAt: '2024-01-17T09:17:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '正交偏光下显示高级白干涉色，环带结构明显',
  },
  {
    sectionId: 4,
    mode: 'ppl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/4/ppl_40x.svg',
    exposureMs: 40,
    capturedAt: '2024-01-18T11:00:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '单偏光下显示特征十字形双晶',
  },
  {
    sectionId: 4,
    mode: 'xpl',
    magnification: 40,
    scaleBarMicrometers: 500,
    imagePath: '/images/sections/4/xpl_40x.svg',
    analyzerAngle: 0,
    exposureMs: 50,
    capturedAt: '2024-01-18T11:02:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '正交偏光下十字双晶四个象限干涉色不同',
  },
  {
    sectionId: 5,
    mode: 'ppl',
    magnification: 100,
    scaleBarMicrometers: 200,
    imagePath: '/images/sections/5/ppl_100x.svg',
    exposureMs: 48,
    capturedAt: '2024-01-19T15:30:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '单偏光下显示空晶石构造，碳质包体定向排列',
  },
  {
    sectionId: 5,
    mode: 'xpl',
    magnification: 100,
    scaleBarMicrometers: 200,
    imagePath: '/images/sections/5/xpl_100x.svg',
    analyzerAngle: 0,
    accessoryPlate: '云母试板',
    exposureMs: 58,
    capturedAt: '2024-01-19T15:32:00Z',
    capturedBy: '显微镜操作员 B',
    notes: '正交偏光下干涉色受碳质影响局部变暗',
  },
];

export const seedVersionBatches = [
  {
    batchId: 'BATCH-2024-001',
    description: '初始数据导入批次',
    timestamp: '2024-01-20T00:00:00Z',
    sectionIds: [1, 2, 3, 4, 5, 6],
  },
  {
    batchId: 'BATCH-2024-002',
    description: '光学数据复核更新',
    timestamp: '2024-02-15T00:00:00Z',
    sectionIds: [1, 3, 5],
  },
];
