import { loadDb } from "./index.server";
import {
  createRecord,
  createSolution,
  createBatch,
  createAudition,
  createReminder,
  getAllRecords,
  getAllBatches,
} from "./queries.server";

function runSeed() {
  const db = loadDb();
  if (db.vinyl_records.length > 0) {
    return;
  }

  console.log("Seeding vinyl database...");

  const records = [
    {
      catalog_no: "APP-010",
      artist: "Pink Floyd",
      album: "The Dark Side of the Moon",
      year: 1973,
      genre: "Progressive Rock",
      condition: "VG+" as const,
      weight: 180,
      pressing: "Harvest UK 1st Press",
      notes: "Gatefold sleeve, minor ring wear",
    },
    {
      catalog_no: "SW-498",
      artist: "Miles Davis",
      album: "Kind of Blue",
      year: 1959,
      genre: "Jazz",
      condition: "VG" as const,
      weight: 140,
      pressing: "Columbia 6-Eye Mono",
      notes: "Deep groove, label has initials",
    },
    {
      catalog_no: "P-10012A",
      artist: "The Beatles",
      album: "Abbey Road",
      year: 1969,
      genre: "Rock",
      condition: "NM" as const,
      weight: 180,
      pressing: "Apple Japan Red Wax",
      notes: "With OBI strip, insert included",
    },
    {
      catalog_no: "ECM-1017",
      artist: "Keith Jarrett",
      album: "The Köln Concert",
      year: 1975,
      genre: "Jazz",
      condition: "NM" as const,
      weight: 160,
      pressing: "ECM Germany",
      notes: "Top copy, minimal spindle marks",
    },
    {
      catalog_no: "BSK-3093",
      artist: "Fleetwood Mac",
      album: "Rumours",
      year: 1977,
      genre: "Rock",
      condition: "VG" as const,
      weight: 130,
      pressing: "Warner US Club Press",
      notes: "Textured cover, slight warp that plays through",
    },
    {
      catalog_no: "B0022415-01",
      artist: "Radiohead",
      album: "OK Computer",
      year: 2016,
      genre: "Alternative",
      condition: "M" as const,
      weight: 180,
      pressing: "XL Recordings Reissue",
      notes: "Sealed until yesterday, 180g virgin vinyl",
    },
    {
      catalog_no: "SP-100",
      artist: "Sun Ra",
      album: "Space Is the Place",
      year: 1973,
      genre: "Free Jazz",
      condition: "G+" as const,
      weight: 130,
      pressing: "Blue Thumb US",
      notes: "Heavy groove wear on Side B, needs deep clean",
    },
  ];

  const createdRecords = records.map((r) => createRecord(r));
  console.log(`  Created ${createdRecords.length} vinyl records`);

  const solutions = [
    {
      name: "Vinyl Clear Enzymatic",
      brand: "Audio Desk",
      type: "enzymatic" as const,
      ph: 7.2,
      dilution_ratio: "1:4",
      volume_ml: 500,
      opened_date: "2026-01-15",
      expiry_date: "2026-07-15",
      is_active: 1,
      notes: "Protein-based for organic contaminants",
    },
    {
      name: "Pure Distilled H2O",
      brand: "Lab Grade",
      type: "distilled" as const,
      ph: 7.0,
      dilution_ratio: "N/A",
      volume_ml: 2000,
      opened_date: "2026-02-01",
      expiry_date: "2027-02-01",
      is_active: 1,
      notes: "0 TDS, for final rinse",
    },
    {
      name: "Record Revival",
      brand: "Mobile Fidelity",
      type: "surfactant" as const,
      ph: 6.8,
      dilution_ratio: "1:10",
      volume_ml: 1000,
      opened_date: "2025-12-20",
      expiry_date: "2026-06-20",
      is_active: 1,
      notes: "Expires soon - will need replacement batch soon",
    },
    {
      name: "Isopropyl Rinse",
      brand: "Generic",
      type: "alcohol" as const,
      ph: 5.5,
      dilution_ratio: "20% IPA",
      volume_ml: 500,
      opened_date: "2025-11-01",
      expiry_date: "2026-05-01",
      is_active: 0,
      notes: "Deprecated - too harsh for shellac pressings",
    },
  ];

  const createdSolutions = solutions.map((s) => createSolution(s));
  console.log(`  Created ${createdSolutions.length} cleaning solutions`);

  const now = new Date();
  const daysAgo = (d: number) => {
    const date = new Date(now);
    date.setDate(date.getDate() - d);
    return date.toISOString().replace("T", " ").slice(0, 19);
  };

  const batches = [
    {
      record_id: createdRecords[0].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Carbon Fiber",
      brush_count: 12,
      ultrasonic_minutes: 10,
      ultrasonic_temp_c: 28,
      rinse_count: 3,
      drying_method: "Vacuum",
      drying_minutes: 45,
      operator: "LF",
      pre_noise_level: 7.2,
      post_noise_level: 2.1,
      crackle_reduction: 68,
      result_rating: 4 as const,
      anomalies: "",
      notes: "B-side dramatic improvement; very light groove wear",
      cleaned_at: daysAgo(45),
    },
    {
      record_id: createdRecords[1].id,
      solution_id: createdSolutions[2].id,
      brush_type: "Goat Hair",
      brush_count: 25,
      ultrasonic_minutes: 15,
      ultrasonic_temp_c: 30,
      rinse_count: 4,
      drying_method: "Air Dry",
      drying_minutes: 120,
      operator: "LF",
      pre_noise_level: 8.5,
      post_noise_level: 5.3,
      crackle_reduction: 35,
      result_rating: 3 as const,
      anomalies: "Slight groove distortion still present on first 2 tracks",
      notes: "Deep groove wear limits improvement; consider ultrasonic bath repeat",
      cleaned_at: daysAgo(38),
    },
    {
      record_id: createdRecords[2].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Carbon Fiber",
      brush_count: 8,
      ultrasonic_minutes: 8,
      ultrasonic_temp_c: 27,
      rinse_count: 2,
      drying_method: "Vacuum",
      drying_minutes: 30,
      operator: "AY",
      pre_noise_level: 1.5,
      post_noise_level: 0.8,
      crackle_reduction: 45,
      result_rating: 5 as const,
      anomalies: "",
      notes: "Near mint copy; clean was purely preventative",
      cleaned_at: daysAgo(30),
    },
    {
      record_id: createdRecords[3].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Carbon Fiber",
      brush_count: 10,
      ultrasonic_minutes: 10,
      ultrasonic_temp_c: 28,
      rinse_count: 3,
      drying_method: "Vacuum",
      drying_minutes: 40,
      operator: "LF",
      pre_noise_level: 2.0,
      post_noise_level: 0.9,
      crackle_reduction: 60,
      result_rating: 5 as const,
      anomalies: "",
      notes: "Pristine result; quietest pressing in library",
      cleaned_at: daysAgo(25),
    },
    {
      record_id: createdRecords[4].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Goat Hair",
      brush_count: 18,
      ultrasonic_minutes: 12,
      ultrasonic_temp_c: 29,
      rinse_count: 3,
      drying_method: "Vacuum",
      drying_minutes: 60,
      operator: "AY",
      pre_noise_level: 6.8,
      post_noise_level: 3.4,
      crackle_reduction: 55,
      result_rating: 3 as const,
      anomalies: "Slight warp, some ticking on side 2",
      notes: "Significant crackle reduction; non-fill spots remain",
      cleaned_at: daysAgo(20),
    },
    {
      record_id: createdRecords[5].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Carbon Fiber",
      brush_count: 5,
      ultrasonic_minutes: 5,
      ultrasonic_temp_c: 27,
      rinse_count: 2,
      drying_method: "Vacuum",
      drying_minutes: 30,
      operator: "LF",
      pre_noise_level: 0.5,
      post_noise_level: 0.3,
      crackle_reduction: 30,
      result_rating: 5 as const,
      anomalies: "",
      notes: "Brand new sealed copy; light wash only to remove mold release",
      cleaned_at: daysAgo(10),
    },
    {
      record_id: createdRecords[6].id,
      solution_id: createdSolutions[2].id,
      brush_type: "Goat Hair",
      brush_count: 60,
      ultrasonic_minutes: 45,
      ultrasonic_temp_c: 32,
      rinse_count: 6,
      drying_method: "Air Dry",
      drying_minutes: 180,
      operator: "AY",
      pre_noise_level: 9.5,
      post_noise_level: 10.2,
      crackle_reduction: -8,
      result_rating: 1 as const,
      anomalies: "Noise increased after cleaning; possible groove damage",
      notes: "Aggressive cleaning; record has deep irreversible groove wear; sound quality deteriorated. **WARNING: noise increased after treatment - do not use this protocol again.**",
      cleaned_at: daysAgo(5),
    },
    {
      record_id: createdRecords[1].id,
      solution_id: createdSolutions[0].id,
      brush_type: "Microfiber Pad",
      brush_count: 15,
      ultrasonic_minutes: 12,
      ultrasonic_temp_c: 28,
      rinse_count: 3,
      drying_method: "Vacuum",
      drying_minutes: 50,
      operator: "LF",
      pre_noise_level: 5.3,
      post_noise_level: 3.8,
      crackle_reduction: 28,
      result_rating: 3 as const,
      anomalies: "",
      notes: "Second pass on Miles Davis with enzymatic solution; marginal improvement",
      cleaned_at: daysAgo(3),
    },
  ];

  const createdBatches = batches.map((b) => {
    const rec = createdRecords.find((r) => r.id === b.record_id)!;
    const idx = batches.indexOf(b);
    const code = `VC${2026}${String(Math.floor((50 - idx * 5) / 30) + 4).padStart(2, "0")}${String((50 - idx * 5) % 28 + 1).padStart(2, "0")}${String(idx + 1).padStart(3, "0")}`;
    return createBatch({ ...b, batch_code: code });
  });
  console.log(`  Created ${createdBatches.length} cleaning batches`);

  const auditions = [
    {
      record_id: createdRecords[0].id,
      batch_id: createdBatches[0].id,
      side: "A" as const,
      track_no: 1,
      noise_level: 2.0,
      crackles: 12,
      pops: 2,
      surface_noise: 1.5,
      distortion: 0,
      warble: 0,
      inner_groove_distortion: 0,
      listener: "LF",
      equipment: "Technics SL-1200G / Ortofon 2M Blue",
      notes: "First 30 seconds light crackle, then settles nicely",
      auditioned_at: daysAgo(44),
    },
    {
      record_id: createdRecords[0].id,
      batch_id: createdBatches[0].id,
      side: "B" as const,
      track_no: 1,
      noise_level: 2.2,
      crackles: 18,
      pops: 3,
      surface_noise: 1.7,
      distortion: 0,
      warble: 0,
      inner_groove_distortion: 0,
      listener: "LF",
      equipment: "Technics SL-1200G / Ortofon 2M Blue",
      notes: "Money - cleaned up very well",
      auditioned_at: daysAgo(44),
    },
    {
      record_id: createdRecords[1].id,
      batch_id: createdBatches[1].id,
      side: "A" as const,
      track_no: 1,
      noise_level: 5.0,
      crackles: 120,
      pops: 25,
      surface_noise: 4.5,
      distortion: 1,
      warble: 0,
      inner_groove_distortion: 0,
      listener: "AY",
      equipment: "VPI Classic 3 / Shure V15VxMR",
      notes: "So What - heavy groove wear limits playback",
      auditioned_at: daysAgo(37),
    },
    {
      record_id: createdRecords[2].id,
      batch_id: createdBatches[2].id,
      side: "A" as const,
      track_no: 2,
      noise_level: 0.7,
      crackles: 3,
      pops: 0,
      surface_noise: 0.5,
      distortion: 0,
      warble: 0,
      inner_groove_distortion: 0,
      listener: "LF",
      equipment: "Technics SL-1200G / Ortofon 2M Blue",
      notes: "Come Together - stunning; Japanese pressing is dead quiet",
      auditioned_at: daysAgo(29),
    },
    {
      record_id: createdRecords[6].id,
      batch_id: createdBatches[6].id,
      side: "B" as const,
      track_no: 3,
      noise_level: 10.5,
      crackles: 250,
      pops: 60,
      surface_noise: 9.0,
      distortion: 1,
      warble: 1,
      inner_groove_distortion: 1,
      listener: "AY",
      equipment: "VPI Classic 3 / Shure V15VxMR",
      notes: "Severe degradation; potential groove collapse from over-cleaning",
      auditioned_at: daysAgo(4),
    },
  ];

  auditions.forEach((a) => createAudition(a));
  console.log(`  Created ${auditions.length} audition logs`);

  const reminders = [
    {
      type: "brush_replace" as const,
      target: "Carbon Fiber Brush #1",
      threshold_count: 100,
      threshold_date: null,
      current_count: 87,
      is_triggered: 1,
      last_maintenance: "2026-03-01",
      notes: "Approaching end of life",
    },
    {
      type: "solution_refill" as const,
      target: "Enzymatic Bath",
      threshold_count: 50,
      threshold_date: null,
      current_count: 32,
      is_triggered: 0,
      last_maintenance: "2026-04-10",
      notes: "",
    },
    {
      type: "ultrasonic_filter" as const,
      target: "Ultrasonic Cleaner Tank 1",
      threshold_count: 200,
      threshold_date: null,
      current_count: 45,
      is_triggered: 0,
      last_maintenance: "2026-02-15",
      notes: "",
    },
    {
      type: "pad_replace" as const,
      target: "Vacuum Suction Pads",
      threshold_count: 80,
      threshold_date: null,
      current_count: 12,
      is_triggered: 0,
      last_maintenance: "2026-05-01",
      notes: "",
    },
    {
      type: "machine_calibration" as const,
      target: "VPI HW-17",
      threshold_count: null,
      threshold_date: "2026-07-01",
      current_count: 0,
      is_triggered: 0,
      last_maintenance: "2025-07-01",
      notes: "Annual calibration",
    },
  ];

  reminders.forEach((r) => createReminder(r));
  console.log(`  Created ${reminders.length} maintenance reminders`);

  console.log("Database seed complete.");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  runSeed();
}

export default runSeed;
