import { db } from "./index";
import { users, records, nodes, attachments, evidenceItems, STATUS, NODE_TYPES, EXCEPTION_TYPES, ROLES } from "./schema";
import { eq, sql } from "drizzle-orm";

export async function seed() {
  console.log("🌱 开始种子数据...");

  await db.execute(sql`DELETE FROM evidence_items`);
  await db.execute(sql`DELETE FROM attachments`);
  await db.execute(sql`DELETE FROM nodes`);
  await db.execute(sql`DELETE FROM records`);
  await db.execute(sql`DELETE FROM users`);
  
  await db.execute(sql`ALTER SEQUENCE evidence_items_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE attachments_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE nodes_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE records_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE users_id_seq RESTART WITH 1`);

  const userList = await db.insert(users).values([
    { username: "zhangwei", displayName: "张伟", role: ROLES.APPLICANT, department: "集装箱操作部", avatarColor: "#3b82f6" },
    { username: "liming", displayName: "李明", role: ROLES.HANDLER, department: "检验检疫科", avatarColor: "#10b981" },
    { username: "wangfang", displayName: "王芳", role: ROLES.REVIEWER, department: "复核审批部", avatarColor: "#f59e0b" },
    { username: "chenjie", displayName: "陈杰", role: ROLES.ARCHIVIST, department: "档案管理室", avatarColor: "#8b5cf6" },
    { username: "liuyang", displayName: "刘洋", role: ROLES.APPLICANT, department: "现场操作组", avatarColor: "#ef4444" },
  ]).returning();

  console.log("✅ 用户数据创建完成");

  const now = new Date();
  const dayMs = 24 * 60 * 60 * 1000;

  const sample1 = await db.insert(records).values({
    recordNo: "SEAL-2024-0001",
    containerNo: "MSKU1234567",
    sealNo: "SEAL-A001234",
    vesselName: "马士基埃德蒙顿",
    voyageNo: "V2401E",
    blNo: "MAEU202401001",
    customer: "上海振华物流有限公司",
    exceptionType: EXCEPTION_TYPES.NORMAL,
    status: STATUS.ARCHIVED,
    source: "系统自动核验",
    currentHandlerId: userList[3].id,
    applicantId: userList[0].id,
    reviewerId: userList[2].id,
    amount: "0.00",
    sealTime: new Date(now.getTime() - 10 * dayMs),
    arrivalTime: new Date(now.getTime() - 7 * dayMs),
    summary: "铅封完好无损，核验通过，正常放箱",
    conclusion: "经核验，集装箱铅封完好，编号一致，无异常情况，准予正常放箱。",
    basis: "《港口集装箱铅封管理规范》第3.2条；现场检验照片2张；铅封编号匹配记录",
    isArchived: true,
    createdAt: new Date(now.getTime() - 10 * dayMs),
    updatedAt: new Date(now.getTime() - 3 * dayMs),
    archivedAt: new Date(now.getTime() - 3 * dayMs),
  }).returning();

  await db.insert(nodes).values([
    {
      recordId: sample1[0].id,
      nodeType: NODE_TYPES.ACCEPT,
      nodeName: "受理登记",
      status: "completed",
      operatorId: userList[0].id,
      operatorName: userList[0].displayName,
      comment: "系统自动识别铅封信息，人工确认受理",
      sequence: 1,
      createdAt: new Date(now.getTime() - 10 * dayMs),
    },
    {
      recordId: sample1[0].id,
      nodeType: NODE_TYPES.PROCESS,
      nodeName: "现场核验",
      status: "completed",
      operatorId: userList[1].id,
      operatorName: userList[1].displayName,
      comment: "现场核对铅封编号 SEAL-A001234 与系统记录一致，铅封完好无破损",
      basis: "现场照片、铅封登记台账",
      sequence: 2,
      createdAt: new Date(now.getTime() - 8 * dayMs),
    },
    {
      recordId: sample1[0].id,
      nodeType: NODE_TYPES.REVIEW,
      nodeName: "复核审批",
      status: "completed",
      operatorId: userList[2].id,
      operatorName: userList[2].displayName,
      comment: "核验材料齐全，流程规范，同意放箱",
      basis: "《铅封核验管理办法》第十二条",
      sequence: 3,
      createdAt: new Date(now.getTime() - 5 * dayMs),
    },
    {
      recordId: sample1[0].id,
      nodeType: NODE_TYPES.ARCHIVE,
      nodeName: "归档结案",
      status: "completed",
      operatorId: userList[3].id,
      operatorName: userList[3].displayName,
      comment: "材料完整，归档保存",
      sequence: 4,
      createdAt: new Date(now.getTime() - 3 * dayMs),
    },
  ]);

  await db.insert(attachments).values([
    {
      recordId: sample1[0].id,
      fileName: "铅封正面照.jpg",
      fileType: "image/jpeg",
      fileSize: 2048000,
      fileUrl: "/attachments/seal-front-001.jpg",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "铅封正面清晰照片，编号 SEAL-A001234",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 8 * dayMs),
    },
    {
      recordId: sample1[0].id,
      fileName: "铅封侧面照.jpg",
      fileType: "image/jpeg",
      fileSize: 1850000,
      fileUrl: "/attachments/seal-side-001.jpg",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "铅封侧面完好性照片",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 8 * dayMs),
    },
    {
      recordId: sample1[0].id,
      fileName: "放箱通知单.pdf",
      fileType: "application/pdf",
      fileSize: 156000,
      fileUrl: "/attachments/release-notice-001.pdf",
      version: "1.0",
      uploadedBy: userList[2].id,
      uploaderName: userList[2].displayName,
      description: "复核通过后的放箱通知单",
      isEvidence: false,
      createdAt: new Date(now.getTime() - 5 * dayMs),
    },
  ]);

  await db.insert(evidenceItems).values([
    {
      recordId: sample1[0].id,
      type: "photo",
      title: "铅封正面照片",
      content: "铅封编号 SEAL-A001234，清晰可见",
      status: "valid",
      verified: true,
      verifiedBy: userList[2].id,
      verifiedAt: new Date(now.getTime() - 5 * dayMs),
      createdAt: new Date(now.getTime() - 8 * dayMs),
    },
    {
      recordId: sample1[0].id,
      type: "document",
      title: "铅封登记台账记录",
      content: "台账编号：LD-2024-0105，记录人与时间一致",
      status: "valid",
      verified: true,
      verifiedBy: userList[2].id,
      verifiedAt: new Date(now.getTime() - 5 * dayMs),
      createdAt: new Date(now.getTime() - 8 * dayMs),
    },
  ]);

  console.log("✅ 样本1（正常核销）创建完成");

  const sample2 = await db.insert(records).values({
    recordNo: "SEAL-2024-0028",
    containerNo: "CMAU9876543",
    sealNo: "SEAL-B005678",
    vesselName: "达飞泰特斯",
    voyageNo: "FT2412W",
    blNo: "CMDU202402056",
    customer: "宁波远洋运输股份有限公司",
    exceptionType: EXCEPTION_TYPES.MISSING_RECORD,
    status: STATUS.RETURNED,
    source: "人工申报",
    currentHandlerId: userList[0].id,
    applicantId: userList[0].id,
    reviewerId: userList[2].id,
    amount: "5000.00",
    sealTime: new Date(now.getTime() - 5 * dayMs),
    arrivalTime: new Date(now.getTime() - 3 * dayMs),
    summary: "现场记录缺失到达时间，退回补证",
    conclusion: "待补充完整记录后重新提交复核",
    basis: "《集装箱核验操作规范》第5条：所有关键时间节点必须记录在案",
    blockReason: "1. 到达时间记录缺失；2. 现场操作人员签字不完整；3. 铅封核验记录单编号不连续",
    remedyPath: "1. 补充到达时间的系统日志截图；2. 补签现场操作人员姓名；3. 说明记录单编号不连续的原因并提供证明",
    diffFields: {
      arrivalTime: { before: null, after: "待补充", label: "到达时间" },
      operatorSignature: { before: null, after: "待补签", label: "操作人签字" },
      recordSerial: { before: "断号", after: "待说明", label: "记录编号连续性" },
    },
    isArchived: false,
    createdAt: new Date(now.getTime() - 6 * dayMs),
    updatedAt: new Date(now.getTime() - 1 * dayMs),
  }).returning();

  await db.insert(nodes).values([
    {
      recordId: sample2[0].id,
      nodeType: NODE_TYPES.ACCEPT,
      nodeName: "受理登记",
      status: "completed",
      operatorId: userList[0].id,
      operatorName: userList[0].displayName,
      comment: "人工申报铅封异常，初步受理",
      sequence: 1,
      createdAt: new Date(now.getTime() - 6 * dayMs),
    },
    {
      recordId: sample2[0].id,
      nodeType: NODE_TYPES.PROCESS,
      nodeName: "现场核验",
      status: "completed",
      operatorId: userList[1].id,
      operatorName: userList[1].displayName,
      comment: "现场核验发现记录不完整，到达时间未填写",
      fieldChanges: {
        status: { before: "pending_accept", after: "processing" },
      },
      sequence: 2,
      createdAt: new Date(now.getTime() - 4 * dayMs),
    },
    {
      recordId: sample2[0].id,
      nodeType: NODE_TYPES.RETURN,
      nodeName: "复核退回",
      status: "returned",
      operatorId: userList[2].id,
      operatorName: userList[2].displayName,
      comment: "记录不完整，需要补证。具体问题：到达时间缺失、签字不全、编号不连续",
      basis: "《集装箱核验操作规范》第5条",
      fieldChanges: {
        status: { before: "pending_review", after: "returned" },
        conclusion: { before: "待审核", after: "待补充完整记录后重新提交复核" },
      },
      snapshotBefore: {
        arrivalTime: null,
        hasSignature: false,
        recordSerial: "不连续",
      },
      snapshotAfter: {
        arrivalTime: "待补充",
        hasSignature: "待补签",
        recordSerial: "待说明",
      },
      sequence: 3,
      createdAt: new Date(now.getTime() - 1 * dayMs),
    },
  ]);

  await db.insert(attachments).values([
    {
      recordId: sample2[0].id,
      fileName: "铅封照片.jpg",
      fileType: "image/jpeg",
      fileSize: 1980000,
      fileUrl: "/attachments/seal-028.jpg",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "铅封外观照片，编号 SEAL-B005678",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 4 * dayMs),
    },
    {
      recordId: sample2[0].id,
      fileName: "核验记录单.pdf",
      fileType: "application/pdf",
      fileSize: 245000,
      fileUrl: "/attachments/checklist-028.pdf",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "现场核验记录单（不完整）",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 4 * dayMs),
    },
  ]);

  await db.insert(evidenceItems).values([
    {
      recordId: sample2[0].id,
      type: "photo",
      title: "铅封照片",
      content: "铅封外观完好，编号 SEAL-B005678",
      status: "valid",
      verified: false,
      createdAt: new Date(now.getTime() - 4 * dayMs),
    },
  ]);

  console.log("✅ 样本2（记录漏填）创建完成");

  const sample3 = await db.insert(records).values({
    recordNo: "SEAL-2024-0045",
    containerNo: "COSCO5678901",
    sealNo: "SEAL-C009876",
    vesselName: "中远荷兰号",
    voyageNo: "COS-2408N",
    blNo: "COSU202403120",
    customer: "中远海运集装箱运输有限公司",
    exceptionType: EXCEPTION_TYPES.ATTACHMENT_VERSION_MISMATCH,
    status: STATUS.PROCESSING,
    source: "系统比对发现",
    currentHandlerId: userList[1].id,
    applicantId: userList[4].id,
    reviewerId: userList[2].id,
    amount: "12000.00",
    sealTime: new Date(now.getTime() - 8 * dayMs),
    arrivalTime: new Date(now.getTime() - 5 * dayMs),
    summary: "附件版本不一致，铅封照片有两个版本",
    conclusion: "待确认附件版本，查明版本差异原因",
    basis: "《电子证据管理规定》第8条：证据附件必须版本唯一、可追溯",
    blockReason: "同一铅封存在两个不同版本的照片附件：v1.0（拍摄时间10:23）和 v1.1（拍摄时间14:56），两版照片背景光线不同，疑似重新拍摄",
    remedyPath: "1. 核实两个版本照片的拍摄人和拍摄原因；2. 确认哪一版为首次拍摄的原始照片；3. 说明重新拍摄的原因并提供相关审批记录",
    diffFields: {
      attachmentVersion: { before: "1.0", after: "1.1", label: "附件版本号" },
      photoTimestamp: { before: "2024-03-15 10:23", after: "2024-03-15 14:56", label: "照片拍摄时间" },
      fileHash: { before: "a1b2c3d4", after: "e5f6g7h8", label: "文件哈希值" },
    },
    isArchived: false,
    createdAt: new Date(now.getTime() - 9 * dayMs),
    updatedAt: new Date(now.getTime() - 2 * dayMs),
  }).returning();

  await db.insert(nodes).values([
    {
      recordId: sample3[0].id,
      nodeType: NODE_TYPES.ACCEPT,
      nodeName: "受理登记",
      status: "completed",
      operatorId: userList[4].id,
      operatorName: userList[4].displayName,
      comment: "现场申报铅封核验",
      sequence: 1,
      createdAt: new Date(now.getTime() - 9 * dayMs),
    },
    {
      recordId: sample3[0].id,
      nodeType: NODE_TYPES.SUPPLEMENT,
      nodeName: "补充材料",
      status: "completed",
      operatorId: userList[4].id,
      operatorName: userList[4].displayName,
      comment: "补充了第二版照片（光线更好）",
      fieldChanges: {
        attachmentCount: { before: 1, after: 2, label: "附件数量" },
      },
      sequence: 2,
      createdAt: new Date(now.getTime() - 6 * dayMs),
    },
    {
      recordId: sample3[0].id,
      nodeType: NODE_TYPES.PROCESS,
      nodeName: "版本核验",
      status: "processing",
      operatorId: userList[1].id,
      operatorName: userList[1].displayName,
      comment: "系统比对发现两个版本照片存在差异，正在核实原因",
      basis: "《电子证据管理规定》第8条",
      fieldChanges: {
        status: { before: "pending_accept", after: "processing" },
        exceptionType: { before: "normal", after: "attachment_version_mismatch" },
      },
      snapshotBefore: {
        version: "1.0",
        photoTime: "10:23",
        hash: "a1b2c3d4",
      },
      snapshotAfter: {
        version: "1.1",
        photoTime: "14:56",
        hash: "e5f6g7h8",
      },
      sequence: 3,
      createdAt: new Date(now.getTime() - 2 * dayMs),
    },
  ]);

  await db.insert(attachments).values([
    {
      recordId: sample3[0].id,
      fileName: "铅封照片_v1.jpg",
      fileType: "image/jpeg",
      fileSize: 2100000,
      fileUrl: "/attachments/seal-045-v1.jpg",
      version: "1.0",
      uploadedBy: userList[4].id,
      uploaderName: userList[4].displayName,
      description: "原始铅封照片（第一版），拍摄时间 10:23",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 9 * dayMs),
    },
    {
      recordId: sample3[0].id,
      fileName: "铅封照片_v2.jpg",
      fileType: "image/jpeg",
      fileSize: 2250000,
      fileUrl: "/attachments/seal-045-v2.jpg",
      version: "1.1",
      uploadedBy: userList[4].id,
      uploaderName: userList[4].displayName,
      description: "重新拍摄的铅封照片（第二版），拍摄时间 14:56，声称光线更清晰",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 6 * dayMs),
    },
    {
      recordId: sample3[0].id,
      fileName: "铅封使用登记台账.xlsx",
      fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      fileSize: 45000,
      fileUrl: "/attachments/ledger-045.xlsx",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "铅封使用登记台账",
      isEvidence: false,
      createdAt: new Date(now.getTime() - 2 * dayMs),
    },
  ]);

  await db.insert(evidenceItems).values([
    {
      recordId: sample3[0].id,
      type: "photo",
      title: "铅封照片 v1.0",
      content: "拍摄时间 10:23，哈希 a1b2c3d4",
      status: "questioned",
      verified: false,
      createdAt: new Date(now.getTime() - 9 * dayMs),
    },
    {
      recordId: sample3[0].id,
      type: "photo",
      title: "铅封照片 v1.1",
      content: "拍摄时间 14:56，哈希 e5f6g7h8",
      status: "questioned",
      verified: false,
      createdAt: new Date(now.getTime() - 6 * dayMs),
    },
  ]);

  console.log("✅ 样本3（附件版本不一致）创建完成");

  const sample4 = await db.insert(records).values({
    recordNo: "SEAL-2024-0019",
    containerNo: "ONE4567890",
    sealNo: "SEAL-D003421",
    vesselName: "海洋网联东京",
    voyageNo: "ONE-2405T",
    blNo: "ONEY202402089",
    customer: "东方海外货柜航运有限公司",
    exceptionType: EXCEPTION_TYPES.RE_PROCESS,
    status: STATUS.PENDING_REVIEW,
    source: "档案抽检发现",
    currentHandlerId: userList[2].id,
    applicantId: userList[0].id,
    reviewerId: userList[2].id,
    amount: "8000.00",
    sealTime: new Date(now.getTime() - 20 * dayMs),
    arrivalTime: new Date(now.getTime() - 17 * dayMs),
    summary: "原已归档，后抽检发现铅封编号有误，重新处理中",
    conclusion: "重新核验中，原结论因铅封编号记录错误予以撤销",
    basis: "《档案质量抽检办法》第6条：抽检发现问题的档案必须重新核验",
    blockReason: "原归档记录中铅封编号 SEAL-D003421 与实际 SEAL-D003427 不符，数字 1 和 7 混淆，属于记录错误",
    remedyPath: "1. 重新核验实际铅封编号；2. 修正系统中错误的铅封编号记录；3. 调查编号记录错误的原因；4. 对相关责任人进行培训",
    diffFields: {
      sealNo: { before: "SEAL-D003421", after: "SEAL-D003427", label: "铅封编号" },
      sealStatus: { before: "正常完好", after: "需重新核验", label: "铅封状态" },
      conclusion: { before: "核验通过", after: "原结论撤销，重新核验", label: "核验结论" },
    },
    isArchived: false,
    createdAt: new Date(now.getTime() - 20 * dayMs),
    updatedAt: new Date(now.getTime() - 2 * dayMs),
  }).returning();

  await db.insert(nodes).values([
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.ACCEPT,
      nodeName: "受理登记",
      status: "completed",
      operatorId: userList[0].id,
      operatorName: userList[0].displayName,
      comment: "系统自动受理",
      sequence: 1,
      createdAt: new Date(now.getTime() - 20 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.PROCESS,
      nodeName: "现场核验",
      status: "completed",
      operatorId: userList[1].id,
      operatorName: userList[1].displayName,
      comment: "铅封完好，核验通过（原记录）",
      sequence: 2,
      createdAt: new Date(now.getTime() - 18 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.REVIEW,
      nodeName: "复核审批",
      status: "completed",
      operatorId: userList[2].id,
      operatorName: userList[2].displayName,
      comment: "同意正常放箱（原结论）",
      sequence: 3,
      createdAt: new Date(now.getTime() - 15 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.ARCHIVE,
      nodeName: "归档结案",
      status: "completed",
      operatorId: userList[3].id,
      operatorName: userList[3].displayName,
      comment: "已归档（原归档）",
      sequence: 4,
      createdAt: new Date(now.getTime() - 12 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.RE_PROCESS,
      nodeName: "重新处理-启动",
      status: "completed",
      operatorId: userList[3].id,
      operatorName: userList[3].displayName,
      comment: "档案抽检发现铅封编号记录错误，申请重新处理。原铅封编号 SEAL-D003421 应为 SEAL-D003427",
      basis: "《档案质量抽检办法》第6条",
      isReProcess: true,
      parentNodeId: 4,
      fieldChanges: {
        isArchived: { before: true, after: false },
        status: { before: "archived", after: "processing" },
        sealNo: { before: "SEAL-D003421", after: "SEAL-D003427（待确认）" },
      },
      snapshotBefore: {
        sealNo: "SEAL-D003421",
        status: "archived",
        conclusion: "核验通过，正常放箱",
      },
      snapshotAfter: {
        sealNo: "SEAL-D003427（待确认）",
        status: "processing",
        conclusion: "原结论撤销，重新核验",
      },
      sequence: 5,
      createdAt: new Date(now.getTime() - 3 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.PROCESS,
      nodeName: "重新核验",
      status: "completed",
      operatorId: userList[1].id,
      operatorName: userList[1].displayName,
      comment: "现场重新核验，确认实际铅封编号为 SEAL-D003427，原记录确实有误",
      isReProcess: true,
      fieldChanges: {
        sealNo: { before: "SEAL-D003421", after: "SEAL-D003427" },
      },
      sequence: 6,
      createdAt: new Date(now.getTime() - 2 * dayMs),
    },
    {
      recordId: sample4[0].id,
      nodeType: NODE_TYPES.REVIEW,
      nodeName: "重新复核",
      status: "pending",
      operatorId: userList[2].id,
      operatorName: userList[2].displayName,
      comment: "待复核确认",
      isReProcess: true,
      sequence: 7,
      createdAt: new Date(now.getTime() - 1 * dayMs),
    },
  ]);

  await db.insert(attachments).values([
    {
      recordId: sample4[0].id,
      fileName: "原铅封照片.jpg",
      fileType: "image/jpeg",
      fileSize: 1780000,
      fileUrl: "/attachments/seal-019-original.jpg",
      version: "1.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "原始核验时的铅封照片（编号记录错误）",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 18 * dayMs),
    },
    {
      recordId: sample4[0].id,
      fileName: "抽检发现说明.pdf",
      fileType: "application/pdf",
      fileSize: 189000,
      fileUrl: "/attachments/audit-report-019.pdf",
      version: "1.0",
      uploadedBy: userList[3].id,
      uploaderName: userList[3].displayName,
      description: "档案抽检发现问题的说明文档",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 3 * dayMs),
    },
    {
      recordId: sample4[0].id,
      fileName: "重新核验照片.jpg",
      fileType: "image/jpeg",
      fileSize: 2050000,
      fileUrl: "/attachments/seal-019-recheck.jpg",
      version: "2.0",
      uploadedBy: userList[1].id,
      uploaderName: userList[1].displayName,
      description: "重新核验拍摄的照片，可见编号为 SEAL-D003427",
      isEvidence: true,
      createdAt: new Date(now.getTime() - 2 * dayMs),
    },
  ]);

  await db.insert(evidenceItems).values([
    {
      recordId: sample4[0].id,
      type: "photo",
      title: "原始铅封照片",
      content: "原记录编号 SEAL-D003421，经核实为记录错误",
      status: "invalid",
      verified: true,
      verifiedBy: userList[2].id,
      verifiedAt: new Date(now.getTime() - 2 * dayMs),
      createdAt: new Date(now.getTime() - 18 * dayMs),
    },
    {
      recordId: sample4[0].id,
      type: "photo",
      title: "重新核验照片",
      content: "确认实际编号为 SEAL-D003427",
      status: "valid",
      verified: false,
      createdAt: new Date(now.getTime() - 2 * dayMs),
    },
    {
      recordId: sample4[0].id,
      type: "document",
      title: "档案抽检报告",
      content: "抽检编号：CJ-2024-03，发现铅封编号记录错误",
      status: "valid",
      verified: true,
      verifiedBy: userList[2].id,
      verifiedAt: new Date(now.getTime() - 2 * dayMs),
      createdAt: new Date(now.getTime() - 3 * dayMs),
    },
  ]);

  console.log("✅ 样本4（重新处理）创建完成");

  const moreSamples = await db.insert(records).values([
    {
      recordNo: "SEAL-2024-0002",
      containerNo: "MSKU7654321",
      sealNo: "SEAL-A001235",
      vesselName: "马士基埃德蒙顿",
      voyageNo: "V2401E",
      blNo: "MAEU202401002",
      customer: "上海振华物流有限公司",
      exceptionType: EXCEPTION_TYPES.NORMAL,
      status: STATUS.ARCHIVED,
      source: "系统自动核验",
      currentHandlerId: userList[3].id,
      applicantId: userList[0].id,
      reviewerId: userList[2].id,
      amount: "0.00",
      sealTime: new Date(now.getTime() - 11 * dayMs),
      arrivalTime: new Date(now.getTime() - 8 * dayMs),
      summary: "铅封完好，正常放箱",
      conclusion: "核验通过，准予放箱",
      basis: "铅封管理规范",
      isArchived: true,
      createdAt: new Date(now.getTime() - 11 * dayMs),
      updatedAt: new Date(now.getTime() - 4 * dayMs),
      archivedAt: new Date(now.getTime() - 4 * dayMs),
    },
    {
      recordNo: "SEAL-2024-0003",
      containerNo: "CMAU1122334",
      sealNo: "SEAL-B005679",
      vesselName: "达飞泰特斯",
      voyageNo: "FT2412W",
      blNo: "CMDU202402057",
      customer: "宁波远洋运输股份有限公司",
      exceptionType: EXCEPTION_TYPES.NORMAL,
      status: STATUS.ARCHIVED,
      source: "人工申报",
      currentHandlerId: userList[3].id,
      applicantId: userList[4].id,
      reviewerId: userList[2].id,
      amount: "0.00",
      sealTime: new Date(now.getTime() - 12 * dayMs),
      arrivalTime: new Date(now.getTime() - 9 * dayMs),
      summary: "铅封完好无损",
      conclusion: "正常放箱",
      basis: "现场核验记录",
      isArchived: true,
      createdAt: new Date(now.getTime() - 12 * dayMs),
      updatedAt: new Date(now.getTime() - 5 * dayMs),
      archivedAt: new Date(now.getTime() - 5 * dayMs),
    },
    {
      recordNo: "SEAL-2024-0030",
      containerNo: "COSCO1357924",
      sealNo: "SEAL-C009877",
      vesselName: "中远荷兰号",
      voyageNo: "COS-2408N",
      blNo: "COSU202403121",
      customer: "中远海运集装箱运输有限公司",
      exceptionType: EXCEPTION_TYPES.MISSING_RECORD,
      status: STATUS.PENDING_REVIEW,
      source: "系统比对发现",
      currentHandlerId: userList[2].id,
      applicantId: userList[0].id,
      reviewerId: userList[2].id,
      amount: "3000.00",
      sealTime: new Date(now.getTime() - 4 * dayMs),
      arrivalTime: new Date(now.getTime() - 2 * dayMs),
      summary: "补证后提交待复核",
      conclusion: "已补充材料，待复核",
      basis: "补充后的记录单",
      isArchived: false,
      createdAt: new Date(now.getTime() - 7 * dayMs),
      updatedAt: new Date(now.getTime() - 1 * dayMs),
    },
    {
      recordNo: "SEAL-2024-0050",
      containerNo: "ONE9876543",
      sealNo: "SEAL-D003422",
      vesselName: "海洋网联东京",
      voyageNo: "ONE-2405T",
      blNo: "ONEY202402090",
      customer: "东方海外货柜航运有限公司",
      exceptionType: EXCEPTION_TYPES.NORMAL,
      status: STATUS.PENDING_ACCEPT,
      source: "人工申报",
      currentHandlerId: userList[1].id,
      applicantId: userList[4].id,
      amount: "0.00",
      sealTime: new Date(now.getTime() - 1 * dayMs),
      summary: "新申报待受理",
      isArchived: false,
      createdAt: new Date(now.getTime() - 1 * dayMs),
      updatedAt: new Date(now.getTime() - 1 * dayMs),
    },
    {
      recordNo: "SEAL-2024-0051",
      containerNo: "MSKU5566778",
      sealNo: "SEAL-E002345",
      vesselName: "马士基吉隆坡",
      voyageNo: "V2403K",
      blNo: "MAEU202403045",
      customer: "深圳华南物流",
      exceptionType: EXCEPTION_TYPES.NORMAL,
      status: STATUS.PENDING_REVIEW,
      source: "系统自动核验",
      currentHandlerId: userList[2].id,
      applicantId: userList[0].id,
      amount: "0.00",
      sealTime: new Date(now.getTime() - 3 * dayMs),
      arrivalTime: new Date(now.getTime() - 2 * dayMs),
      summary: "核验完成待复核",
      conclusion: "铅封完好，待复核",
      basis: "现场照片2张",
      isArchived: false,
      createdAt: new Date(now.getTime() - 5 * dayMs),
      updatedAt: new Date(now.getTime() - 1 * dayMs),
    },
    {
      recordNo: "SEAL-2024-0052",
      containerNo: "CMAU2233445",
      sealNo: "SEAL-F005432",
      vesselName: "达飞马赛",
      voyageNo: "FT2415M",
      blNo: "CMDU202404078",
      customer: "青岛港国际物流",
      exceptionType: EXCEPTION_TYPES.ATTACHMENT_VERSION_MISMATCH,
      status: STATUS.PENDING_REVIEW,
      source: "人工申报",
      currentHandlerId: userList[2].id,
      applicantId: userList[4].id,
      amount: "6500.00",
      sealTime: new Date(now.getTime() - 6 * dayMs),
      arrivalTime: new Date(now.getTime() - 4 * dayMs),
      summary: "附件版本问题已说明，待复核",
      conclusion: "已提供版本差异说明，待复核确认",
      basis: "补充说明函",
      blockReason: "附件版本不一致",
      remedyPath: "已补充版本差异说明",
      isArchived: false,
      createdAt: new Date(now.getTime() - 8 * dayMs),
      updatedAt: new Date(now.getTime() - 1 * dayMs),
    },
  ]).returning();

  console.log("✅ 额外样本创建完成");

  console.log("\n🎉 所有种子数据创建成功！");
  console.log("📊 数据统计：");
  console.log("   - 用户：5 名");
  console.log("   - 记录：10 条");
  console.log("   - 四类样本：正常核销、记录漏填、附件版本不一致、重新处理");
}

if (process.argv[1] && process.argv[1].includes("seed")) {
  seed()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error("❌ 种子数据失败:", error);
      process.exit(1);
    });
}
