# Generated by Django 5.0.6 on 2026-06-15 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('collector', models.CharField(max_length=100, verbose_name='收藏者')),
                ('cabinet_layer', models.IntegerField(verbose_name='柜层')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='记录日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('rolled_back', '已回滚'), ('exception', '异常')], default='draft', max_length=20, verbose_name='记录状态')),
                ('tasting_notes', models.TextField(blank=True, verbose_name='品吸备注')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主记录',
                'verbose_name_plural': '主记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CigarTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='标签颜色')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
            ],
            options={
                'verbose_name': '雪茄标签',
                'verbose_name_plural': '雪茄标签',
            },
        ),
        migrations.CreateModel(
            name='HumidorCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='养护柜名称')),
                ('cabinet_code', models.CharField(max_length=50, unique=True, verbose_name='柜编号')),
                ('layers', models.IntegerField(default=5, verbose_name='总层数')),
                ('slots_per_layer', models.IntegerField(default=8, verbose_name='每层格数')),
                ('status', models.CharField(choices=[('normal', '正常运行'), ('warning', '异常告警'), ('maintenance', '维护中')], default='normal', max_length=20, verbose_name='状态')),
                ('target_temp_min', models.FloatField(default=18.0, verbose_name='目标温度下限(°C)')),
                ('target_temp_max', models.FloatField(default=22.0, verbose_name='目标温度上限(°C)')),
                ('target_humidity_min', models.FloatField(default=65.0, verbose_name='目标湿度下限(%)')),
                ('target_humidity_max', models.FloatField(default=75.0, verbose_name='目标湿度上限(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '养护柜',
                'verbose_name_plural': '养护柜',
            },
        ),
        migrations.CreateModel(
            name='CigarPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigar_name', models.CharField(max_length=100, verbose_name='雪茄名称')),
                ('cigar_code', models.CharField(max_length=50, verbose_name='雪茄编号')),
                ('from_layer', models.IntegerField(blank=True, null=True, verbose_name='起始柜层')),
                ('from_slot', models.IntegerField(blank=True, null=True, verbose_name='起始格位')),
                ('to_layer', models.IntegerField(verbose_name='目标柜层')),
                ('to_slot', models.IntegerField(verbose_name='目标格位')),
                ('position_type', models.CharField(choices=[('placed', '入柜'), ('moved', '移动'), ('rotated', '轮换'), ('removed', '取出')], default='placed', max_length=20, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cigar_positions', to='humidor.cabinetrecord', verbose_name='主记录')),
            ],
            options={
                'verbose_name': '雪茄位置历史',
                'verbose_name_plural': '雪茄位置历史',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.AddField(
            model_name='cabinetrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, to='humidor.cigartag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='HumidityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('measure_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测量时间')),
                ('sensor_position', models.CharField(blank=True, max_length=50, verbose_name='传感器位置')),
                ('is_alert', models.BooleanField(default=False, verbose_name='是否告警')),
                ('alert_type', models.CharField(blank=True, max_length=50, verbose_name='告警类型')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_details', to='humidor.cabinetrecord', verbose_name='主记录')),
            ],
            options={
                'verbose_name': '温湿度明细',
                'verbose_name_plural': '温湿度明细',
                'ordering': ['-measure_time'],
            },
        ),
        migrations.AddField(
            model_name='cabinetrecord',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humidor.humidorcabinet', verbose_name='所属养护柜'),
        ),
        migrations.CreateModel(
            name='AlertReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('temperature', '温度告警'), ('humidity', '湿度告警'), ('rotation_due', '轮换到期'), ('position_anomaly', '位置异常'), ('system', '系统提醒')], max_length=30, verbose_name='提醒类型')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('danger', '危险')], default='warning', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('resolved', '已处理')], default='unread', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humidor.cabinetrecord', verbose_name='主记录')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humidor.humidorcabinet', verbose_name='养护柜')),
            ],
            options={
                'verbose_name': '告警提醒',
                'verbose_name_plural': '告警提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RotationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_date', models.DateField(verbose_name='轮换日期')),
                ('result', models.CharField(choices=[('normal', '正常完成'), ('partial', '部分完成'), ('failed', '失败'), ('rolled_back', '已回滚')], default='normal', max_length=20, verbose_name='轮换结果')),
                ('cigar_count', models.IntegerField(default=0, verbose_name='轮换雪茄数量')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='轮换耗时(分钟)')),
                ('executor', models.CharField(blank=True, max_length=50, verbose_name='执行人')),
                ('summary', models.TextField(blank=True, verbose_name='轮换总结')),
                ('export_version', models.CharField(blank=True, max_length=50, verbose_name='导出版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_result', to='humidor.cabinetrecord', verbose_name='主记录')),
            ],
            options={
                'verbose_name': '轮换结果',
                'verbose_name_plural': '轮换结果',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cabinetrecord',
            unique_together={('batch_no', 'version')},
        ),
    ]
