# Generated by Django 5.2.15 on 2026-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原月费')),
                ('new_monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新月费')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_doctor', '待医生确认'), ('pending_family', '待家属确认'), ('pending_director', '待院长复核'), ('approved', '已生效'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='状态')),
                ('assessment_date', models.DateField(verbose_name='评估日期')),
                ('assessment_reason', models.TextField(blank=True, verbose_name='评估原因')),
                ('nurse_notes', models.TextField(blank=True, verbose_name='护士备注')),
                ('doctor_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='医生确认时间')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='医生意见')),
                ('family_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='家属确认时间')),
                ('family_agreed', models.BooleanField(blank=True, null=True, verbose_name='家属是否同意')),
                ('family_notes', models.TextField(blank=True, verbose_name='家属意见')),
                ('objection_reason', models.TextField(blank=True, verbose_name='异议原因')),
                ('director_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='院长复核时间')),
                ('director_approved', models.BooleanField(blank=True, null=True, verbose_name='院长是否批准')),
                ('director_notes', models.TextField(blank=True, verbose_name='院长意见')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '护理评估',
                'verbose_name_plural': '护理评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, verbose_name='维度描述')),
                ('max_score', models.IntegerField(default=100, verbose_name='最高分')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='权重')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估维度',
                'verbose_name_plural': '评估维度',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建评估'), ('submit', '提交审核'), ('doctor_confirm', '医生确认'), ('family_confirm', '家属确认'), ('director_approve', '院长批准'), ('director_reject', '院长退回'), ('edit', '编辑')], max_length=20, verbose_name='操作类型')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '评估历史',
                'verbose_name_plural': '评估历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='评估项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('max_score', models.IntegerField(default=10, verbose_name='最高分')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估项目',
                'verbose_name_plural': '评估项目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估得分',
                'verbose_name_plural': '评估得分',
                'ordering': ['item__order', 'item__id'],
            },
        ),
        migrations.CreateModel(
            name='NursingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '一级护理'), (2, '二级护理'), (3, '三级护理'), (4, '四级护理'), (5, '五级护理')], unique=True, verbose_name='护理等级')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('description', models.TextField(blank=True, verbose_name='等级描述')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月费标准')),
                ('services', models.TextField(blank=True, verbose_name='服务内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '护理等级',
                'verbose_name_plural': '护理等级',
                'ordering': ['level'],
            },
        ),
    ]
