# Generated by Django 5.2.15 on 2026-06-10 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_director', to=settings.AUTH_USER_MODEL, verbose_name='复核院长'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_doctor', to=settings.AUTH_USER_MODEL, verbose_name='确认医生'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.elder', verbose_name='长者'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_family', to=settings.AUTH_USER_MODEL, verbose_name='确认家属'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL, verbose_name='评估护士'),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assessments.assessment', verbose_name='评估记录'),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessmentdimension', verbose_name='所属维度'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment', verbose_name='评估记录'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessmentitem', verbose_name='评估项目'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='nursing_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.nursinglevel', verbose_name='建议护理等级'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='previous_nursing_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_previous', to='assessments.nursinglevel', verbose_name='原护理等级'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('assessment', 'item')},
        ),
    ]
