# Generated by Django 5.2.15 on 2026-06-10 12:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('nurse', '护士'), ('doctor', '医生'), ('family', '家属'), ('director', '院长')], default='nurse', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('id_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('floor', models.CharField(max_length=50, verbose_name='楼层')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('bed_number', models.CharField(max_length=10, verbose_name='床位号')),
                ('admission_date', models.DateField(verbose_name='入住日期')),
                ('medical_history', models.TextField(blank=True, verbose_name='病史')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='紧急联系电话')),
                ('current_monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当前月费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_nursing_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_elders', to='assessments.nursinglevel', verbose_name='当前护理等级')),
                ('family_members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'family'}, related_name='elders', to=settings.AUTH_USER_MODEL, verbose_name='家属成员')),
            ],
            options={
                'verbose_name': '长者',
                'verbose_name_plural': '长者',
                'ordering': ['-created_at'],
            },
        ),
    ]
