# Generated by Django 5.0.14 on 2026-06-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=50, unique=True, verbose_name='版本号')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('batch_type', models.CharField(choices=[('daily', '日批次'), ('weekly', '周批次'), ('project', '项目批次'), ('ad_hoc', '临时批次')], default='daily', max_length=20, verbose_name='批次类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('snapshot_data', models.TextField(blank=True, verbose_name='快照数据(JSON)')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '批次版本',
                'verbose_name_plural': '批次版本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(max_length=50, unique=True, verbose_name='样本编号')),
                ('well_name', models.CharField(max_length=100, verbose_name='井号')),
                ('depth_start', models.FloatField(verbose_name='起始深度(m)')),
                ('depth_end', models.FloatField(verbose_name='结束深度(m)')),
                ('total_length', models.FloatField(verbose_name='总长度(m)')),
                ('remaining_length', models.FloatField(verbose_name='剩余长度(m)')),
                ('lithology', models.CharField(blank=True, max_length=100, verbose_name='岩性')),
                ('formation', models.CharField(blank=True, max_length=100, verbose_name='地层')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待切割'), ('in_progress', '切割中'), ('completed', '已完成'), ('on_hold', '暂停'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('collected_date', models.DateField(blank=True, null=True, verbose_name='采集日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '岩心样本',
                'verbose_name_plural': '岩心样本',
                'ordering': ['-priority', 'sample_no'],
            },
        ),
        migrations.CreateModel(
            name='Cutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutter_no', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('cutter_type', models.CharField(choices=[('diamond', '金刚石切割机'), ('laser', '激光切割机'), ('band_saw', '带锯切割机')], default='diamond', max_length=30, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('available', '可用'), ('busy', '运行中'), ('maintenance', '维护中'), ('offline', '离线')], default='available', max_length=20, verbose_name='状态')),
                ('max_cut_length', models.FloatField(default=1.0, verbose_name='最大切割长度(m)')),
                ('min_cut_length', models.FloatField(default=0.01, verbose_name='最小切割长度(m)')),
                ('daily_capacity', models.FloatField(default=10.0, verbose_name='日产能(m/天)')),
                ('blade_loss_rate', models.FloatField(default=2.5, verbose_name='刀片损耗率(%)')),
                ('work_start_time', models.TimeField(default='08:00', verbose_name='工作开始时间')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='工作结束时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '切割机',
                'verbose_name_plural': '切割机',
                'ordering': ['cutter_no'],
            },
        ),
        migrations.CreateModel(
            name='CuttingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='目的代码')),
                ('name', models.CharField(max_length=100, verbose_name='切割目的')),
                ('standard_loss_rate', models.FloatField(default=3.0, verbose_name='标准损耗率(%)')),
                ('typical_length', models.FloatField(default=0.05, verbose_name='典型切片厚度(m)')),
                ('requires_quality_check', models.BooleanField(default=True, verbose_name='需要质检')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '切割目的',
                'verbose_name_plural': '切割目的',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CuttingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('scheduled', '已排程'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_cut_length', models.FloatField(verbose_name='计划切割长度(m)')),
                ('actual_cut_length', models.FloatField(blank=True, null=True, verbose_name='实际切割长度(m)')),
                ('loss_length', models.FloatField(default=0.0, verbose_name='损耗长度(m)')),
                ('slice_count', models.IntegerField(default=1, verbose_name='切片数量')),
                ('slice_thickness', models.FloatField(default=0.05, verbose_name='切片厚度(m)')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('scheduled_end_time', models.TimeField(blank=True, null=True, verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人员')),
                ('quality_checked', models.BooleanField(default=False, verbose_name='已质检')),
                ('quality_result', models.CharField(blank=True, max_length=50, verbose_name='质检结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.batchversion', verbose_name='所属批次')),
                ('core_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_tasks', to='core.coresample', verbose_name='岩心样本')),
                ('cutter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.cutter', verbose_name='切割机')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuttingpurpose', verbose_name='切割目的')),
            ],
            options={
                'verbose_name': '切割任务',
                'verbose_name_plural': '切割任务',
                'ordering': ['-scheduled_date', '-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('length_mismatch', '长度不符'), ('over_scheduled', '排程冲突'), ('high_loss', '损耗过高'), ('low_remaining', '剩余不足'), ('priority_conflict', '优先级冲突'), ('capacity_exceeded', '产能超限'), ('data_incomplete', '数据不全'), ('quality_issue', '质量问题'), ('other', '其他')], max_length=30, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '提示')], default='warning', max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='描述')),
                ('resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('core_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.coresample', verbose_name='关联岩心')),
                ('cutter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.cutter', verbose_name='关联设备')),
                ('cutting_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.cuttingtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
                'ordering': ['-severity', '-detected_at'],
            },
        ),
    ]
