# Generated by Django 5.0.14 on 2026-06-09 13:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('tax_no', models.CharField(max_length=50, unique=True, verbose_name='税号')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='银行账号')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('researcher', '课题组经办人'), ('college_admin', '学院管理员'), ('asset_staff', '资产人员'), ('finance_staff', '财务人员')], default='researcher', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='预算科目名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.budgetsubject', verbose_name='上级科目')),
            ],
            options={
                'verbose_name': '预算科目',
                'verbose_name_plural': '预算科目',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学院名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='学院代码')),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_colleges', to=settings.AUTH_USER_MODEL, verbose_name='院长')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.college'),
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='采购标题')),
                ('procurement_no', models.CharField(max_length=50, unique=True, verbose_name='采购编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='采购金额')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('equipment_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('equipment_params', models.TextField(verbose_name='设备参数要求')),
                ('purpose', models.TextField(verbose_name='采购用途')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('budget_frozen', '预算已冻结'), ('accepted', '已验收'), ('finance_review', '财务复核中'), ('reimbursed', '已核销'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('exception_reason', models.CharField(choices=[('none', '无异常'), ('budget_insufficient', '预算不足'), ('invoice_title_error', '发票抬头错误'), ('parameter_mismatch', '设备参数不符')], default='none', max_length=30, verbose_name='异常原因')),
                ('exception_note', models.TextField(blank=True, verbose_name='异常说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('budget_frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='预算冻结时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='验收时间')),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_procurements', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('budget_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budgetsubject', verbose_name='预算科目')),
            ],
            options={
                'verbose_name': '采购申请',
                'verbose_name_plural': '采购申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='发票号码')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('title', models.CharField(max_length=200, verbose_name='发票抬头')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='发票金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='税额')),
                ('verified', models.BooleanField(default=False, verbose_name='是否复核通过')),
                ('verification_note', models.TextField(blank=True, verbose_name='复核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finance_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL, verbose_name='复核人员')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.procurement', verbose_name='采购申请')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
            },
        ),
        migrations.CreateModel(
            name='HistoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('budget_frozen', '预算已冻结'), ('accepted', '已验收'), ('finance_review', '财务复核中'), ('reimbursed', '已核销'), ('rejected', '已驳回')], max_length=20, verbose_name='状态')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_nodes', to='core.procurement', verbose_name='采购申请')),
            ],
            options={
                'verbose_name': '历史节点',
                'verbose_name_plural': '历史节点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateField(verbose_name='验收日期')),
                ('actual_params', models.TextField(verbose_name='实际设备参数')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('remarks', models.TextField(blank=True, verbose_name='验收备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to=settings.AUTH_USER_MODEL, verbose_name='验收人员')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='core.procurement', verbose_name='采购申请')),
            ],
            options={
                'verbose_name': '设备验收',
                'verbose_name_plural': '设备验收',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课题名称')),
                ('project_no', models.CharField(max_length=50, unique=True, verbose_name='课题编号')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总预算')),
                ('description', models.TextField(blank=True, verbose_name='课题描述')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.college', verbose_name='所属学院')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='课题负责人')),
            ],
            options={
                'verbose_name': '课题',
                'verbose_name_plural': '课题',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='procurement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='core.researchproject', verbose_name='所属课题'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='core.supplier', verbose_name='供应商'),
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='计划金额')),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='已冻结金额')),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='已使用金额')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budgetsubject', verbose_name='预算科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.researchproject', verbose_name='课题')),
            ],
            options={
                'verbose_name': '课题预算',
                'verbose_name_plural': '课题预算',
                'unique_together': {('project', 'subject')},
            },
        ),
    ]
