# Generated by Django 5.2.15 on 2026-06-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('target_text', models.TextField()),
                ('difficulty', models.PositiveIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '大师')], default=1)),
                ('time_limit', models.PositiveIntegerField(default=120)),
                ('ink_budget', models.PositiveIntegerField(default=100)),
                ('pass_score', models.PositiveIntegerField(default=60)),
                ('error_penalty', models.PositiveIntegerField(default=5)),
                ('inverted_penalty', models.PositiveIntegerField(default=8)),
                ('ink_waste_penalty', models.PositiveIntegerField(default=2)),
                ('base_reward', models.PositiveIntegerField(default=100)),
                ('char_pool', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('total_revenue', models.IntegerField(default=0)),
                ('total_rounds', models.PositiveIntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('failed', '已失败'), ('abandoned', '已放弃')], default='in_progress', max_length=20)),
                ('arranged_text', models.TextField(default='')),
                ('ink_used', models.PositiveIntegerField(default=0)),
                ('proofread_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='workshop.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='workshop.player')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('wrong_char_count', models.PositiveIntegerField(default=0)),
                ('inverted_char_count', models.PositiveIntegerField(default=0)),
                ('missing_char_count', models.PositiveIntegerField(default=0)),
                ('extra_char_count', models.PositiveIntegerField(default=0)),
                ('ink_efficiency', models.FloatField(default=0.0)),
                ('ink_waste', models.PositiveIntegerField(default=0)),
                ('time_bonus', models.FloatField(default=0.0)),
                ('proofread_bonus', models.FloatField(default=0.0)),
                ('raw_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('revenue', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('server_calculated', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='workshop.round')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('pick_char', '取字'), ('place_char', '放字'), ('swap_char', '换字'), ('remove_char', '删字'), ('adjust_ink', '调墨'), ('proofread', '校对'), ('flip_char', '翻字')], max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('char_value', models.CharField(blank=True, max_length=4)),
                ('old_char', models.CharField(blank=True, max_length=4)),
                ('ink_delta', models.IntegerField(default=0)),
                ('data_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='workshop.round')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
