// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealManagementSystem.Data;

#nullable disable

namespace SealManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611093943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SealManagementSystem.Models.ApprovalNode", b =>
                {
                    b.Property<int>("ApprovalNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalNodeId"));

                    b.Property<int>("BorrowRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("ApprovalNodeId");

                    b.HasIndex("BorrowRequestId");

                    b.HasIndex("OperatorId");

                    b.ToTable("ApprovalNodes");

                    b.HasData(
                        new
                        {
                            ApprovalNodeId = 1,
                            BorrowRequestId = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 1,
                            OperatorId = 1,
                            ProcessedAt = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 2,
                            BorrowRequestId = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 2,
                            OperatorId = 5,
                            ProcessedAt = new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "合同审核通过，条款完整合规",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 3,
                            BorrowRequestId = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 3,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 3, 18, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章已交接，签收人：张三",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 4,
                            BorrowRequestId = 1,
                            CreatedAt = new DateTime(2024, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 4,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章完好归还，归还人：张三",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 5,
                            BorrowRequestId = 1,
                            CreatedAt = new DateTime(2024, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 5,
                            OperatorId = 7,
                            ProcessedAt = new DateTime(2024, 3, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "归还核验通过，无异常",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 6,
                            BorrowRequestId = 2,
                            CreatedAt = new DateTime(2024, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 1,
                            OperatorId = 3,
                            ProcessedAt = new DateTime(2024, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 7,
                            BorrowRequestId = 2,
                            CreatedAt = new DateTime(2024, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 2,
                            OperatorId = 5,
                            ProcessedAt = new DateTime(2024, 4, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "合同文件缺失，无法审核，请上传完整合同后重新申请",
                            Result = 2
                        },
                        new
                        {
                            ApprovalNodeId = 8,
                            BorrowRequestId = 3,
                            CreatedAt = new DateTime(2024, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 1,
                            OperatorId = 4,
                            ProcessedAt = new DateTime(2024, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 9,
                            BorrowRequestId = 3,
                            CreatedAt = new DateTime(2024, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 2,
                            OperatorId = 5,
                            ProcessedAt = new DateTime(2024, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "合同审核通过",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 10,
                            BorrowRequestId = 3,
                            CreatedAt = new DateTime(2024, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 3,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 5, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章已交接，签收人：赵六",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 11,
                            BorrowRequestId = 3,
                            CreatedAt = new DateTime(2024, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 4,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章归还，已超期12天",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 12,
                            BorrowRequestId = 3,
                            CreatedAt = new DateTime(2024, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 5,
                            OperatorId = 7,
                            ProcessedAt = new DateTime(2024, 5, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "超期归还已记录，申请人需书面说明原因，已纳入信用档案",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 13,
                            BorrowRequestId = 4,
                            CreatedAt = new DateTime(2024, 6, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 1,
                            OperatorId = 1,
                            ProcessedAt = new DateTime(2024, 6, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 14,
                            BorrowRequestId = 4,
                            CreatedAt = new DateTime(2024, 6, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 2,
                            OperatorId = 5,
                            ProcessedAt = new DateTime(2024, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "合同审核通过",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 15,
                            BorrowRequestId = 4,
                            CreatedAt = new DateTime(2024, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 3,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 6, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章已交接，签收人：张三",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 16,
                            BorrowRequestId = 4,
                            CreatedAt = new DateTime(2024, 6, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 4,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 6, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "印章归还，归还人报告盖章文件：合同正本1份、补充协议2份、授权委托书1份",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 17,
                            BorrowRequestId = 4,
                            CreatedAt = new DateTime(2024, 6, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 5,
                            OperatorId = 7,
                            ProcessedAt = new DateTime(2024, 6, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "复核发现用印范围不符：申请为合同正本1份，实际加盖补充协议2份和授权委托书1份。已要求补充审批并通报批评。",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 18,
                            BorrowRequestId = 5,
                            CreatedAt = new DateTime(2024, 6, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 1,
                            OperatorId = 3,
                            ProcessedAt = new DateTime(2024, 6, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 19,
                            BorrowRequestId = 5,
                            CreatedAt = new DateTime(2024, 6, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 2,
                            OperatorId = 5,
                            ProcessedAt = new DateTime(2024, 6, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "合同审核通过",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 20,
                            BorrowRequestId = 5,
                            CreatedAt = new DateTime(2024, 6, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NodeType = 3,
                            OperatorId = 6,
                            ProcessedAt = new DateTime(2024, 6, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Remark = "财务专用章已交接，签收人：王五",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 21,
                            BorrowRequestId = 6,
                            CreatedAt = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Local),
                            NodeType = 1,
                            OperatorId = 2,
                            ProcessedAt = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Local),
                            Remark = "提交印章外借申请",
                            Result = 1
                        },
                        new
                        {
                            ApprovalNodeId = 22,
                            BorrowRequestId = 6,
                            CreatedAt = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Local),
                            NodeType = 2,
                            Result = 0
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.BorrowRequest", b =>
                {
                    b.Property<int>("BorrowRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowRequestId"));

                    b.Property<DateTime?>("ActualBorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ExceptionReason")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedBorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RiskReviewRemark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SealId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BorrowRequestId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ContractId");

                    b.HasIndex("SealId");

                    b.ToTable("BorrowRequests");

                    b.HasData(
                        new
                        {
                            BorrowRequestId = 1,
                            ActualBorrowDate = new DateTime(2024, 3, 18, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ActualReturnDate = new DateTime(2024, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicantId = 1,
                            ContractId = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExceptionReason = 0,
                            PlannedBorrowDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestCode = "BR-2024-001",
                            SealId = 2,
                            Status = 7,
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageScope = "XX科技软件采购合同第3、5、7、9页签字盖章处盖章，共4处"
                        },
                        new
                        {
                            BorrowRequestId = 2,
                            ApplicantId = 3,
                            ContractId = 3,
                            CreatedAt = new DateTime(2024, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ExceptionDescription = "法务审核发现合同文件缺失，无法确认合同内容，驳回申请",
                            ExceptionReason = 1,
                            PlannedBorrowDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestCode = "BR-2024-002",
                            SealId = 2,
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 4, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageScope = "ZZ物流运输服务合同盖章"
                        },
                        new
                        {
                            BorrowRequestId = 3,
                            ActualBorrowDate = new DateTime(2024, 5, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualReturnDate = new DateTime(2024, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicantId = 4,
                            ContractId = 4,
                            CreatedAt = new DateTime(2024, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExceptionDescription = "实际归还日期2024-05-20，超过计划归还日期2024-05-08共12天",
                            ExceptionReason = 2,
                            PlannedBorrowDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestCode = "BR-2024-003",
                            SealId = 1,
                            Status = 8,
                            UpdatedAt = new DateTime(2024, 5, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageScope = "AA咨询管理咨询服务合同盖章"
                        },
                        new
                        {
                            BorrowRequestId = 4,
                            ActualBorrowDate = new DateTime(2024, 6, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualReturnDate = new DateTime(2024, 6, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicantId = 1,
                            ContractId = 5,
                            CreatedAt = new DateTime(2024, 6, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ExceptionDescription = "风控复核发现申请人除合同正本外，还在2份补充协议和1份授权委托书上盖章，超出申请的用印范围",
                            ExceptionReason = 3,
                            PlannedBorrowDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestCode = "BR-2024-004",
                            RiskReviewRemark = "超出范围盖章文件已报备，需补充审批流程，警告申请人",
                            SealId = 1,
                            Status = 8,
                            UpdatedAt = new DateTime(2024, 6, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageScope = "BB设备办公设备采购合同正文及附件盖章，仅合同正本1份"
                        },
                        new
                        {
                            BorrowRequestId = 5,
                            ActualBorrowDate = new DateTime(2024, 6, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ApplicantId = 3,
                            ContractId = 6,
                            CreatedAt = new DateTime(2024, 6, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ExceptionReason = 0,
                            PlannedBorrowDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestCode = "BR-2024-005",
                            SealId = 3,
                            Status = 5,
                            UpdatedAt = new DateTime(2024, 6, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageScope = "CC云服务云平台服务合同盖章，共2份正本"
                        },
                        new
                        {
                            BorrowRequestId = 6,
                            ApplicantId = 2,
                            ContractId = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Local),
                            ExceptionReason = 0,
                            PlannedBorrowDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            PlannedReturnDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            RequestCode = "BR-2024-006",
                            SealId = 2,
                            Status = 1,
                            UsageScope = "YY地产办公场地租赁合同补充条款盖章"
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContractAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContractParty")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContractSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ApplicantId = 1,
                            ContractAmount = 280000m,
                            ContractCode = "HT-2024-001",
                            ContractName = "XX科技软件采购合同",
                            ContractParty = "XX科技有限公司",
                            ContractSummary = "ERP系统软件采购及实施服务合同",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SignedDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            ContractId = 2,
                            ApplicantId = 2,
                            ContractAmount = 960000m,
                            ContractCode = "HT-2024-002",
                            ContractName = "YY地产办公场地租赁合同",
                            ContractParty = "YY地产集团",
                            ContractSummary = "总部办公楼三年期租赁合同",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(2027, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SignedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4
                        },
                        new
                        {
                            ContractId = 3,
                            ApplicantId = 3,
                            ContractAmount = 450000m,
                            ContractCode = "HT-2024-003",
                            ContractName = "ZZ物流运输服务合同",
                            ContractParty = "ZZ物流股份有限公司",
                            ContractSummary = "年度货物运输服务框架协议",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5
                        },
                        new
                        {
                            ContractId = 4,
                            ApplicantId = 4,
                            ContractAmount = 180000m,
                            ContractCode = "HT-2024-004",
                            ContractName = "AA咨询管理咨询服务合同",
                            ContractParty = "AA管理咨询公司",
                            ContractSummary = "企业管理咨询及流程优化服务",
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SignedDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            ContractId = 5,
                            ApplicantId = 1,
                            ContractAmount = 120000m,
                            ContractCode = "HT-2024-005",
                            ContractName = "BB设备办公设备采购合同",
                            ContractParty = "BB办公设备有限公司",
                            ContractSummary = "办公电脑及打印设备采购",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SignedDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            ContractId = 6,
                            ApplicantId = 3,
                            ContractAmount = 360000m,
                            ContractCode = "HT-2024-006",
                            ContractName = "CC云服务云平台服务合同",
                            ContractParty = "CC云计算科技有限公司",
                            ContractSummary = "年度云服务器及云存储服务",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SignedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "综合管理部",
                            Description = "行政办公综合管理"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "法务部",
                            Description = "合同审核与法律事务"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "风控部",
                            Description = "风险控制与合规审查"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "市场部",
                            Description = "市场拓展与销售"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "财务部",
                            Description = "财务管理与核算"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "技术部",
                            Description = "技术研发与产品"
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.Seal", b =>
                {
                    b.Property<int>("SealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SealId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SealCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SealType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SealId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Seals");

                    b.HasData(
                        new
                        {
                            SealId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "公司法人公章",
                            SealCode = "SEAL-001",
                            SealName = "公司公章",
                            SealType = 1,
                            Status = 1
                        },
                        new
                        {
                            SealId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "用于合同签署",
                            SealCode = "SEAL-002",
                            SealName = "合同专用章",
                            SealType = 2,
                            Status = 1
                        },
                        new
                        {
                            SealId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Description = "用于财务票据",
                            SealCode = "SEAL-003",
                            SealName = "财务专用章",
                            SealType = 3,
                            Status = 1
                        },
                        new
                        {
                            SealId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "法定代表人签章",
                            SealCode = "SEAL-004",
                            SealName = "法人名章",
                            SealType = 4,
                            Status = 1
                        },
                        new
                        {
                            SealId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Description = "用于发票盖章",
                            SealCode = "SEAL-005",
                            SealName = "发票专用章",
                            SealType = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DepartmentId = 4,
                            EmployeeId = "EMP001",
                            Phone = "13800000001",
                            Role = 1,
                            UserName = "张三"
                        },
                        new
                        {
                            UserId = 2,
                            DepartmentId = 5,
                            EmployeeId = "EMP002",
                            Phone = "13800000002",
                            Role = 1,
                            UserName = "李四"
                        },
                        new
                        {
                            UserId = 3,
                            DepartmentId = 6,
                            EmployeeId = "EMP003",
                            Phone = "13800000003",
                            Role = 1,
                            UserName = "王五"
                        },
                        new
                        {
                            UserId = 4,
                            DepartmentId = 4,
                            EmployeeId = "EMP004",
                            Phone = "13800000004",
                            Role = 1,
                            UserName = "赵六"
                        },
                        new
                        {
                            UserId = 5,
                            DepartmentId = 2,
                            EmployeeId = "EMP005",
                            Phone = "13800000005",
                            Role = 2,
                            UserName = "陈法务"
                        },
                        new
                        {
                            UserId = 6,
                            DepartmentId = 1,
                            EmployeeId = "EMP006",
                            Phone = "13800000006",
                            Role = 3,
                            UserName = "刘行政"
                        },
                        new
                        {
                            UserId = 7,
                            DepartmentId = 3,
                            EmployeeId = "EMP007",
                            Phone = "13800000007",
                            Role = 4,
                            UserName = "孙风控"
                        });
                });

            modelBuilder.Entity("SealManagementSystem.Models.ApprovalNode", b =>
                {
                    b.HasOne("SealManagementSystem.Models.BorrowRequest", "BorrowRequest")
                        .WithMany("ApprovalNodes")
                        .HasForeignKey("BorrowRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealManagementSystem.Models.User", "Operator")
                        .WithMany("ApprovalNodes")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BorrowRequest");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("SealManagementSystem.Models.BorrowRequest", b =>
                {
                    b.HasOne("SealManagementSystem.Models.User", "Applicant")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SealManagementSystem.Models.Contract", "Contract")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SealManagementSystem.Models.Seal", "Seal")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("SealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Contract");

                    b.Navigation("Seal");
                });

            modelBuilder.Entity("SealManagementSystem.Models.Contract", b =>
                {
                    b.HasOne("SealManagementSystem.Models.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SealManagementSystem.Models.Seal", b =>
                {
                    b.HasOne("SealManagementSystem.Models.Department", "Department")
                        .WithMany("Seals")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SealManagementSystem.Models.User", b =>
                {
                    b.HasOne("SealManagementSystem.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SealManagementSystem.Models.BorrowRequest", b =>
                {
                    b.Navigation("ApprovalNodes");
                });

            modelBuilder.Entity("SealManagementSystem.Models.Contract", b =>
                {
                    b.Navigation("BorrowRequests");
                });

            modelBuilder.Entity("SealManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Seals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SealManagementSystem.Models.Seal", b =>
                {
                    b.Navigation("BorrowRequests");
                });

            modelBuilder.Entity("SealManagementSystem.Models.User", b =>
                {
                    b.Navigation("ApprovalNodes");

                    b.Navigation("BorrowRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
