server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_maintenance
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

logging:
  level:
    com.hotel.maintenance: DEBUG
