# Generated by Django 5.1 on 2026-06-04 15:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='异常编码')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='异常名称')),
                ('description', models.TextField(blank=True, verbose_name='异常描述')),
                ('block_adjustment', models.BooleanField(default=False, verbose_name='是否阻断费用调整')),
                ('check_fields', models.TextField(blank=True, help_text='多个字段用逗号分隔', verbose_name='需核对字段')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '异常类型',
                'verbose_name_plural': '异常类型',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('reader', '抄表员'), ('reviewer', '复核员'), ('admin', '管理员')], default='reader', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='片区名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='片区编码')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'reader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='片区负责人')),
            ],
            options={
                'verbose_name': '片区',
                'verbose_name_plural': '片区',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.CharField(max_length=50, unique=True, verbose_name='用户编号')),
                ('name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='用户地址')),
                ('meter_no', models.CharField(max_length=50, unique=True, verbose_name='水表编号')),
                ('water_price', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='水价(元/吨)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在用')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter_review.district', verbose_name='所属片区')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['customer_no'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='抄表日期')),
                ('last_reading', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='上期读数')),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='本期读数')),
                ('adjusted_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后读数')),
                ('usage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='用水量(吨)')),
                ('adjusted_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后用水量(吨)')),
                ('original_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='原始费用(元)')),
                ('adjusted_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后费用(元)')),
                ('anomaly_detail', models.TextField(blank=True, verbose_name='异常说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('reading', '抄表员处理中'), ('reviewing', '复核员处理中'), ('adjusted', '已调整'), ('returned', '已退回'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('rework_count', models.IntegerField(default=0, verbose_name='返工次数')),
                ('adjustment_basis', models.TextField(blank=True, verbose_name='调整依据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('anomaly_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter_review.anomalytype', verbose_name='异常类型')),
                ('assigned_reader', models.ForeignKey(blank=True, limit_choices_to={'role': 'reader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_readings', to=settings.AUTH_USER_MODEL, verbose_name='指派抄表员')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_readings', to=settings.AUTH_USER_MODEL, verbose_name='当前责任人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter_review.customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '抄表记录',
                'verbose_name_plural': '抄表记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('reading', '抄表员处理中'), ('reviewing', '复核员处理中'), ('adjusted', '已调整'), ('returned', '已退回'), ('archived', '已归档')], max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(choices=[('pending', '待处理'), ('reading', '抄表员处理中'), ('reviewing', '复核员处理中'), ('adjusted', '已调整'), ('returned', '已退回'), ('archived', '已归档')], max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_owner_logs', to=settings.AUTH_USER_MODEL, verbose_name='新责任人')),
                ('old_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_owner_logs', to=settings.AUTH_USER_MODEL, verbose_name='原责任人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='meter_review.meterreading', verbose_name='抄表记录')),
            ],
            options={
                'verbose_name': '历史变更',
                'verbose_name_plural': '历史变更',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='现场说明')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='field_photos/', verbose_name='现场照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('reader', models.ForeignKey(limit_choices_to={'role': 'reader'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='抄表员')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_notes', to='meter_review.meterreading', verbose_name='抄表记录')),
            ],
            options={
                'verbose_name': '现场说明',
                'verbose_name_plural': '现场说明',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('adjust', '调整'), ('return', '退回'), ('archive', '归档')], max_length=20, verbose_name='处理动作')),
                ('old_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='原读数')),
                ('new_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='新读数')),
                ('old_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='原费用(元)')),
                ('new_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='新费用(元)')),
                ('adjustment_reason', models.TextField(verbose_name='调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='复核员')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='meter_review.meterreading', verbose_name='抄表记录')),
            ],
            options={
                'verbose_name': '费用调整',
                'verbose_name_plural': '费用调整',
                'ordering': ['-created_at'],
            },
        ),
    ]
