# Generated by Django 5.0.14 on 2026-06-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.CharField(choices=[('research', '学术研究'), ('study', '学习参考'), ('teaching', '教学使用'), ('exhibition', '展览展示'), ('other', '其他')], default='research', max_length=20, verbose_name='阅览目的')),
                ('purpose_detail', models.TextField(blank=True, verbose_name='目的说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('checked_out', '已调出'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('qualification_checked', models.BooleanField(default=False, verbose_name='资格已核验')),
                ('qualification_notes', models.TextField(blank=True, verbose_name='资格核验说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.rarebook', verbose_name='珍本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约申请',
                'verbose_name_plural': '预约申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
