// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources/workers-by-team": {
    params: {};
  };
  "/resources/check-area-conflict": {
    params: {};
  };
  "/permits": {
    params: {};
  };
  "/permits/new": {
    params: {};
  };
  "/permits/:id": {
    params: {
      "id": string;
    };
  };
  "/statistics": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources/workers-by-team" | "/resources/check-area-conflict" | "/permits" | "/permits/new" | "/permits/:id" | "/statistics";
  };
  "routes/resources.workers-by-team.ts": {
    id: "routes/resources.workers-by-team";
    page: "/resources/workers-by-team";
  };
  "routes/resources.check-area-conflict.ts": {
    id: "routes/resources.check-area-conflict";
    page: "/resources/check-area-conflict";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/permits" | "/permits/new" | "/permits/:id" | "/statistics";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/permits.tsx": {
    id: "routes/permits";
    page: "/permits" | "/permits/new" | "/permits/:id";
  };
  "routes/permits._index.tsx": {
    id: "routes/permits._index";
    page: "/permits";
  };
  "routes/permits.new.tsx": {
    id: "routes/permits.new";
    page: "/permits/new";
  };
  "routes/permits.$id.tsx": {
    id: "routes/permits.$id";
    page: "/permits/:id";
  };
  "routes/statistics.tsx": {
    id: "routes/statistics";
    page: "/statistics";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/resources.workers-by-team": typeof import("./app/routes/resources.workers-by-team.ts");
  "routes/resources.check-area-conflict": typeof import("./app/routes/resources.check-area-conflict.ts");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/permits": typeof import("./app/routes/permits.tsx");
  "routes/permits._index": typeof import("./app/routes/permits._index.tsx");
  "routes/permits.new": typeof import("./app/routes/permits.new.tsx");
  "routes/permits.$id": typeof import("./app/routes/permits.$id.tsx");
  "routes/statistics": typeof import("./app/routes/statistics.tsx");
};