# Generated by Django 5.2.15 on 2026-06-09 11:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='航空公司名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='航司代码')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo')),
            ],
            options={
                'verbose_name': '航空公司',
                'verbose_name_plural': '航空公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='过敏源名称')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '过敏源',
                'verbose_name_plural': '过敏源',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='餐食类别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '餐食类别',
                'verbose_name_plural': '餐食类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('catering_clerk', '配餐经办人'), ('qc_officer', '品控员'), ('cabin_crew', '机供人员'), ('duty_manager', '值班经理')], default='catering_clerk', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='航班号')),
                ('departure', models.CharField(max_length=50, verbose_name='出发地')),
                ('destination', models.CharField(max_length=50, verbose_name='目的地')),
                ('departure_time', models.DateTimeField(verbose_name='计划起飞时间')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='机型')),
                ('passenger_count', models.IntegerField(default=0, verbose_name='载客量')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='catering.airline', verbose_name='航空公司')),
            ],
            options={
                'verbose_name': '航班',
                'verbose_name_plural': '航班',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='MealBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('quantity', models.IntegerField(verbose_name='数量（份）')),
                ('production_time', models.DateTimeField(verbose_name='生产时间')),
                ('shelf_life_hours', models.IntegerField(default=24, verbose_name='保质期（小时）')),
                ('allergen_label_verified', models.BooleanField(default=False, verbose_name='过敏源标识已复核')),
                ('allergen_label_missing', models.BooleanField(default=False, verbose_name='过敏源标识缺失')),
                ('status', models.CharField(choices=[('created', '已创建'), ('produced', '生产完成'), ('in_cold_storage', '冷藏中'), ('qc_pending', '待品控复核'), ('qc_passed', '品控通过'), ('qc_failed', '品控不通过'), ('loading', '装机中'), ('loaded', '已装机'), ('returned', '已退回'), ('recalled', '已召回'), ('consumed', '已食用')], default='created', max_length=20, verbose_name='状态')),
                ('anomaly_type', models.CharField(choices=[('none', '无异常'), ('allergen_missing', '过敏源标识缺失'), ('cold_storage_timeout', '冷藏超时'), ('flight_meal_change', '航班临时换餐'), ('temperature_abnormal', '温度异常'), ('label_damaged', '标签损坏'), ('other', '其他异常')], default='none', max_length=30, verbose_name='异常类型')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('qc_time', models.DateTimeField(blank=True, null=True, verbose_name='品控时间')),
                ('load_time', models.DateTimeField(blank=True, null=True, verbose_name='装机时间')),
                ('cold_storage_start', models.DateTimeField(blank=True, null=True, verbose_name='冷藏开始时间')),
                ('cold_storage_end', models.DateTimeField(blank=True, null=True, verbose_name='冷藏结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allergens', models.ManyToManyField(blank=True, related_name='batches', to='catering.allergen', verbose_name='所含过敏源')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_batches', to='catering.flight', verbose_name='航班')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_batches', to=settings.AUTH_USER_MODEL, verbose_name='装机人')),
                ('qc_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_batches', to=settings.AUTH_USER_MODEL, verbose_name='品控员')),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catering.mealcategory', verbose_name='餐食类别')),
            ],
            options={
                'verbose_name': '餐食批次',
                'verbose_name_plural': '餐食批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='catering.mealbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '批次历史',
                'verbose_name_plural': '批次历史',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='召回原因')),
                ('anomaly_type', models.CharField(choices=[('none', '无异常'), ('allergen_missing', '过敏源标识缺失'), ('cold_storage_timeout', '冷藏超时'), ('flight_meal_change', '航班临时换餐'), ('temperature_abnormal', '温度异常'), ('label_damaged', '标签损坏'), ('other', '其他异常')], max_length=30, verbose_name='异常类型')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否解决')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='catering.mealbatch', verbose_name='批次')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_recalls', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_recalls', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '召回记录',
                'verbose_name_plural': '召回记录',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度（℃）')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录位置')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_records', to='catering.mealbatch', verbose_name='批次')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '温度记录',
                'verbose_name_plural': '温度记录',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
