# Generated by Django 5.1.15 on 2026-06-17 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystallizationPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_code', models.CharField(max_length=20, unique=True, verbose_name='池号')),
                ('pool_name', models.CharField(blank=True, max_length=50, verbose_name='池名')),
                ('pool_group', models.CharField(choices=[('A', 'A组'), ('B', 'B组'), ('C', 'C组'), ('D', 'D组')], default='A', max_length=2, verbose_name='池组')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='面积(亩)')),
                ('position_x', models.FloatField(default=0.0, verbose_name='地图X坐标')),
                ('position_y', models.FloatField(default=0.0, verbose_name='地图Y坐标')),
                ('status', models.CharField(choices=[('active', '生产中'), ('idle', '闲置'), ('maintenance', '维护中'), ('repair', '抢修中')], default='active', max_length=20, verbose_name='状态')),
                ('build_date', models.DateField(blank=True, null=True, verbose_name='建成日期')),
                ('depth_cm', models.DecimalField(decimal_places=1, default=30, max_digits=5, verbose_name='池深(cm)')),
                ('remarks', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '结晶池',
                'verbose_name_plural': '结晶池',
                'db_table': 'crystallization_pool',
                'ordering': ['pool_code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='巡检日期')),
                ('inspection_time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='巡检时间')),
                ('inspector', models.CharField(default='系统', max_length=50, verbose_name='巡检员')),
                ('batch_no', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='批次号')),
                ('brine_concentration', models.DecimalField(decimal_places=2, help_text='波美度，正常25-30', max_digits=5, verbose_name='卤水浓度(°Bé)')),
                ('brine_depth_cm', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='卤水深度(cm)')),
                ('crystal_thickness_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='结晶层厚度(mm)')),
                ('surface_status', models.CharField(choices=[('normal', '正常'), ('leaking', '渗漏'), ('cracked', '开裂'), ('flooded', '积水'), ('dirty', '污染'), ('crystallized', '结晶完好')], default='normal', max_length=20, verbose_name='池面状态')),
                ('surface_photo', models.ImageField(blank=True, null=True, upload_to='inspection/', verbose_name='池面照片')),
                ('weather_type', models.CharField(choices=[('sunny', '晴'), ('cloudy', '多云'), ('overcast', '阴'), ('rainy', '雨'), ('storm', '暴雨'), ('foggy', '雾')], default='sunny', max_length=20, verbose_name='天气')),
                ('temperature', models.DecimalField(decimal_places=1, default=25.0, max_digits=4, verbose_name='气温(℃)')),
                ('humidity', models.DecimalField(decimal_places=1, default=60.0, max_digits=5, verbose_name='湿度(%)')),
                ('wind_level', models.CharField(choices=[('0', '无风'), ('1-2', '1-2级'), ('3-4', '3-4级'), ('5-6', '5-6级'), ('7+', '7级以上')], default='3-4', max_length=10, verbose_name='风力')),
                ('wind_direction', models.CharField(blank=True, max_length=10, verbose_name='风向')),
                ('salt_yield', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='本次收盐量(吨)')),
                ('cumulative_yield', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='累计产量(吨)')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH值')),
                ('impurity_level', models.CharField(blank=True, choices=[('excellent', '优级'), ('good', '一级'), ('normal', '二级'), ('poor', '等外')], max_length=20, verbose_name='杂质等级')),
                ('has_anomaly', models.BooleanField(default=False, verbose_name='存在异常')),
                ('anomaly_description', models.TextField(blank=True, max_length=1000, verbose_name='异常描述')),
                ('handling_measures', models.TextField(blank=True, max_length=1000, verbose_name='处理措施')),
                ('remarks', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否最新版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspection.crystallizationpool', verbose_name='结晶池')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_record',
                'ordering': ['-inspection_date', '-inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('concentration', '浓度异常'), ('surface', '池面异常'), ('weather', '天气异常'), ('yield', '产量异常'), ('equipment', '设备异常'), ('other', '其他')], default='other', max_length=30, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='异常标题')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('ignored', '忽略')], default='open', max_length=20, verbose_name='处理状态')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发现时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='处理人')),
                ('resolution', models.TextField(blank=True, max_length=2000, verbose_name='解决方案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inspection.crystallizationpool', verbose_name='结晶池')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inspection.inspectionrecord', verbose_name='关联巡检')),
            ],
            options={
                'verbose_name': '异常告警',
                'verbose_name_plural': '异常告警',
                'db_table': 'anomaly_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.IntegerField(verbose_name='版本号')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('revise', '修正'), ('revert', '回滚')], default='update', max_length=20, verbose_name='操作类型')),
                ('change_summary', models.TextField(blank=True, max_length=1000, verbose_name='变更摘要')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='数据快照')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inspection.inspectionrecord', verbose_name='巡检记录')),
            ],
            options={
                'verbose_name': '版本历史',
                'verbose_name_plural': '版本历史',
                'db_table': 'record_version',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['pool', 'inspection_date'], name='inspection__pool_id_3746de_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['batch_no'], name='inspection__batch_n_74f436_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['has_anomaly'], name='inspection__has_ano_5f041f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordversion',
            unique_together={('record', 'version_no')},
        ),
    ]
