# Generated by Django 6.0.6 on 2026-06-05 09:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_number', models.CharField(max_length=50, unique=True, verbose_name='灯杆编号')),
                ('area', models.CharField(max_length=100, verbose_name='片区')),
                ('address', models.CharField(max_length=255, verbose_name='位置地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备编号')),
                ('rated_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='额定功率(W)')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '灯杆',
                'verbose_name_plural': '灯杆',
                'ordering': ['pole_number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('inspector', '巡检员'), ('reviewer', '能耗复核人'), ('admin', '管理员')], default='inspector', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='读数日期')),
                ('daily_energy', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='日耗电量(kWh)')),
                ('cumulative_energy', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='累计电量(kWh)')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='是否异常')),
                ('anomaly_type', models.CharField(blank=True, max_length=50, verbose_name='异常类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('light_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='inspection.lightpole', verbose_name='灯杆')),
            ],
            options={
                'verbose_name': '能耗读数',
                'verbose_name_plural': '能耗读数',
                'ordering': ['-reading_date'],
                'unique_together': {('light_pole', 'reading_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('fault_source', models.CharField(choices=[('automatic', '系统自动检测'), ('manual', '人工上报'), ('patrol', '巡检发现'), ('citizen', '市民投诉')], max_length=20, verbose_name='故障来源')),
                ('fault_type', models.CharField(choices=[('normal_repair', '正常修复'), ('energy_spike', '能耗突增'), ('location_error', '位置编号错误'), ('duplicate', '重复派单'), ('bulb_damage', '灯泡损坏'), ('circuit_fault', '电路故障'), ('control_issue', '控制问题'), ('other', '其他')], max_length=30, verbose_name='故障类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('assigned', '已派单'), ('in_progress', '处理中'), ('inspected', '待复核'), ('reviewing', '复核中'), ('returned', '已退回'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('expected_energy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预期能耗(kWh)')),
                ('actual_energy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际能耗(kWh)')),
                ('repair_description', models.TextField(blank=True, verbose_name='修复说明')),
                ('anomaly_cause', models.TextField(blank=True, verbose_name='异常原因')),
                ('review_comment', models.TextField(blank=True, verbose_name='复核意见')),
                ('rework_count', models.IntegerField(default=0, verbose_name='返工次数')),
                ('is_location_error', models.BooleanField(default=False, verbose_name='位置编号错误')),
                ('location_error_note', models.TextField(blank=True, verbose_name='位置错误说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='巡检完成时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核完成时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('energy_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.energyreading', verbose_name='关联能耗读数')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_orders', to=settings.AUTH_USER_MODEL, verbose_name='巡检员')),
                ('light_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='inspection.lightpole', verbose_name='灯杆')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_orders', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', '照片'), ('video', '视频'), ('document', '文档'), ('other', '其他')], max_length=20, verbose_name='证据类型')),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/', verbose_name='文件')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inspection.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '证据',
                'verbose_name_plural': '证据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建工单'), ('assign', '派单'), ('start', '开始处理'), ('complete_inspection', '完成巡检'), ('submit_review', '提交复核'), ('review_confirm', '复核确认'), ('return', '退回返工'), ('archive', '归档'), ('update', '更新信息'), ('add_evidence', '添加证据')], max_length=30, verbose_name='操作')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inspection.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单历史',
                'verbose_name_plural': '工单历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
