# Generated by Django 5.1.4 on 2026-06-06 12:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(choices=[('20GP', '20GP'), ('40GP', '40GP'), ('40HQ', '40HQ'), ('45HQ', '45HQ')], max_length=10)),
                ('vessel_name', models.CharField(max_length=100, verbose_name='船名')),
                ('voyage_no', models.CharField(max_length=30, verbose_name='航次')),
                ('bl_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='提单号')),
                ('seal_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='封条号')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='毛重(吨)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '集装箱',
                'verbose_name_plural': '集装箱',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='单证名称')),
                ('is_required', models.BooleanField(default=True, verbose_name='必备单证')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '单证类型',
                'verbose_name_plural': '单证类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '货代公司',
                'verbose_name_plural': '货代公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='查验窗口名称')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '查验窗口',
                'verbose_name_plural': '查验窗口',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '航线/船公司',
                'verbose_name_plural': '航线/船公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=30, unique=True, verbose_name='预约编号')),
                ('route', models.CharField(max_length=100, verbose_name='航线')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(verbose_name='预约时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待查验'), ('in_inspection', '查验中'), ('normal_release', '正常放行'), ('doc_missing', '单证缺失'), ('rescheduled', '查验改期'), ('pending_fee', '待费用复核'), ('fee_confirmed', '费用确认'), ('fee_disputed', '滞箱费异议'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('inspection_reason', models.TextField(blank=True, null=True, verbose_name='查验原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('inspection_started_at', models.DateTimeField(blank=True, null=True, verbose_name='查验开始时间')),
                ('inspection_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='查验完成时间')),
                ('inspection_result', models.TextField(blank=True, null=True, verbose_name='查验结果')),
                ('demurrage_days', models.IntegerField(default=0, verbose_name='滞箱天数')),
                ('demurrage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='滞箱费(元)')),
                ('fee_reduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='减免金额(元)')),
                ('final_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最终费用(元)')),
                ('fee_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='费用确认时间')),
                ('fee_dispute_reason', models.TextField(blank=True, null=True, verbose_name='费用异议原因')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_appointments', to=settings.AUTH_USER_MODEL, verbose_name='归档人')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='inspection.container', verbose_name='集装箱')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('fee_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='费用确认人')),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='inspection.forwarder', verbose_name='货代公司')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_appointments', to=settings.AUTH_USER_MODEL, verbose_name='查验员')),
                ('inspection_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.inspectionwindow', verbose_name='查验窗口')),
                ('shipping_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='inspection.shippingline', verbose_name='船公司')),
            ],
            options={
                'verbose_name': '查验预约',
                'verbose_name_plural': '查验预约',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='费用项目')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额(元)')),
                ('is_reduction', models.BooleanField(default=False, verbose_name='减免项')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='inspection.inspectionappointment', verbose_name='查验预约')),
            ],
            options={
                'verbose_name': '费用明细',
                'verbose_name_plural': '费用明细',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('status_from', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '待查验'), ('in_inspection', '查验中'), ('normal_release', '正常放行'), ('doc_missing', '单证缺失'), ('rescheduled', '查验改期'), ('pending_fee', '待费用复核'), ('fee_confirmed', '费用确认'), ('fee_disputed', '滞箱费异议'), ('archived', '已归档')], max_length=20, null=True, verbose_name='原状态')),
                ('status_to', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '待查验'), ('in_inspection', '查验中'), ('normal_release', '正常放行'), ('doc_missing', '单证缺失'), ('rescheduled', '查验改期'), ('pending_fee', '待费用复核'), ('fee_confirmed', '费用确认'), ('fee_disputed', '滞箱费异议'), ('archived', '已归档')], max_length=20, null=True, verbose_name='新状态')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inspection.inspectionappointment', verbose_name='查验预约')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作历史',
                'verbose_name_plural': '操作历史',
                'ordering': ['-operated_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='原预约日期')),
                ('original_time', models.TimeField(verbose_name='原预约时间')),
                ('new_date', models.DateField(verbose_name='新预约日期')),
                ('new_time', models.TimeField(verbose_name='新预约时间')),
                ('reason', models.TextField(verbose_name='改期原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='inspection.inspectionappointment', verbose_name='查验预约')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '改期记录',
                'verbose_name_plural': '改期记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='shipping_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.shippingline'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('forwarder', '货代经办人'), ('yard', '场站人员'), ('fee_auditor', '费用复核人')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='已提交')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.documenttype', verbose_name='单证类型')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspection.inspectionappointment', verbose_name='查验预约')),
            ],
            options={
                'verbose_name': '单证',
                'verbose_name_plural': '单证',
                'unique_together': {('appointment', 'document_type')},
            },
        ),
    ]
