# Generated by Django 6.0.6 on 2026-06-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-is_adopted', '-created_at'], 'verbose_name': '证据', 'verbose_name_plural': '证据'},
        ),
        migrations.AddField(
            model_name='evidence',
            name='adopt_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='采用说明'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='adopted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='采用时间'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_evidences', to=settings.AUTH_USER_MODEL, verbose_name='采用人'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_adopted',
            field=models.BooleanField(default=False, verbose_name='是否采用'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='action',
            field=models.CharField(choices=[('create', '创建工单'), ('assign', '派单'), ('start', '开始处理'), ('complete_inspection', '完成巡检'), ('submit_review', '提交复核'), ('review_confirm', '复核确认'), ('return', '退回返工'), ('archive', '归档'), ('update', '更新信息'), ('add_evidence', '添加证据'), ('adopt_evidence', '采用证据'), ('unadopt_evidence', '取消采用证据')], max_length=30, verbose_name='操作'),
        ),
    ]
