# Generated by Django 6.0.6 on 2026-06-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('expire_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('engineering', '工程学院'), ('science', '理学院'), ('medicine', '医学院'), ('business', '商学院'), ('arts', '文学院')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('danger_level', models.CharField(choices=[('I', 'I级 - 无危险'), ('II', 'II级 - 低度危险'), ('III', 'III级 - 中度危险'), ('IV', 'IV级 - 高度危险')], default='I', max_length=10)),
                ('unit', models.CharField(default='个', max_length=20)),
                ('min_stock', models.IntegerField(default=10)),
                ('max_stock', models.IntegerField(default=100)),
                ('requires_qualification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chemical', '化学试剂'), ('glass', '玻璃器皿'), ('instrument', '仪器设备'), ('biological', '生物材料'), ('safety', '安全防护'), ('other', '其他')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField()),
                ('actual_quantity', models.IntegerField(default=0)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('inventory_checked', '库存已审核'), ('safety_checked', '安全已审核'), ('approved', '已批准'), ('issued', '已出库'), ('returned', '已归还'), ('overdue', '逾期未归还'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.CharField(blank=True, choices=[('stock_shortage', '库存不足'), ('qualification_missing', '危险品资质缺失'), ('overdue', '逾期未归还'), ('other', '其他')], max_length=50, null=True)),
                ('exception_note', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('inventory_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_checks', to=settings.AUTH_USER_MODEL)),
                ('lab_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_checks', to=settings.AUTH_USER_MODEL)),
                ('safety_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_checks', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='inventory.batch')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(choices=[('pending', '待审核'), ('inventory_checked', '库存已审核'), ('safety_checked', '安全已审核'), ('approved', '已批准'), ('issued', '已出库'), ('returned', '已归还'), ('overdue', '逾期未归还'), ('rejected', '已拒绝')], max_length=20)),
                ('status_after', models.CharField(choices=[('pending', '待审核'), ('inventory_checked', '库存已审核'), ('safety_checked', '安全已审核'), ('approved', '已批准'), ('issued', '已出库'), ('returned', '已归还'), ('overdue', '逾期未归还'), ('rejected', '已拒绝')], max_length=20)),
                ('operated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.application')),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='inventory.consumablecategory'),
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='inventory.college')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='research_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.researchgroup'),
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.IntegerField()),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='inventory.application')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', '教师'), ('stock_manager', '库管员'), ('safety_officer', '安全员'), ('lab_manager', '实验室负责人')], max_length=20)),
                ('has_dangerous_qualification', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.college')),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.researchgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
