# Generated by Django 5.0 on 2026-06-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True, verbose_name='批次号')),
                ('animal_type', models.CharField(max_length=50, verbose_name='动物种类')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('origin_country', models.CharField(max_length=50, verbose_name='来源国')),
                ('entry_date', models.DateField(verbose_name='入境日期')),
                ('quarantine_site', models.CharField(max_length=100, verbose_name='隔离场')),
                ('status', models.CharField(choices=[('pending', '待登记'), ('quarantining', '隔离中'), ('reviewing', '待复核'), ('approving', '待审批'), ('released', '已放行'), ('returned', '已退运'), ('extended', '延长隔离')], default='pending', max_length=20, verbose_name='状态')),
                ('vaccine_certificate', models.BooleanField(default=False, verbose_name='疫苗证明')),
                ('health_certificate', models.BooleanField(default=False, verbose_name='健康证明')),
                ('quarantine_certificate', models.BooleanField(default=False, verbose_name='检疫证书')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('release', '放行'), ('extend', '延长隔离'), ('return', '退运'), ('veterinary_review', '兽医复核')], max_length=20, verbose_name='操作')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因')),
                ('extend_days', models.IntegerField(blank=True, null=True, verbose_name='延长天数')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='batches.batch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '审批历史',
                'verbose_name_plural': '审批历史',
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('vaccine_certificate', '疫苗证明'), ('health_certificate', '健康证明'), ('quarantine_certificate', '检疫证书'), ('photo', '照片'), ('other', '其他')], max_length=50, verbose_name='文档类型')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='batches.batch', verbose_name='批次')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='batches.batch', verbose_name='批次')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
            ],
            options={
                'verbose_name': '状态历史',
                'verbose_name_plural': '状态历史',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='batches_bat_status_7a0087_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['origin_country'], name='batches_bat_origin__015bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['entry_date'], name='batches_bat_entry_d_e98ff7_idx'),
        ),
    ]
