default: &default
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: food_material_platform_development

test:
  <<: *default
  database: food_material_platform_test

production:
  <<: *default
  database: food_material_platform_production
