# Generated by Django 6.0.6 on 2026-06-10 17:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'core_department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('employee', '员工'), ('manager', '部门经理'), ('admin', '行政'), ('finance', '财务'), ('superadmin', '管理员')], default='employee', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_city', models.CharField(max_length=50, verbose_name='目的地城市')),
                ('purpose', models.TextField(verbose_name='出差事由')),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='预计预算')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('pending_booking', '待预订'), ('booked', '已预订'), ('pending_reimbursement', '待报销'), ('completed', '已完成'), ('rejected', '已驳回')], default='draft', max_length=25, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='core.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '差旅申请',
                'verbose_name_plural': '差旅申请',
                'db_table': 'core_travel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实际总费用')),
                ('receipt_status', models.CharField(choices=[('complete', '完整'), ('missing', '缺失'), ('pending_supplement', '待补充')], default='complete', max_length=20, verbose_name='票据状态')),
                ('has_flight_receipt', models.BooleanField(default=False, verbose_name='有机票票据')),
                ('has_hotel_receipt', models.BooleanField(default=False, verbose_name='有酒店票据')),
                ('has_meal_receipt', models.BooleanField(default=False, verbose_name='有餐饮票据')),
                ('has_meal_expense', models.BooleanField(default=False, verbose_name='有餐饮报销')),
                ('missing_receipts', models.TextField(blank=True, verbose_name='缺失票据描述')),
                ('finance_comments', models.TextField(blank=True, verbose_name='财务复核意见')),
                ('review_status', models.CharField(choices=[('pending', '待复核'), ('approved', '已通过'), ('returned', '已退回')], default='pending', max_length=20, verbose_name='复核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement', to='core.travel', verbose_name='差旅申请')),
            ],
            options={
                'verbose_name': '报销单',
                'verbose_name_plural': '报销单',
                'db_table': 'core_reimbursement',
            },
        ),
        migrations.CreateModel(
            name='HistoryNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', '创建申请'), ('submit', '提交申请'), ('approve', '审批通过'), ('reject', '审批驳回'), ('book', '预订行程'), ('update_booking', '更新预订'), ('create_reimbursement', '创建报销单'), ('approve_reimbursement', '报销通过'), ('return_reimbursement', '退回报销'), ('complete', '完成报销')], max_length=50, verbose_name='动作类型')),
                ('comment', models.TextField(blank=True, verbose_name='操作备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_nodes', to='core.travel', verbose_name='差旅申请')),
            ],
            options={
                'verbose_name': '历史节点',
                'verbose_name_plural': '历史节点',
                'db_table': 'core_history_node',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_info', models.JSONField(blank=True, default=dict, verbose_name='航班信息')),
                ('hotel_info', models.JSONField(blank=True, default=dict, verbose_name='酒店信息')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实际费用')),
                ('over_budget_reason', models.CharField(blank=True, choices=[('seasonal_high', '旺季价格上调'), ('location_price', '地点价格差异'), ('emergency_trip', '紧急出差无法提前预订'), ('event_special', '展会/会议期间价格上浮'), ('quality_requirement', '业务需要的品质要求'), ('other', '其他原因')], max_length=50, null=True, verbose_name='超标原因')),
                ('over_budget_reason_text', models.TextField(blank=True, verbose_name='超标原因说明')),
                ('booking_status', models.CharField(choices=[('pending', '待预订'), ('booked', '已预订'), ('confirmed', '已确认')], default='pending', max_length=20, verbose_name='预订状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='core.travel', verbose_name='差旅申请')),
            ],
            options={
                'verbose_name': '行程预订',
                'verbose_name_plural': '行程预订',
                'db_table': 'core_booking',
            },
        ),
    ]
