# Generated by Django 5.0.14 on 2026-06-17 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='批次名称')),
                ('description', models.TextField(blank=True, verbose_name='批次描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('latitude', models.DecimalField(decimal_places=6, default=39.9042, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, default=116.4074, max_digits=9, verbose_name='经度')),
                ('timezone_offset', models.IntegerField(default=8, verbose_name='时区')),
                ('total_records', models.IntegerField(default=0, verbose_name='总记录数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('error_count', models.IntegerField(default=0, verbose_name='异常数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('calculating', '推算中'), ('completed', '已完成'), ('error', '出错')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '推算批次',
                'verbose_name_plural': '推算批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('time_hour', models.IntegerField(default=12, verbose_name='时间(时)')),
                ('time_minute', models.IntegerField(default=0, verbose_name='时间(分)')),
                ('latitude', models.DecimalField(decimal_places=6, default=39.9042, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, default=116.4074, max_digits=9, verbose_name='经度')),
                ('timezone_offset', models.IntegerField(default=8, verbose_name='时区')),
                ('location_name', models.CharField(blank=True, max_length=100, verbose_name='地点名称')),
                ('lunar_year', models.IntegerField(blank=True, null=True, verbose_name='农历年')),
                ('lunar_month', models.IntegerField(blank=True, null=True, verbose_name='农历月')),
                ('lunar_day', models.IntegerField(blank=True, null=True, verbose_name='农历日')),
                ('lunar_month_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='农历月名')),
                ('lunar_day_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='农历日名')),
                ('is_leap_month', models.BooleanField(default=False, verbose_name='是否闰月')),
                ('year_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='年干支')),
                ('month_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='月干支')),
                ('day_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='日干支')),
                ('moon_phase', models.CharField(blank=True, max_length=20, null=True, verbose_name='月相')),
                ('moon_phase_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='月相类型')),
                ('solar_terms', models.JSONField(blank=True, null=True, verbose_name='节气数据')),
                ('calculation_steps', models.JSONField(blank=True, null=True, verbose_name='推算步骤')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('calculated', '已推算'), ('verified', '已验证'), ('abnormal', '异常')], default='draft', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='推算时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.calculationbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '推算记录',
                'verbose_name_plural': '推算记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('calculation_error', '推算错误'), ('date_out_of_range', '日期超出范围'), ('location_invalid', '地点无效'), ('solar_term_conflict', '节气冲突'), ('lunar_date_error', '农历日期错误'), ('manual_flag', '手动标记')], max_length=30, verbose_name='异常类型')),
                ('message', models.TextField(verbose_name='异常信息')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='详细数据')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormalities', to='core.calculationbatch', verbose_name='关联批次')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormalities', to='core.calculationrecord', verbose_name='关联记录')),
            ],
            options={
                'verbose_name': '异常数据',
                'verbose_name_plural': '异常数据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('changes', models.TextField(verbose_name='变更说明')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('time_hour', models.IntegerField(default=12, verbose_name='时间(时)')),
                ('time_minute', models.IntegerField(default=0, verbose_name='时间(分)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('timezone_offset', models.IntegerField(default=8, verbose_name='时区')),
                ('lunar_year', models.IntegerField(blank=True, null=True, verbose_name='农历年')),
                ('lunar_month', models.IntegerField(blank=True, null=True, verbose_name='农历月')),
                ('lunar_day', models.IntegerField(blank=True, null=True, verbose_name='农历日')),
                ('year_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='年干支')),
                ('month_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='月干支')),
                ('day_gan_zhi', models.CharField(blank=True, max_length=10, null=True, verbose_name='日干支')),
                ('moon_phase', models.CharField(blank=True, max_length=20, null=True, verbose_name='月相')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.calculationrecord', verbose_name='关联记录')),
            ],
            options={
                'verbose_name': '记录版本',
                'verbose_name_plural': '记录版本',
                'ordering': ['-version_number'],
            },
        ),
    ]
