# Generated by Django 5.0.14 on 2026-06-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_level', models.CharField(choices=[('minor', '轻微'), ('moderate', '中度'), ('severe', '严重'), ('critical', '损毁')], max_length=20, verbose_name='损伤等级')),
                ('damage_type', models.CharField(choices=[('page_damage', '页面破损'), ('stain', '污渍'), ('tear', '撕裂'), ('binding', '装订损坏'), ('mold', '霉变'), ('worm', '虫蛀'), ('other', '其他')], max_length=50, verbose_name='损伤类型')),
                ('damage_description', models.TextField(verbose_name='损伤描述')),
                ('damage_location', models.CharField(blank=True, max_length=200, verbose_name='损伤部位')),
                ('previous_damage', models.BooleanField(default=False, verbose_name='是否为旧损')),
                ('repair_suggestion', models.TextField(verbose_name='修复建议')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估修复费用')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='鉴定时间')),
                ('needs_supervisor_review', models.BooleanField(default=True, verbose_name='需主管审核')),
                ('assessment_notes', models.TextField(blank=True, verbose_name='鉴定备注')),
                ('circulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessment', to='circulation.circulationlog', verbose_name='流通记录')),
                ('conservator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人')),
            ],
            options={
                'verbose_name': '损伤鉴定',
                'verbose_name_plural': '损伤鉴定',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('return_to_stack', '正常归库'), ('send_for_repair', '送修'), ('compensation', '赔付处理'), ('restrict_access', '限制阅览')], max_length=30, verbose_name='决策类型')),
                ('decision_reason', models.TextField(verbose_name='决策理由')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='决策时间')),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='赔付金额')),
                ('compensation_notes', models.TextField(blank=True, verbose_name='赔付备注')),
                ('is_compensation_paid', models.BooleanField(default=False, verbose_name='赔付已支付')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='conservation.damageassessment', verbose_name='鉴定记录')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='主管')),
            ],
            options={
                'verbose_name': '归库决策',
                'verbose_name_plural': '归库决策',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='修复开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='修复完成日期')),
                ('repair_description', models.TextField(verbose_name='修复内容')),
                ('materials_used', models.TextField(blank=True, verbose_name='使用材料')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际费用')),
                ('repair_notes', models.TextField(blank=True, verbose_name='修复备注')),
                ('is_completed', models.BooleanField(default=False, verbose_name='修复完成')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_records', to='conservation.damageassessment', verbose_name='鉴定记录')),
                ('repairer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_done', to=settings.AUTH_USER_MODEL, verbose_name='修复人员')),
            ],
            options={
                'verbose_name': '修复记录',
                'verbose_name_plural': '修复记录',
                'ordering': ['-start_date'],
            },
        ),
    ]
