# Generated by Django 5.2.15 on 2026-06-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '已失败')], default='active', max_length=20)),
                ('ticket_price', models.IntegerField(default=10)),
                ('open_windows', models.IntegerField(default=2)),
                ('car_capacity', models.IntegerField(default=6)),
                ('dispatch_interval', models.IntegerField(default=10)),
                ('current_tick', models.IntegerField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_served', models.IntegerField(default=0)),
                ('total_departed', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('queue_json', models.TextField(default='[]')),
                ('income_history_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('difficulty', models.IntegerField(default=1)),
                ('target_income', models.IntegerField(default=500)),
                ('max_complaints', models.IntegerField(default=10)),
                ('time_limit', models.IntegerField(default=120)),
                ('initial_ticket_price', models.IntegerField(default=10)),
                ('initial_windows', models.IntegerField(default=2)),
                ('car_capacity', models.IntegerField(default=6)),
                ('tourist_rate', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.CreateModel(
            name='DispatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('car_index', models.IntegerField()),
                ('passenger_count', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('wait_times_json', models.TextField(default='[]')),
                ('destinations_json', models.TextField(default='[]')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='game.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.level'),
        ),
        migrations.CreateModel(
            name='PatienceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('patience_before', models.IntegerField()),
                ('patience_after', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('tourist_count', models.IntegerField(default=0)),
                ('complaint_count', models.IntegerField(default=0)),
                ('note', models.TextField(default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patience_results', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='TouristHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_entered', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('patience', models.IntegerField(default=5)),
                ('needs_transfer', models.BooleanField(default=False)),
                ('ticket_price_at_entry', models.IntegerField(default=10)),
                ('served', models.BooleanField(default=False)),
                ('complained', models.BooleanField(default=False)),
                ('wait_ticks', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourists', to='game.gamesession')),
            ],
            options={
                'ordering': ['tick_entered'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('severity', models.IntegerField(default=1)),
                ('rolled_back', models.BooleanField(default=False)),
                ('rollback_tick', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='game.gamesession')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.touristhistory')),
            ],
            options={
                'ordering': ['tick'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('cumulative_income', models.IntegerField(default=0)),
                ('tick_income', models.IntegerField(default=0)),
                ('ticket_price', models.IntegerField(default=10)),
                ('queue_length', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_snapshots', to='game.gamesession')),
            ],
            options={
                'ordering': ['tick'],
                'unique_together': {('session', 'tick')},
            },
        ),
    ]
