# Generated by Django 5.1.15 on 2026-06-16 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('setup', '布置阶段'), ('playing', '进行中'), ('won', '胜利'), ('lost', '失败')], default='setup', max_length=20)),
                ('current_turn', models.IntegerField(default=0)),
                ('wall_health', models.IntegerField(default=100)),
                ('max_wall_health', models.IntegerField(default=100)),
                ('gold', models.IntegerField(default=100)),
                ('score', models.IntegerField(default=0)),
                ('enemies_killed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('server_checksum', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enemy_waves', models.JSONField()),
                ('base_reward', models.IntegerField(default=50)),
                ('difficulty', models.FloatField(default=1.0)),
                ('unlocked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('range', models.IntegerField()),
                ('cooldown', models.IntegerField(default=2)),
                ('emoji', models.CharField(default='🏰', max_length=10)),
                ('color', models.CharField(default='#4a5568', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_type', models.CharField(choices=[('grunt', '步兵'), ('fast', '快骑兵'), ('tank', '重装兵'), ('boss', 'BOSS')], max_length=20)),
                ('health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('speed', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=10)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.IntegerField()),
                ('spawn_turn', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('path_index', models.IntegerField(default=0)),
                ('score_value', models.IntegerField(default=10)),
                ('gold_value', models.IntegerField(default=5)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('detailed_log', models.JSONField()),
                ('final_score', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('enemies_killed', models.IntegerField()),
                ('traps_used', models.IntegerField()),
                ('tasks_completed', models.IntegerField()),
                ('damage_to_wall', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('action_type', models.CharField(choices=[('place_trap', '放置陷阱'), ('remove_trap', '移除陷阱'), ('start_task', '开始任务'), ('complete_task', '完成任务'), ('next_turn', '下一回合'), ('start_attack', '开始进攻'), ('trigger_trap', '触发陷阱'), ('enemy_move', '敌人移动'), ('enemy_damage', '敌人受伤'), ('wall_damage', '城墙受伤')], max_length=30)),
                ('details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game.gamesession')),
            ],
            options={
                'ordering': ['turn', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level'),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('gold', models.IntegerField(default=100)),
                ('total_score', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.playerprofile'),
        ),
        migrations.CreateModel(
            name='ReplayFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('frame_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_frames', to='game.gamesession')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('server_calculated_score', models.IntegerField(default=0)),
                ('gold_earned', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_record', to='game.gamesession')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='CraftsmanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_gold', models.IntegerField()),
                ('duration_turns', models.IntegerField()),
                ('start_turn', models.IntegerField()),
                ('end_turn', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '已失败')], default='pending', max_length=20)),
                ('reward_gold', models.IntegerField(default=0)),
                ('reward_score', models.IntegerField(default=0)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='game.gamesession')),
                ('reward_trap_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.traptype')),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('last_triggered', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traps', to='game.gamesession')),
                ('trap_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.traptype')),
            ],
            options={
                'unique_together': {('game_session', 'position_x', 'position_y')},
            },
        ),
    ]
