# Generated by Django 5.2.15 on 2026-06-16 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', '进行中'), ('won', '已通关'), ('lost', '已失败')], default='playing', max_length=10, verbose_name='游戏状态')),
                ('current_steps', models.IntegerField(default=0, verbose_name='当前步数')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '游戏局次',
                'verbose_name_plural': '游戏局次',
                'db_table': 'game_session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='关卡名称')),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='难度最小为1'), django.core.validators.MaxValueValidator(5, message='难度最大为5')], verbose_name='难度等级')),
                ('grid_data', models.JSONField(verbose_name='网格数据')),
                ('best_steps', models.IntegerField(default=0, verbose_name='最佳步数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关卡',
                'verbose_name_plural': '关卡',
                'db_table': 'level',
                'ordering': ['difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(default=0, verbose_name='最终得分')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通关')),
                ('steps_used', models.IntegerField(default=0, verbose_name='使用步数')),
                ('collapse_count', models.IntegerField(default=0, verbose_name='坍缩次数')),
                ('undo_count', models.IntegerField(default=0, verbose_name='撤销次数')),
                ('server_score', models.IntegerField(default=0, verbose_name='服务器重算分数')),
                ('detail', models.JSONField(default=dict, verbose_name='结算详情')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='game.gamesession', verbose_name='游戏局次')),
            ],
            options={
                'verbose_name': '游戏结算',
                'verbose_name_plural': '游戏结算',
                'db_table': 'game_result',
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.IntegerField(verbose_name='操作序号')),
                ('action_type', models.CharField(choices=[('move', '移动'), ('collapse', '坍缩'), ('undo', '撤销')], max_length=10, verbose_name='操作类型')),
                ('direction', models.CharField(blank=True, choices=[('up', '上'), ('down', '下'), ('left', '左'), ('right', '右')], max_length=5, null=True, verbose_name='操作方向')),
                ('state_before', models.JSONField(verbose_name='操作前状态')),
                ('state_after', models.JSONField(verbose_name='操作后状态')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gamesession', verbose_name='游戏局次')),
            ],
            options={
                'verbose_name': '游戏操作',
                'verbose_name_plural': '游戏操作',
                'db_table': 'game_action',
                'ordering': ['session_id', 'action_number'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='game.level', verbose_name='关卡'),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='玩家昵称')),
                ('total_score', models.IntegerField(default=0, verbose_name='总得分')),
                ('play_count', models.IntegerField(default=0, verbose_name='游玩次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '玩家档案',
                'verbose_name_plural': '玩家档案',
                'db_table': 'player_profile',
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='game.playerprofile', verbose_name='玩家'),
        ),
    ]
