# Generated by Django 5.2.15 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienceresult',
            name='normal_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='normal_patience_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='normal_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='transfer_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='transfer_patience_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='transfer_revenue_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patienceresult',
            name='transfer_served',
            field=models.IntegerField(default=0),
        ),
    ]
