# Generated by Django 5.2.15 on 2026-06-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_patienceresult_normal_complaints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollbackSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollback_tick', models.IntegerField()),
                ('to_tick', models.IntegerField()),
                ('rolled_back_count', models.IntegerField(default=0)),
                ('before_complaints', models.IntegerField(default=0)),
                ('before_score', models.IntegerField(default=0)),
                ('before_income', models.IntegerField(default=0)),
                ('before_served', models.IntegerField(default=0)),
                ('after_complaints', models.IntegerField(default=0)),
                ('after_score', models.IntegerField(default=0)),
                ('after_income', models.IntegerField(default=0)),
                ('after_served', models.IntegerField(default=0)),
                ('delta_complaints', models.IntegerField(default=0)),
                ('delta_score', models.IntegerField(default=0)),
                ('delta_income', models.IntegerField(default=0)),
                ('delta_penalty', models.IntegerField(default=0)),
                ('transfer_rolled_back', models.IntegerField(default=0)),
                ('normal_rolled_back', models.IntegerField(default=0)),
                ('restored_queue_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_snapshots', to='game.gamesession')),
            ],
            options={
                'ordering': ['-rollback_tick'],
            },
        ),
    ]
