# Generated by Django 5.2.15 on 2026-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rollbacksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollbacksnapshot',
            name='income_curve_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rollbacksnapshot',
            name='income_curve_tick_labels_json',
            field=models.TextField(default=''),
        ),
    ]
