# Generated by Django 5.0.14 on 2026-06-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecoveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='记录编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('source', models.CharField(choices=[('auto_scan', '系统自动扫描'), ('manual_report', '人工报备'), ('complaint', '投诉举报'), ('audit', '审计发现')], default='auto_scan', max_length=30, verbose_name='来源')),
                ('sample_type', models.CharField(choices=[('normal_release', '正常放行'), ('over_limit', '指标超限'), ('evidence_missing', '现场证据缺失'), ('timeout', '审批超时')], max_length=30, verbose_name='样本类型')),
                ('status', models.CharField(choices=[('pending_accept', '待受理'), ('accepted', '已受理'), ('processing', '处理中'), ('reviewing', '复核中'), ('archived', '已归档'), ('rejected', '已退回')], default='pending_accept', max_length=30, verbose_name='状态')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申请人姓名')),
                ('applicant_dept', models.CharField(max_length=100, verbose_name='申请人部门')),
                ('applicant_id', models.CharField(max_length=50, verbose_name='申请人工号')),
                ('lab_name', models.CharField(max_length=150, verbose_name='实验室名称')),
                ('lab_code', models.CharField(max_length=50, verbose_name='实验室编号')),
                ('access_area', models.CharField(max_length=150, verbose_name='授权区域')),
                ('original_authorized_date', models.DateField(verbose_name='原授权日期')),
                ('expiry_date', models.DateField(verbose_name='到期日期')),
                ('recovered_date', models.DateField(blank=True, null=True, verbose_name='实际回收日期')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='处理截止时间')),
                ('authorized_person_count', models.IntegerField(default=0, verbose_name='授权人数')),
                ('involved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='涉及金额')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '极高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('business_note', models.TextField(blank=True, verbose_name='业务记录')),
                ('site_description', models.TextField(blank=True, verbose_name='现场说明')),
                ('conclusion', models.TextField(blank=True, verbose_name='处理结论')),
                ('recovery_basis', models.TextField(blank=True, verbose_name='采用依据')),
                ('remedial_path', models.TextField(blank=True, verbose_name='补救路径')),
                ('block_reason', models.TextField(blank=True, verbose_name='阻断原因')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='是否被阻断')),
                ('has_anomaly', models.BooleanField(default=False, verbose_name='是否存在异常')),
                ('diff_fields', models.JSONField(blank=True, default=dict, verbose_name='差异字段')),
                ('snapshot_before', models.JSONField(blank=True, default=dict, verbose_name='处理前快照')),
                ('snapshot_after', models.JSONField(blank=True, default=dict, verbose_name='处理后快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '门禁授权回收记录',
                'verbose_name_plural': '门禁授权回收记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyBlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_code', models.CharField(max_length=50, verbose_name='阻断代码')),
                ('block_reason', models.TextField(verbose_name='阻断原因')),
                ('diff_fields', models.JSONField(blank=True, default=dict, verbose_name='差异字段详情')),
                ('remedial_path', models.TextField(verbose_name='补救路径')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='阻断时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_note', models.TextField(blank=True, verbose_name='解决说明')),
            ],
            options={
                'verbose_name': '异常阻断记录',
                'verbose_name_plural': '异常阻断记录',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', '现场照片'), ('video', '视频录像'), ('document', '书面文档'), ('signature', '签字确认'), ('access_log', '门禁日志'), ('other', '其他')], max_length=30, verbose_name='证据类型')),
                ('title', models.CharField(max_length=200, verbose_name='证据标题')),
                ('description', models.TextField(blank=True, verbose_name='证据描述')),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/', verbose_name='附件文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('invalid_reason', models.TextField(blank=True, verbose_name='失效原因')),
            ],
            options={
                'verbose_name': '证据附件',
                'verbose_name_plural': '证据附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_label', models.CharField(max_length=100, verbose_name='字段显示名')),
                ('old_value', models.TextField(blank=True, verbose_name='原值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '字段变更日志',
                'verbose_name_plural': '字段变更日志',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('accept', '受理'), ('process', '处理'), ('submit_review', '提交复核'), ('review_pass', '复核通过'), ('review_reject', '复核退回'), ('archive', '归档'), ('supplement', '补充材料'), ('reopen', '重新处理'), ('block', '异常阻断'), ('unblock', '解除阻断')], max_length=30, verbose_name='节点类型')),
                ('node_title', models.CharField(max_length=200, verbose_name='节点标题')),
                ('description', models.TextField(blank=True, verbose_name='节点描述')),
                ('previous_status', models.CharField(choices=[('pending_accept', '待受理'), ('accepted', '已受理'), ('processing', '处理中'), ('reviewing', '复核中'), ('archived', '已归档'), ('rejected', '已退回')], max_length=30, verbose_name='变更前状态')),
                ('new_status', models.CharField(choices=[('pending_accept', '待受理'), ('accepted', '已受理'), ('processing', '处理中'), ('reviewing', '复核中'), ('archived', '已归档'), ('rejected', '已退回')], max_length=30, verbose_name='变更后状态')),
                ('field_changes', models.JSONField(blank=True, default=dict, verbose_name='字段变更')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sequence', models.IntegerField(default=0, verbose_name='节点序号')),
            ],
            options={
                'verbose_name': '处理节点',
                'verbose_name_plural': '处理节点',
                'ordering': ['record', 'sequence', '-created_at'],
            },
        ),
    ]
