# Generated by Django 5.0.14 on 2026-06-12 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_records', to=settings.AUTH_USER_MODEL, verbose_name='受理人'),
        ),
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='current_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_records', to=settings.AUTH_USER_MODEL, verbose_name='当前责任人'),
        ),
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_records', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='accessrecoveryrecord',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AddField(
            model_name='anomalyblockrecord',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_records', to=settings.AUTH_USER_MODEL, verbose_name='阻断人'),
        ),
        migrations.AddField(
            model_name='anomalyblockrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_blocks', to='access_control.accessrecoveryrecord', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='anomalyblockrecord',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_blocks', to=settings.AUTH_USER_MODEL, verbose_name='解决人'),
        ),
        migrations.AddField(
            model_name='evidenceattachment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='access_control.accessrecoveryrecord', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='evidenceattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='fieldchangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='fieldchangelog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='access_control.accessrecoveryrecord', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='processingnode',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_nodes', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='processingnode',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='access_control.accessrecoveryrecord', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='fieldchangelog',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='access_control.processingnode', verbose_name='关联节点'),
        ),
        migrations.AddField(
            model_name='evidenceattachment',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='access_control.processingnode', verbose_name='关联节点'),
        ),
        migrations.AddField(
            model_name='anomalyblockrecord',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_blocks', to='access_control.processingnode', verbose_name='关联节点'),
        ),
        migrations.AddIndex(
            model_name='accessrecoveryrecord',
            index=models.Index(fields=['status', 'sample_type'], name='access_cont_status_e60485_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrecoveryrecord',
            index=models.Index(fields=['expiry_date', 'recovered_date'], name='access_cont_expiry__bead9a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrecoveryrecord',
            index=models.Index(fields=['current_owner', 'is_archived'], name='access_cont_current_8398b4_idx'),
        ),
        migrations.AddIndex(
            model_name='processingnode',
            index=models.Index(fields=['record', 'node_type'], name='access_cont_record__830d41_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldchangelog',
            index=models.Index(fields=['record', 'field_name'], name='access_cont_record__7ee54a_idx'),
        ),
    ]
