# Generated by Django 5.0.6 on 2026-06-05 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.CharField(max_length=50, unique=True, verbose_name='电梯编号')),
                ('building', models.CharField(max_length=100, verbose_name='所在楼宇')),
                ('floor', models.CharField(max_length=50, verbose_name='所在楼层')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='生产厂家')),
                ('install_date', models.DateField(verbose_name='安装日期')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维保日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维保日期')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停梯'), ('maintenance', '维保中'), ('fault', '故障中')], default='running', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '电梯',
                'verbose_name_plural': '电梯',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='维保单位名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '维保单位',
                'verbose_name_plural': '维保单位',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配件名称')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='配件编号')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('status', models.CharField(choices=[('in_stock', '库存充足'), ('low_stock', '库存不足'), ('waiting', '待到货'), ('ordered', '已订购')], default='in_stock', max_length=20, verbose_name='状态')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '配件',
                'verbose_name_plural': '配件',
            },
        ),
        migrations.CreateModel(
            name='FaultTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_source', models.CharField(choices=[('resident', '业主报修'), ('inspection', '巡检发现'), ('alarm', '系统告警'), ('maintenance', '维保发现')], max_length=30, verbose_name='故障来源')),
                ('fault_description', models.TextField(verbose_name='故障描述')),
                ('fault_location', models.CharField(blank=True, max_length=200, verbose_name='故障位置')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('reported', '已报修'), ('confirmed', '停梯已确认'), ('dispatched', '已派单'), ('parts_waiting', '配件待到'), ('in_repair', '维修中'), ('repaired', '维修完成待复核'), ('reviewing', '复核中'), ('returned', '已退回'), ('archived', '已归档')], default='reported', max_length=30, verbose_name='状态')),
                ('is_repeat_fault', models.BooleanField(default=False, verbose_name='是否重复故障')),
                ('repeat_difference', models.TextField(blank=True, verbose_name='重复故障差异说明')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='报修人姓名')),
                ('reporter_phone', models.CharField(max_length=20, verbose_name='报修人电话')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报修时间')),
                ('stop_confirmation_time', models.DateTimeField(blank=True, null=True, verbose_name='停梯确认时间')),
                ('company_mismatch', models.BooleanField(default=False, verbose_name='维保单位不匹配')),
                ('mismatch_note', models.TextField(blank=True, verbose_name='单位不匹配说明')),
                ('assigned_time', models.DateTimeField(blank=True, null=True, verbose_name='派单时间')),
                ('repair_start_time', models.DateTimeField(blank=True, null=True, verbose_name='维修开始时间')),
                ('repair_end_time', models.DateTimeField(blank=True, null=True, verbose_name='维修完成时间')),
                ('repair_description', models.TextField(blank=True, verbose_name='维修内容描述')),
                ('repair_parts_used', models.TextField(blank=True, verbose_name='使用配件明细')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='复核意见')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='指派维保人员')),
                ('current_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tickets', to=settings.AUTH_USER_MODEL, verbose_name='当前责任人')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.elevator', verbose_name='电梯')),
                ('previous_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.faultticket', verbose_name='上次故障工单')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('stop_confirmation_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='停梯确认人')),
            ],
            options={
                'verbose_name': '故障工单',
                'verbose_name_plural': '故障工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='elevator',
            name='maintenance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancecompany', verbose_name='维保单位'),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('regular', '按期维保'), ('emergency', '应急维保')], default='regular', max_length=20, verbose_name='维保类型')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('description', models.TextField(verbose_name='维保内容描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='指派维保人员')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.elevator', verbose_name='电梯')),
            ],
            options={
                'verbose_name': '维保计划',
                'verbose_name_plural': '维保计划',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('report', '报修'), ('confirm_stop', '确认停梯'), ('dispatch', '派单'), ('parts_wait', '配件待到'), ('start_repair', '开始维修'), ('complete_repair', '完成维修'), ('submit_check', '提交检查记录'), ('review_pass', '复核通过'), ('review_return', '复核退回'), ('archive', '归档'), ('note', '备注'), ('status_change', '状态变更')], max_length=30, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='变更前状态')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='变更后状态')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='maintenance.faultticket', verbose_name='关联工单')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='maintenance.maintenanceplan', verbose_name='关联维保计划')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_items', models.JSONField(default=dict, verbose_name='检查项目')),
                ('abnormal_items', models.TextField(blank=True, verbose_name='异常项目')),
                ('handling_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='更换配件')),
                ('signature', models.TextField(blank=True, verbose_name='签名')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.elevator', verbose_name='电梯')),
                ('maintenance_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='维保人员')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceplan', verbose_name='维保计划')),
            ],
            options={
                'verbose_name': '维保记录',
                'verbose_name_plural': '维保记录',
            },
        ),
        migrations.CreateModel(
            name='TicketPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(default=1, verbose_name='需要数量')),
                ('quantity_used', models.IntegerField(default=0, verbose_name='已使用数量')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.part', verbose_name='配件')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.faultticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单配件',
                'verbose_name_plural': '工单配件',
            },
        ),
        migrations.AddField(
            model_name='faultticket',
            name='parts_needed',
            field=models.ManyToManyField(blank=True, through='maintenance.TicketPart', to='maintenance.part', verbose_name='所需配件'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('maintenance_staff', '维保人员'), ('property_handler', '物业经办人'), ('property_reviewer', '物业复核人')], max_length=30, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancecompany', verbose_name='所属单位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
