# Generated by Django 5.0.6 on 2026-06-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='current_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_plans', to=settings.AUTH_USER_MODEL, verbose_name='当前责任人'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='复核意见'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复核时间'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plans', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('report', '报修'), ('confirm_stop', '确认停梯'), ('dispatch', '派单'), ('parts_wait', '配件待到'), ('start_repair', '开始维修'), ('complete_repair', '完成维修'), ('submit_check', '提交检查记录'), ('review_pass', '复核通过'), ('review_return', '复核退回'), ('archive', '归档'), ('note', '备注'), ('status_change', '状态变更'), ('plan_start', '开始维保'), ('plan_submit', '提交维保记录'), ('plan_review_pass', '计划复核通过'), ('plan_review_return', '计划复核退回'), ('plan_complete', '计划完成归档')], max_length=30, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('submitted', '已提交待复核'), ('reviewing', '复核中'), ('approved', '已通过'), ('returned', '已退回重填'), ('completed', '已完成归档'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
