# Generated by Django 5.0.14 on 2026-06-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类代码')),
                ('rarity_level', models.CharField(choices=[('common', '普通古籍'), ('rare', '珍本'), ('precious', '特藏珍本')], default='common', max_length=20, verbose_name='珍责等级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '馆藏分类',
                'verbose_name_plural': '馆藏分类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RareBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('call_number', models.CharField(max_length=50, unique=True, verbose_name='索书号')),
                ('status', models.CharField(choices=[('in_stack', '在库'), ('reserved', '已预约'), ('checked_out', '已调出'), ('in_repair', '修复中'), ('restricted', '限制阅览')], default='in_stack', max_length=20, verbose_name='馆藏状态')),
                ('condition', models.CharField(choices=[('excellent', '完好'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', max_length=20, verbose_name='保存状况')),
                ('description', models.TextField(blank=True, verbose_name='内容简介')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版年代')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版者')),
                ('edition', models.CharField(blank=True, max_length=100, verbose_name='版本')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('format_size', models.CharField(blank=True, max_length=50, verbose_name='开本')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='馆藏位置')),
                ('cover_image', models.CharField(blank=True, max_length=255, verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.bookcategory', verbose_name='馆藏分类')),
            ],
            options={
                'verbose_name': '珍本',
                'verbose_name_plural': '珍本',
                'ordering': ['call_number'],
            },
        ),
        migrations.CreateModel(
            name='DamageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_level', models.CharField(choices=[('minor', '轻微'), ('moderate', '中度'), ('severe', '严重'), ('critical', '损毁')], max_length=20, verbose_name='损伤等级')),
                ('description', models.TextField(verbose_name='损伤描述')),
                ('discovered_date', models.DateField(auto_now_add=True, verbose_name='发现日期')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='catalog.rarebook', verbose_name='珍本')),
            ],
            options={
                'verbose_name': '损伤记录',
                'verbose_name_plural': '损伤记录',
                'ordering': ['-discovered_date'],
            },
        ),
    ]
