# Generated by Django 5.0.6 on 2026-06-07 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='借展方名称')),
                ('type', models.CharField(choices=[('museum', '博物馆'), ('gallery', '美术馆'), ('university', '高校'), ('research', '科研机构'), ('other', '其他')], default='museum', max_length=20, verbose_name='机构类型')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('credit_rating', models.IntegerField(default=3, verbose_name='信用评级(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '借展方',
                'verbose_name_plural': '借展方',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='展品名称')),
                ('accession_number', models.CharField(max_length=50, unique=True, verbose_name='登记号')),
                ('level', models.CharField(choices=[('first', '一级文物'), ('second', '二级文物'), ('third', '三级文物'), ('general', '一般文物')], default='general', max_length=20, verbose_name='文物级别')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='类别')),
                ('era', models.CharField(blank=True, max_length=100, verbose_name='年代')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='估值(元)')),
                ('temperature_min', models.FloatField(default=15.0, verbose_name='最低温度(°C)')),
                ('temperature_max', models.FloatField(default=25.0, verbose_name='最高温度(°C)')),
                ('humidity_min', models.FloatField(default=45.0, verbose_name='最低湿度(%)')),
                ('humidity_max', models.FloatField(default=65.0, verbose_name='最高湿度(%)')),
                ('status', models.CharField(choices=[('in_storage', '在库'), ('on_loan', '出借中'), ('in_transport', '运输中'), ('conserved', '修复中')], default='in_storage', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展品',
                'verbose_name_plural': '展品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True, verbose_name='出借编号')),
                ('purpose', models.TextField(verbose_name='出借目的')),
                ('planned_start_date', models.DateField(verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(verbose_name='计划结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('transport_registered', '运输已登记'), ('insurance_pending', '待保险复核'), ('insurance_approved', '保险已通过'), ('insurance_rejected', '保险未通过'), ('out_of_storage', '已出库'), ('in_transit', '运输中'), ('arrived', '已到达'), ('on_display', '展出中'), ('returning', '归还中'), ('returned', '已归还'), ('inspection_pending', '待鉴定'), ('inspection_done', '鉴定完成'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.borrower', verbose_name='借展方')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.exhibit', verbose_name='展品')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_loans', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '出借申请',
                'verbose_name_plural': '出借申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, verbose_name='保单号')),
                ('insurance_company', models.CharField(max_length=200, verbose_name='保险公司')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='保额(元)')),
                ('coverage_type', models.CharField(blank=True, max_length=200, verbose_name='险种')),
                ('start_date', models.DateField(verbose_name='生效日期')),
                ('end_date', models.DateField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_notes', models.TextField(blank=True, verbose_name='复核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insurances', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='loans.loanapplication', verbose_name='出借单')),
            ],
            options={
                'verbose_name': '保险单',
                'verbose_name_plural': '保险单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='是否异常')),
                ('anomaly_type', models.CharField(blank=True, max_length=50, verbose_name='异常类型')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_environments', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_data', to='loans.loanapplication', verbose_name='出借单')),
            ],
            options={
                'verbose_name': '环境数据',
                'verbose_name_plural': '环境数据',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(verbose_name='归还日期')),
                ('condition', models.CharField(choices=[('perfect', '完好'), ('minor_damage', '轻微损伤'), ('major_damage', '严重损伤'), ('lost', '丢失')], max_length=20, verbose_name='归还状况')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('photos', models.TextField(blank=True, verbose_name='照片记录')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='鉴定日期')),
                ('recommendations', models.TextField(blank=True, verbose_name='处理建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conservator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_inspection', to='loans.loanapplication', verbose_name='出借单')),
            ],
            options={
                'verbose_name': '归还鉴定',
                'verbose_name_plural': '归还鉴定',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='目标状态')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loans.loanapplication', verbose_name='出借单')),
            ],
            options={
                'verbose_name': '状态历史',
                'verbose_name_plural': '状态历史',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=200, verbose_name='出发地')),
                ('route_to', models.CharField(max_length=200, verbose_name='目的地')),
                ('transport_company', models.CharField(max_length=200, verbose_name='运输公司')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, verbose_name='车辆编号')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='司机姓名')),
                ('driver_phone', models.CharField(blank=True, max_length=50, verbose_name='司机电话')),
                ('packing_method', models.CharField(blank=True, max_length=200, verbose_name='包装方式')),
                ('estimated_departure', models.DateTimeField(blank=True, null=True, verbose_name='预计出发时间')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='实际出发时间')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to='loans.loanapplication', verbose_name='出借单')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_transports', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '运输记录',
                'verbose_name_plural': '运输记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('collection_clerk', '馆藏经办人'), ('transport_coordinator', '运输协调人'), ('insurance_reviewer', '保险复核人'), ('conservator', '文保人员'), ('admin', '系统管理员')], default='collection_clerk', max_length=30, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
