import { StageConfig, GameEvent } from './types';

const yinEvents: GameEvent[] = [
  {
    id: 'yin-repair-1',
    name: '微光校准',
    description: '使用微量银盐校准一处暗槽，归并值小幅上升。',
    type: 'repair',
    cost: 1,
    effect: { mergeValue: 5, slots: { lit: true, target: 'first-dark' } },
  },
  {
    id: 'yin-repair-2',
    name: '节拍同步',
    description: '同步暗房节拍，归并值稳定上升。',
    type: 'repair',
    cost: 2,
    effect: { mergeValue: 12, slots: { lit: true, value: 2, target: 'first-dark' } },
  },
  {
    id: 'yin-reward-1',
    name: '丁号增益',
    description: '激活丁号奖励槽，获得额外奖励值。',
    type: 'reward',
    cost: 0,
    effect: { rewardDing: 10, mergeValue: 3 },
  },
  {
    id: 'yin-risk-1',
    name: '寅号试探',
    description: '高风险高回报，归并值大增但风险上升。',
    type: 'risk',
    cost: 0,
    effect: { mergeValue: 20, riskYin: 15 },
  },
  {
    id: 'yin-patrol-1',
    name: '巡测推进',
    description: '推进巡测痕位置，检测暗房状态。',
    type: 'special',
    cost: 1,
    effect: { patrol: 2, mergeValue: 2 },
  },
];

const dingEvents: GameEvent[] = [
  {
    id: 'ding-repair-1',
    name: '微光校准',
    description: '资源紧张下的微量校准。',
    type: 'repair',
    cost: 2,
    effect: { mergeValue: 4, slots: { lit: true, target: 'first-dark' } },
  },
  {
    id: 'ding-repair-2',
    name: '浓缩银盐',
    description: '使用浓缩银盐，效果显著但消耗大。',
    type: 'repair',
    cost: 4,
    effect: { mergeValue: 15, slots: { lit: true, value: 3, target: 'first-dark' } },
  },
  {
    id: 'ding-reward-1',
    name: '丁号储蓄',
    description: '积累丁号奖励，为后续步骤蓄力。',
    type: 'reward',
    cost: 1,
    effect: { rewardDing: 15, mergeValue: 2 },
  },
  {
    id: 'ding-risk-1',
    name: '寅号冒险',
    description: '资源短缺时的冒险选择，可能崩盘。',
    type: 'risk',
    cost: 0,
    effect: { mergeValue: 25, riskYin: 25, failGui: 5 },
  },
  {
    id: 'ding-patrol-1',
    name: '巡测扫描',
    description: '全面扫描，消耗资源但获取信息。',
    type: 'special',
    cost: 3,
    effect: { patrol: 3, slots: { lit: true, target: 'random' } },
  },
  {
    id: 'ding-fail-1',
    name: '癸号侵蚀',
    description: '失败因子累积，小心使用！',
    type: 'risk',
    cost: 0,
    effect: { mergeValue: 30, failGui: 20, riskYin: 10 },
  },
];

const guiEvents: GameEvent[] = [
  {
    id: 'gui-repair-1',
    name: '暗房秘术',
    description: '失传的暗房修复秘术，效果神秘。',
    type: 'repair',
    cost: 2,
    effect: { mergeValue: 10, slots: { lit: true, value: 2, target: 'first-dark' } },
  },
  {
    id: 'gui-repair-2',
    name: '银盐共鸣',
    description: '银盐粒子共振，归并值跃升。',
    type: 'repair',
    cost: 3,
    effect: { mergeValue: 18, slots: { lit: true, value: 2, target: 'first-dark' } },
  },
  {
    id: 'gui-reward-1',
    name: '丁号赐福',
    description: '丁号奖励降临，获得大量加成。',
    type: 'reward',
    cost: 1,
    effect: { rewardDing: 20, mergeValue: 5, slots: { lit: true, target: 'random' } },
  },
  {
    id: 'gui-risk-1',
    name: '寅号试炼',
    description: '寅号风险试炼，考验你的决断。',
    type: 'risk',
    cost: 0,
    effect: { mergeValue: 30, riskYin: 20 },
  },
  {
    id: 'gui-patrol-1',
    name: '巡测残影',
    description: '巡测痕留下残影，隐藏路径显现。',
    type: 'special',
    cost: 2,
    effect: { patrol: 2, mergeValue: 3, failGui: -5 },
  },
  {
    id: 'gui-hidden-trigger',
    name: '癸号密钥',
    description: '传说中的癸号密钥，似乎能触发什么...',
    type: 'special',
    cost: 5,
    effect: { mergeValue: 8, failGui: -15, riskYin: -10 },
  },
  {
    id: 'gui-fail-1',
    name: '癸号暗影',
    description: '癸号失败因子如影随形。',
    type: 'risk',
    cost: 0,
    effect: { mergeValue: 35, failGui: 25, riskYin: 15 },
  },
];

export const stageConfigs: Record<string, StageConfig> = {
  yin: {
    id: 'yin',
    name: '寅局 · 启蒙',
    description: '教学局：熟悉银盐暗房的基本操作，学习归并值、点亮槽、巡测痕的概念。',
    initialMergeValue: 10,
    slotCount: 5,
    initialLitSlots: 1,
    patrolStart: 0,
    patrolSpeed: 1,
    riskYinThreshold: 50,
    rewardDingThreshold: 30,
    failGuiThreshold: 60,
    winCondition: {
      type: 'merge-value',
      target: 100,
    },
    maxSteps: 15,
    eventPool: yinEvents,
    eventsPerStep: 3,
  },
  ding: {
    id: 'ding',
    name: '丁局 · 匮乏',
    description: '资源短缺局：事件消耗更高，需要精打细算，合理利用丁号奖励度过难关。',
    initialMergeValue: 5,
    slotCount: 6,
    initialLitSlots: 0,
    patrolStart: 0,
    patrolSpeed: 1,
    riskYinThreshold: 40,
    rewardDingThreshold: 50,
    failGuiThreshold: 50,
    winCondition: {
      type: 'all-lit',
      target: 6,
    },
    maxSteps: 20,
    eventPool: dingEvents,
    eventsPerStep: 3,
  },
  gui: {
    id: 'gui',
    name: '癸局 · 秘境',
    description: '隐藏条件局：存在隐藏胜利条件，探索癸号密钥，发现暗房的真正秘密。',
    initialMergeValue: 15,
    slotCount: 7,
    initialLitSlots: 2,
    patrolStart: 3,
    patrolSpeed: 1,
    riskYinThreshold: 45,
    rewardDingThreshold: 40,
    failGuiThreshold: 55,
    winCondition: {
      type: 'merge-value',
      target: 150,
    },
    maxSteps: 25,
    eventPool: guiEvents,
    eventsPerStep: 4,
    hiddenCondition: {
      type: 'no-risk',
      value: 0,
    },
  },
};

export function getStageConfig(stageId: string): StageConfig | undefined {
  return stageConfigs[stageId];
}
