import type { Book, Customer } from '~/types/game';

export const seedBooks: Omit<Book, 'id'>[] = [
  {
    title: '《活着》',
    author: '余华',
    publishYear: 1993,
    condition: 'good',
    conditionDesc: '精装版，书脊有轻微磨损，内页干净无笔记',
    hasInscription: true,
    inscription: '赠予吾友，愿你在苦难中仍能感受生命的温度。——余华 1994年春',
    hasSeal: true,
    sealName: '文轩藏书',
    sealOwner: '知名文学收藏家 李文轩',
    isRare: true,
    rarityLevel: 'first_edition',
    rarityDesc: '作家出版社初版精装本，仅印5000册',
    basePrice: 120,
    actualValue: 380,
    category: '文学',
    coverImage: null,
  },
  {
    title: '《人类简史》',
    author: '尤瓦尔·赫拉利',
    publishYear: 2014,
    condition: 'excellent',
    conditionDesc: '几乎全新，仅翻阅过一次，书角完好',
    hasInscription: false,
    inscription: null,
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: false,
    rarityLevel: 'common',
    rarityDesc: '普通流通版本，印量较大',
    basePrice: 68,
    actualValue: 88,
    category: '历史',
    coverImage: null,
  },
  {
    title: '《万历十五年》',
    author: '黄仁宇',
    publishYear: 1982,
    condition: 'fair',
    conditionDesc: '平装本，封面有折痕，内页有少量铅笔笔记可擦除',
    hasInscription: false,
    inscription: null,
    hasSeal: true,
    sealName: '求真斋',
    sealOwner: '私人收藏家 王健',
    isRare: true,
    rarityLevel: 'out_of_print',
    rarityDesc: '中华书局首版，已绝版多年',
    basePrice: 80,
    actualValue: 280,
    category: '历史',
    coverImage: null,
  },
  {
    title: '《存在与时间》',
    author: '马丁·海德格尔',
    publishYear: 1987,
    condition: 'poor',
    conditionDesc: '封面破损，书脊松动，内页有黄斑但完整',
    hasInscription: true,
    inscription: '哲学的道路是漫长的，愿此书能伴你走过一段。——陈嘉映 译序',
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: true,
    rarityLevel: 'rare',
    rarityDesc: '国内首个中译本，由陈嘉映、王庆节合译',
    basePrice: 95,
    actualValue: 220,
    category: '哲学',
    coverImage: null,
  },
  {
    title: '《三体》',
    author: '刘慈欣',
    publishYear: 2008,
    condition: 'good',
    conditionDesc: '平装本，有轻微阅读痕迹，无笔记',
    hasInscription: false,
    inscription: null,
    hasSeal: true,
    sealName: '科幻迷俱乐部',
    sealOwner: '科幻收藏协会',
    isRare: true,
    rarityLevel: 'first_edition',
    rarityDesc: '重庆出版社初版，科幻文学里程碑之作',
    basePrice: 75,
    actualValue: 180,
    category: '科幻',
    coverImage: null,
  },
  {
    title: '《百年孤独》',
    author: '加西亚·马尔克斯',
    publishYear: 1984,
    condition: 'fair',
    conditionDesc: '书脊有胶带修复，内页完整，有少量读者批注',
    hasInscription: false,
    inscription: null,
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: true,
    rarityLevel: 'out_of_print',
    rarityDesc: '国内首个授权中译本，已绝版',
    basePrice: 110,
    actualValue: 320,
    category: '文学',
    coverImage: null,
  },
  {
    title: '《小王子》',
    author: '安托万·德·圣-埃克苏佩里',
    publishYear: 2000,
    condition: 'excellent',
    conditionDesc: '精装插图版，品相完美，带原装书盒',
    hasInscription: true,
    inscription: '送给我最爱的小侄女，愿你永远保持童心。——姑姑 2001年',
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: false,
    rarityLevel: 'common',
    rarityDesc: '常见精装版本',
    basePrice: 45,
    actualValue: 60,
    category: '文学',
    coverImage: null,
  },
  {
    title: '《中国哲学史》',
    author: '冯友兰',
    publishYear: 1961,
    condition: 'poor',
    conditionDesc: '布面精装，封面褪色，内页有虫蛀但不影响阅读',
    hasInscription: false,
    inscription: null,
    hasSeal: true,
    sealName: '北京大学图书馆',
    sealOwner: '北京大学图书馆（旧藏流出）',
    isRare: true,
    rarityLevel: 'out_of_print',
    rarityDesc: '中华书局老版本，建国后首次修订版',
    basePrice: 150,
    actualValue: 450,
    category: '哲学',
    coverImage: null,
  },
  {
    title: '《摄影美学》',
    author: '阮义忠',
    publishYear: 1998,
    condition: 'good',
    conditionDesc: '图文并茂，铜版纸印刷，有少量读者划线',
    hasInscription: false,
    inscription: null,
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: false,
    rarityLevel: 'uncommon',
    rarityDesc: '摄影家签名版',
    basePrice: 85,
    actualValue: 130,
    category: '艺术',
    coverImage: null,
  },
  {
    title: '《红楼梦》',
    author: '曹雪芹',
    publishYear: 1959,
    condition: 'fair',
    conditionDesc: '人民文学出版社程乙本，四册全，有藏书者印章',
    hasInscription: false,
    inscription: null,
    hasSeal: true,
    sealName: '脂砚斋',
    sealOwner: '知名红学家 周汝昌（旧藏）',
    isRare: true,
    rarityLevel: 'out_of_print',
    rarityDesc: '建国后首个整理本，启功注释',
    basePrice: 200,
    actualValue: 680,
    category: '文学',
    coverImage: null,
  },
  {
    title: '《思考，快与慢》',
    author: '丹尼尔·卡尼曼',
    publishYear: 2012,
    condition: 'good',
    conditionDesc: '精装版，内页有少量阅读笔记',
    hasInscription: false,
    inscription: null,
    hasSeal: false,
    sealName: null,
    sealOwner: null,
    isRare: false,
    rarityLevel: 'common',
    rarityDesc: '诺贝尔经济学奖得主著作，普及版',
    basePrice: 69,
    actualValue: 85,
    category: '思想',
    coverImage: null,
  },
  {
    title: '《梵高传》',
    author: '欧文·斯通',
    publishYear: 1985,
    condition: 'fair',
    conditionDesc: '传记文学经典，附有梵高作品插图，封底有水渍',
    hasInscription: true,
    inscription: '愿你如梵高般热爱生命。——父赠 1986年',
    hasSeal: true,
    sealName: '向日葵书屋',
    sealOwner: '艺术爱好者 林雨',
    isRare: true,
    rarityLevel: 'rare',
    rarityDesc: '国内首个全译本，已绝版',
    basePrice: 70,
    actualValue: 195,
    category: '艺术',
    coverImage: null,
  },
];

export const seedCustomers: Omit<Customer, 'id'>[] = [
  {
    name: '陈教授',
    avatar: '👨‍🏫',
    preferences: ['历史', '哲学', '文学', '绝版'],
    budgetRange: [200, 600],
    personality: 'collector',
    tolerance: 0.25,
  },
  {
    name: '小王同学',
    avatar: '👨‍🎓',
    preferences: ['科幻', '文学', '思想'],
    budgetRange: [50, 150],
    personality: 'casual',
    tolerance: 0.15,
  },
  {
    name: '李阿姨',
    avatar: '👩',
    preferences: ['文学', '艺术', '签名'],
    budgetRange: [80, 250],
    personality: 'bargain_hunter',
    tolerance: 0.1,
  },
  {
    name: '张老板',
    avatar: '👨‍💼',
    preferences: ['绝版', '初版', '藏书章', '历史'],
    budgetRange: [300, 800],
    personality: 'serious',
    tolerance: 0.35,
  },
  {
    name: '林小姐',
    avatar: '👩‍🎨',
    preferences: ['艺术', '文学', '插图', '签名'],
    budgetRange: [100, 300],
    personality: 'casual',
    tolerance: 0.2,
  },
  {
    name: '周老先生',
    avatar: '👴',
    preferences: ['哲学', '历史', '民国', '绝版'],
    budgetRange: [150, 500],
    personality: 'collector',
    tolerance: 0.3,
  },
];

export interface SeedScenario {
  name: string;
  description: string;
  scenarioType: 'overpriced_overstock' | 'underpriced_lost_profit' | 'ledger_rollback';
  books: string[];
  customerName: string;
  playerPrice: number;
  expectedStatus: string;
  expectedScore: string;
}

export const seedScenarios: SeedScenario[] = [
  {
    name: '样本1：定价过高导致积压',
    description: '玩家对普通流通书籍定价过高，远超市场预期，导致书籍积压无法售出',
    scenarioType: 'overpriced_overstock',
    books: ['《人类简史》', '《小王子》', '《思考，快与慢》'],
    customerName: '小王同学',
    playerPrice: 350,
    expectedStatus: 'overstock',
    expectedScore: '扣分，利润损失',
  },
  {
    name: '样本2：定价过低损失稀缺书利润（触发异常）',
    description: '玩家未能识别绝版书籍的价值，定价过低导致利润大幅流失，触发稀缺书利润损失异常',
    scenarioType: 'underpriced_lost_profit',
    books: ['《红楼梦》', '《万历十五年》', '《百年孤独》'],
    customerName: '张老板',
    playerPrice: 400,
    expectedStatus: 'sold',
    expectedScore: '销售成功但利润损失严重，有扣分',
  },
  {
    name: '样本3：进货台账需要回滚或重算',
    description: '进货时账目记录有误，需要执行回滚操作并重新计算成本和分数',
    scenarioType: 'ledger_rollback',
    books: ['《活着》', '《存在与时间》', '《中国哲学史》'],
    customerName: '陈教授',
    playerPrice: 680,
    expectedStatus: 'sold',
    expectedScore: '需要回滚错误的进货记录后重新计算',
  },
];
