# Generated by Django 5.0.14 on 2026-06-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('condition_out', models.CharField(choices=[('excellent', '完好'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('damaged', '有损伤')], default='good', max_length=20, verbose_name='出库状况')),
                ('condition_out_notes', models.TextField(blank=True, verbose_name='出库状况说明')),
                ('condition_in', models.CharField(blank=True, choices=[('excellent', '完好'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('damaged', '有损伤')], max_length=20, null=True, verbose_name='归还状况')),
                ('condition_in_notes', models.TextField(blank=True, verbose_name='归还状况说明')),
                ('reader_signature', models.CharField(blank=True, max_length=50, verbose_name='读者签收')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_logs', to='catalog.rarebook', verbose_name='珍本')),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulation_handled', to=settings.AUTH_USER_MODEL, verbose_name='经手馆员')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_log', to='reservations.reservation', verbose_name='预约记录')),
                ('return_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_received', to=settings.AUTH_USER_MODEL, verbose_name='归还接收人')),
            ],
            options={
                'verbose_name': '流通记录',
                'verbose_name_plural': '流通记录',
                'ordering': ['-checkout_time'],
            },
        ),
    ]
