# Generated by Django 5.0.6 on 2026-06-09 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='片区名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='片区编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '片区',
                'verbose_name_plural': '片区',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间')),
                ('status', models.CharField(choices=[('normal', '正常'), ('partial', '部分清运'), ('missed', '漏收')], default='normal', max_length=20, verbose_name='签到状态')),
                ('waste_weight', models.FloatField(blank=True, null=True, verbose_name='清运重量(kg)')),
                ('photo_url', models.URLField(blank=True, verbose_name='现场照片')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL, verbose_name='签到司机')),
            ],
            options={
                'verbose_name': '站点签到',
                'verbose_name_plural': '站点签到',
                'ordering': ['check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=100, verbose_name='投诉人')),
                ('complainant_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('complaint_type', models.CharField(choices=[('overflow', '垃圾桶满溢'), ('missed_collection', '漏收投诉'), ('odor', '异味投诉'), ('other', '其他投诉')], default='overflow', max_length=30, verbose_name='投诉类型')),
                ('description', models.TextField(verbose_name='投诉描述')),
                ('photo_evidence', models.URLField(blank=True, verbose_name='投诉照片')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投诉时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('in_progress', '整改中'), ('resolved', '已解决'), ('closed', '已结案')], default='pending', max_length=20, verbose_name='处理状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_notes', models.TextField(blank=True, verbose_name='确认意见')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='解决说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL, verbose_name='处理巡检员')),
            ],
            options={
                'verbose_name': '投诉记录',
                'verbose_name_plural': '投诉记录',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='路线编码')),
                ('estimated_duration', models.DurationField(help_text='格式：HH:MM:SS', verbose_name='预计时长')),
                ('distance_km', models.FloatField(default=0, verbose_name='里程(公里)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='路线描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='operations.district', verbose_name='所属片区')),
            ],
            options={
                'verbose_name': '清运路线',
                'verbose_name_plural': '清运路线',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='派车日期')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='计划发车时间')),
                ('status', models.CharField(choices=[('pending', '待出发'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停'), ('failed', '任务失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际发车时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_assignments', to=settings.AUTH_USER_MODEL, verbose_name='调度员')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to=settings.AUTH_USER_MODEL, verbose_name='司机')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '路线分派',
                'verbose_name_plural': '路线分派',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_result', models.CharField(choices=[('pass', '通过'), ('needs_rectification', '需整改'), ('rectified', '已整改')], default='pass', max_length=30, verbose_name='复核结果')),
                ('review_notes', models.TextField(verbose_name='复核意见')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='复核时间')),
                ('rectification_deadline', models.DateTimeField(blank=True, null=True, verbose_name='整改期限')),
                ('rectification_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='整改完成时间')),
                ('rectification_notes', models.TextField(blank=True, verbose_name='整改说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='operations.checkin', verbose_name='关联签到')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='operations.complaint', verbose_name='关联投诉')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核主管')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='operations.routeassignment', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='operations.routeassignment', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='operations.routeassignment', verbose_name='路线任务'),
        ),
        migrations.CreateModel(
            name='RouteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assigned', '任务分派'), ('started', '开始作业'), ('check_in', '站点签到'), ('fault_reported', '故障上报'), ('complaint_received', '收到投诉'), ('complaint_confirmed', '投诉确认'), ('review', '复核记录'), ('reassigned', '车辆改派'), ('suspended', '任务暂停'), ('resumed', '任务恢复'), ('completed', '任务完成'), ('failed', '任务失败')], max_length=30, verbose_name='事件类型')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.routeassignment', verbose_name='路线任务')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '路线事件',
                'verbose_name_plural': '路线事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('order', models.IntegerField(default=0, verbose_name='站点顺序')),
                ('bin_count', models.IntegerField(default=1, verbose_name='垃圾桶数量')),
                ('bin_capacity', models.FloatField(default=240, verbose_name='单桶容量(L)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='operations.route', verbose_name='所属路线')),
            ],
            options={
                'verbose_name': '清运站点',
                'verbose_name_plural': '清运站点',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='operations.station', verbose_name='站点'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='operations.station', verbose_name='站点'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='车型')),
                ('capacity', models.FloatField(verbose_name='载重(吨)')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_service', '作业中'), ('maintenance', '维保中'), ('faulty', '故障')], default='available', max_length=20, verbose_name='状态')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维保日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='operations.district', verbose_name='所属片区')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='固定司机')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'ordering': ['plate_number'],
            },
        ),
        migrations.AddField(
            model_name='routeassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.vehicle', verbose_name='车辆'),
        ),
        migrations.CreateModel(
            name='VehicleFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上报时间')),
                ('fault_type', models.CharField(max_length=100, verbose_name='故障类型')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('moderate', '中等'), ('severe', '严重')], default='moderate', max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('being_repaired', '维修中'), ('resolved', '已解决')], default='reported', max_length=20, verbose_name='处理状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='operations.routeassignment', verbose_name='关联任务')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_faults', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='operations.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆故障',
                'verbose_name_plural': '车辆故障',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('assignment', 'station')},
        ),
    ]
