# Generated by Django 5.0.6 on 2026-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', '任务分派'), ('started', '开始作业'), ('check_in', '站点签到'), ('fault_reported', '故障上报'), ('complaint_received', '收到投诉'), ('complaint_confirmed', '投诉确认'), ('complaint_resolved', '投诉整改完成'), ('complaint_closed', '投诉结案'), ('review', '复核记录'), ('reassigned', '车辆改派'), ('suspended', '任务暂停'), ('resumed', '任务恢复'), ('completed', '任务完成'), ('failed', '任务失败')], max_length=30, verbose_name='事件类型'),
        ),
    ]
