# Generated by Django 5.2.15 on 2026-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.CharField(max_length=50, verbose_name='统计类型')),
                ('dimension', models.CharField(max_length=100, verbose_name='统计维度')),
                ('value', models.CharField(max_length=200, verbose_name='维度值')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统计数据',
                'verbose_name_plural': '统计数据',
                'unique_together': {('statistic_type', 'dimension', 'value')},
            },
        ),
    ]
