# Generated by Django 5.2.15 on 2026-06-17 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=40, unique=True, verbose_name='批次号')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('operator', models.CharField(max_length=60, verbose_name='操作员')),
                ('lab_location', models.CharField(blank=True, max_length=120, verbose_name='实验室地点')),
                ('temperature_env', models.FloatField(blank=True, null=True, verbose_name='环境温度(°C)')),
                ('humidity_env', models.FloatField(blank=True, null=True, verbose_name='环境湿度(%RH)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='已作废')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '校准批次',
                'verbose_name_plural': '校准批次',
                'ordering': ['-calibration_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('temperature', '温度仪'), ('humidity', '湿度仪'), ('wind_speed', '风速仪'), ('wind_direction', '风向仪'), ('barometer', '气压仪'), ('rain_gauge', '雨量计')], max_length=20, verbose_name='仪器类型')),
                ('model_name', models.CharField(max_length=80, verbose_name='型号')),
                ('serial_number', models.CharField(max_length=60, unique=True, verbose_name='序列号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='制造商')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('status', models.CharField(choices=[('normal', '正常'), ('needs_calibration', '待校准'), ('calibrating', '校准中'), ('faulty', '故障'), ('retired', '退役')], default='normal', max_length=20, verbose_name='仪器状态')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='上次校准日期')),
                ('next_calibration_due', models.DateField(blank=True, null=True, verbose_name='下次校准到期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪器',
                'verbose_name_plural': '仪器',
                'ordering': ['instrument_type', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='站名')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='站点编号')),
                ('altitude', models.FloatField(verbose_name='海拔(m)')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('region', models.CharField(choices=[('qinghai', '青海'), ('tibet', '西藏'), ('sichuan', '四川'), ('yunnan', '云南'), ('gansu', '甘肃'), ('xinjiang', '新疆')], max_length=20, verbose_name='所属区域')),
                ('status', models.CharField(choices=[('active', '运行中'), ('maintenance', '维护中'), ('offline', '离线'), ('decommissioned', '已退役')], default='active', max_length=20, verbose_name='运行状态')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='建站日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '气象站',
                'verbose_name_plural': '气象站',
                'ordering': ['-altitude'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_point', models.CharField(help_text='如: -20°C, 50%RH, 10m/s', max_length=60, verbose_name='测试点')),
                ('before_value', models.FloatField(verbose_name='校准前读数')),
                ('after_value', models.FloatField(verbose_name='校准后读数')),
                ('standard_value', models.FloatField(blank=True, null=True, verbose_name='标准值')),
                ('deviation_before', models.FloatField(blank=True, null=True, verbose_name='校准前偏差')),
                ('deviation_after', models.FloatField(blank=True, null=True, verbose_name='校准后偏差')),
                ('tolerance', models.FloatField(blank=True, null=True, verbose_name='允许误差')),
                ('result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('conditional', '有条件合格')], max_length=15, verbose_name='校准结果')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='异常标记')),
                ('anomaly_note', models.TextField(blank=True, verbose_name='异常说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='calibration.calibrationbatch', verbose_name='校准批次')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='calibration.instrument', verbose_name='仪器')),
            ],
            options={
                'verbose_name': '校准记录',
                'verbose_name_plural': '校准记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='证书编号')),
                ('issued_date', models.DateField(verbose_name='签发日期')),
                ('expiry_date', models.DateField(verbose_name='有效期至')),
                ('issued_by', models.CharField(max_length=120, verbose_name='签发机构')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='calibration.calibrationrecord', verbose_name='校准记录')),
            ],
            options={
                'verbose_name': '校准证书',
                'verbose_name_plural': '校准证书',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='calibration.station', verbose_name='所属站点'),
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_date', models.DateField(verbose_name='运输日期')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='到达日期')),
                ('method', models.CharField(blank=True, max_length=40, verbose_name='运输方式')),
                ('impact_score', models.FloatField(blank=True, help_text='0-10, 0=无影响, 10=严重损坏', null=True, verbose_name='运输影响评分')),
                ('pre_transport_reading', models.FloatField(blank=True, null=True, verbose_name='运输前读数')),
                ('post_transport_reading', models.FloatField(blank=True, null=True, verbose_name='运输后读数')),
                ('reading_deviation', models.FloatField(blank=True, null=True, verbose_name='读数偏差')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports_from', to='calibration.station', verbose_name='出发站')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to='calibration.instrument', verbose_name='仪器')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports_to', to='calibration.station', verbose_name='目的站')),
            ],
            options={
                'verbose_name': '运输记录',
                'verbose_name_plural': '运输记录',
                'ordering': ['-transport_date'],
            },
        ),
    ]
