# Generated by Django 5.2.15 on 2026-06-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationbatch',
            name='batch_number',
            field=models.CharField(max_length=40, verbose_name='批次号'),
        ),
        migrations.AlterUniqueTogether(
            name='calibrationbatch',
            unique_together={('batch_number', 'version')},
        ),
    ]
