# Generated by Django 5.0.6 on 2026-06-09 08:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='点位编号')),
                ('name', models.CharField(max_length=100, verbose_name='点位名称')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('location_type', models.CharField(choices=[('rooftop', '楼顶'), ('wall', '墙面'), ('standalone', '单立柱'), ('bus_stop', '公交站亭'), ('subway', '地铁站')], max_length=20, verbose_name='点位类型')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='安装高度(米)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='广告牌宽度(米)')),
                ('height_dim', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='广告牌高度(米)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='点位描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '广告牌点位',
                'verbose_name_plural': '广告牌点位',
                'ordering': ['city', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '施工人员',
                'verbose_name_plural': '施工人员',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('constructor', '施工队'), ('project_manager', '项目经理'), ('safety_officer', '安全员'), ('acceptor', '验收人'), ('admin', '系统管理员')], default='constructor', max_length=20, verbose_name='角色')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=30, unique=True, verbose_name='计划编号')),
                ('title', models.CharField(max_length=200, verbose_name='施工计划标题')),
                ('planned_start_date', models.DateField(verbose_name='计划开工日期')),
                ('planned_end_date', models.DateField(verbose_name='计划完工日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开工日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际完工日期')),
                ('construction_content', models.TextField(verbose_name='施工内容')),
                ('materials', models.TextField(blank=True, verbose_name='主要材料清单')),
                ('safety_measures', models.TextField(blank=True, verbose_name='安全措施')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预算金额(元)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('pm_reviewing', '项目经理审核中'), ('pm_rejected', '项目经理退回'), ('pm_approved', '项目经理通过'), ('safety_reviewing', '安全员审核中'), ('safety_rejected', '安全员退回'), ('safety_approved', '安全员通过'), ('ready', '待开工'), ('in_progress', '施工中'), ('completed', '已完工待验收'), ('acceptance_rejected', '验收退回'), ('accepted', '已验收归档'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('rework_count', models.IntegerField(default=0, verbose_name='返工次数')),
                ('has_delay', models.BooleanField(default=False, verbose_name='是否有延期')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('accept_time', models.DateTimeField(blank=True, null=True, verbose_name='验收归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('constructor_team', models.ForeignKey(limit_choices_to={'role': 'constructor'}, on_delete=django.db.models.deletion.PROTECT, related_name='construction_plans', to=settings.AUTH_USER_MODEL, verbose_name='施工队')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.billboardlocation', verbose_name='施工点位')),
                ('project_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'project_manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_plans', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
                ('safety_officer', models.ForeignKey(blank=True, limit_choices_to={'role': 'safety_officer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_plans', to=settings.AUTH_USER_MODEL, verbose_name='安全员')),
            ],
            options={
                'verbose_name': '施工计划',
                'verbose_name_plural': '施工计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('submit', '提交计划'), ('pm_review', '项目经理审核'), ('safety_review', '安全员审核'), ('start_work', '确认开工'), ('complete', '施工完成'), ('acceptance', '验收归档'), ('rework', '退回返工'), ('delay', '延期申请')], max_length=20, verbose_name='节点类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '通过'), ('rejected', '驳回/退回'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='处理结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='construction.constructionplan', verbose_name='施工计划')),
            ],
            options={
                'verbose_name': '审核节点',
                'verbose_name_plural': '审核节点',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_type', models.CharField(choices=[('wind', '大风天气'), ('rain', '降雨天气'), ('material', '材料问题'), ('personnel', '人员问题'), ('site_issue', '现场问题'), ('other', '其他')], max_length=20, verbose_name='延期原因')),
                ('delay_days', models.IntegerField(verbose_name='延期天数')),
                ('original_date', models.DateField(verbose_name='原定日期')),
                ('new_date', models.DateField(verbose_name='延期后日期')),
                ('reason', models.TextField(verbose_name='延期说明')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='是否批准')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='construction.constructionplan', verbose_name='施工计划')),
            ],
            options={
                'verbose_name': '延期记录',
                'verbose_name_plural': '延期记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('high_altitude', '高空作业证'), ('electrician', '电工证'), ('welding', '焊工证'), ('lifting', '起重作业证'), ('safety', '安全员证')], max_length=20, verbose_name='证书类型')),
                ('cert_no', models.CharField(max_length=50, verbose_name='证书编号')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
                ('expiry_date', models.DateField(verbose_name='到期日期')),
                ('issuing_authority', models.CharField(blank=True, max_length=100, verbose_name='发证机关')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.worker', verbose_name='施工人员')),
            ],
            options={
                'verbose_name': '资质证书',
                'verbose_name_plural': '资质证书',
                'ordering': ['worker', 'cert_type'],
            },
        ),
        migrations.CreateModel(
            name='PlanWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='岗位')),
                ('is_lead', models.BooleanField(default=False, verbose_name='是否负责人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.constructionplan', verbose_name='施工计划')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.worker', verbose_name='施工人员')),
            ],
            options={
                'verbose_name': '计划施工人员',
                'verbose_name_plural': '计划施工人员',
                'unique_together': {('plan', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='constructionplan',
            name='workers',
            field=models.ManyToManyField(through='construction.PlanWorker', to='construction.worker', verbose_name='施工人员'),
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('weather', models.CharField(choices=[('sunny', '晴'), ('cloudy', '多云'), ('overcast', '阴'), ('rain', '雨'), ('snow', '雪'), ('fog', '雾'), ('thunderstorm', '雷阵雨')], max_length=20, verbose_name='天气状况')),
                ('temperature_high', models.IntegerField(blank=True, null=True, verbose_name='最高温度(℃)')),
                ('temperature_low', models.IntegerField(blank=True, null=True, verbose_name='最低温度(℃)')),
                ('wind_level', models.IntegerField(choices=[(0, '0级（无风）'), (1, '1级（软风）'), (2, '2级（轻风）'), (3, '3级（微风）'), (4, '4级（和风）'), (5, '5级（清劲风）'), (6, '6级（强风）'), (7, '7级（疾风）'), (8, '8级（大风）'), (9, '9级（烈风）'), (10, '10级（狂风）')], default=0, verbose_name='风力等级')),
                ('wind_speed', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='风速(m/s)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, verbose_name='风向')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='湿度(%)')),
                ('has_wind_warning', models.BooleanField(default=False, verbose_name='是否大风预警')),
                ('warning_level', models.CharField(blank=True, max_length=20, verbose_name='预警级别')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.billboardlocation', verbose_name='点位')),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'ordering': ['-record_date'],
                'unique_together': {('location', 'record_date')},
            },
        ),
    ]
