# Generated by Django 6.0.5 on 2026-06-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='快递单号')),
                ('sender_name', models.CharField(max_length=50, verbose_name='寄件人')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='寄件人电话')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收件人')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('status', models.CharField(choices=[('checked_in', '已入站'), ('pending_pickup', '待取件'), ('picked_up', '已取件'), ('retention', '滞留'), ('abnormal', '异常'), ('returned', '已退回')], default='checked_in', max_length=20, verbose_name='状态')),
                ('shelf_code', models.CharField(blank=True, default='', max_length=20, verbose_name='货架编码')),
                ('carrier', models.CharField(choices=[('sf', '顺丰'), ('yt', '圆通'), ('zt', '中通'), ('st', '申通'), ('yd', '韵达'), ('ems', 'EMS'), ('jd', '京东'), ('other', '其他')], default='other', max_length=20, verbose_name='快递公司')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='入站时间')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='取件时间')),
                ('picked_up_by_name', models.CharField(blank=True, default='', max_length=50, verbose_name='取件人姓名')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '包裹',
                'verbose_name_plural': '包裹',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='驿站名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='驿站编码')),
                ('address', models.TextField(verbose_name='地址')),
                ('district', models.CharField(max_length=50, verbose_name='所属片区')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '驿站',
                'verbose_name_plural': '驿站',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=30, unique=True, verbose_name='投诉编号')),
                ('complainant_name', models.CharField(max_length=50, verbose_name='投诉人姓名')),
                ('complainant_phone', models.CharField(max_length=20, verbose_name='投诉人电话')),
                ('complaint_type', models.CharField(choices=[('delayed_pickup', '取件延迟'), ('damaged', '包裹破损'), ('lost', '包裹丢失'), ('poor_service', '服务态度差'), ('wrong_item', '错件'), ('other', '其他')], default='other', max_length=20, verbose_name='投诉类型')),
                ('description', models.TextField(verbose_name='投诉内容')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('accepted', '已受理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投诉时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('satisfaction', models.IntegerField(blank=True, null=True, verbose_name='满意度评分(1-5)')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='depot.package', verbose_name='关联包裹')),
            ],
            options={
                'verbose_name': '客户投诉',
                'verbose_name_plural': '客户投诉',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(choices=[('clerk', '店员'), ('supervisor', '片区主管'), ('cs_specialist', '客服专员')], default='clerk', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.station', verbose_name='所属驿站')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('retention_expired', '滞留超期'), ('customer_request', '客户要求退回'), ('wrong_station', '错分驿站'), ('damaged', '破损退回'), ('rejected', '拒收退回'), ('other', '其他')], default='other', max_length=20, verbose_name='退回原因')),
                ('returned_to', models.CharField(max_length=200, verbose_name='退回目的地')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='退回时间')),
                ('return_carrier', models.CharField(blank=True, default='', max_length=50, verbose_name='退回承运商')),
                ('return_tracking', models.CharField(blank=True, default='', max_length=50, verbose_name='退回单号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_records', to='depot.package', verbose_name='包裹')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.staff', verbose_name='退回操作员')),
            ],
            options={
                'verbose_name': '退回记录',
                'verbose_name_plural': '退回记录',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('warning', '预警(3天)'), ('critical', '严重(5天)'), ('urgent', '紧急(7天+)')], default='warning', max_length=20, verbose_name='预警等级')),
                ('days_retained', models.IntegerField(verbose_name='滞留天数')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='处理说明')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_alerts', to='depot.package', verbose_name='包裹')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='depot.staff', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '滞留预警',
                'verbose_name_plural': '滞留预警',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_type', models.CharField(choices=[('full', '全责'), ('partial', '部分责任'), ('none', '无责任')], default='partial', max_length=20, verbose_name='责任类型')),
                ('penalty_type', models.CharField(choices=[('warning', '警告'), ('fine', '罚款'), ('training', '培训'), ('demotion', '降级'), ('none', '无处罚')], default='warning', max_length=20, verbose_name='处罚类型')),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='罚款金额')),
                ('description', models.TextField(verbose_name='责任说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('executed', '已执行'), ('appealed', '已申诉')], default='pending', max_length=20, verbose_name='状态')),
                ('appeal_note', models.TextField(blank=True, default='', verbose_name='申诉说明')),
                ('appeal_at', models.DateTimeField(blank=True, null=True, verbose_name='申诉时间')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='depot.complaint', verbose_name='关联投诉')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_responsibilities', to='depot.staff', verbose_name='创建人')),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='depot.staff', verbose_name='责任人')),
            ],
            options={
                'verbose_name': '责任处理',
                'verbose_name_plural': '责任处理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('sms', '短信'), ('call', '电话'), ('app_notify', 'APP通知')], default='sms', max_length=20, verbose_name='提醒方式')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('delivered', '已送达'), ('failed', '发送失败')], default='sent', max_length=20, verbose_name='发送状态')),
                ('response', models.CharField(blank=True, choices=[('no_response', '无回应'), ('confirmed_pickup', '确认取件'), ('delayed_pickup', '延迟取件'), ('rejected', '拒收')], default='', max_length=20, verbose_name='客户回应')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='depot.package', verbose_name='包裹')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.staff', verbose_name='发送人')),
            ],
            options={
                'verbose_name': '取件提醒',
                'verbose_name_plural': '取件提醒',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_packages', to='depot.staff', verbose_name='入站操作员'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_complaints', to='depot.staff', verbose_name='受理人'),
        ),
        migrations.CreateModel(
            name='AbnormalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_type', models.CharField(choices=[('damaged', '破损'), ('lost', '丢失'), ('wrong_station', '错分驿站'), ('expired', '超期'), ('wrong_item', '错件'), ('other', '其他')], default='other', max_length=20, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='处理状态')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_records', to='depot.package', verbose_name='包裹')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_abnormals', to='depot.staff', verbose_name='登记人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_abnormals', to='depot.staff', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '异常件',
                'verbose_name_plural': '异常件',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.station', verbose_name='所属驿站'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.station', verbose_name='涉事驿站'),
        ),
    ]
