# Generated by Django 6.0.5 on 2026-06-01 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入站时间'),
        ),
    ]
