# Generated by Django 6.0.5 on 2026-06-01 13:33

from django.db import migrations, models


def migrate_empty_responses(apps, schema_editor):
    PickupReminder = apps.get_model("depot", "PickupReminder")
    PickupReminder.objects.filter(response="").update(response="no_response")


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_package_checked_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupreminder',
            name='response',
            field=models.CharField(blank=True, choices=[('no_response', '无回应'), ('confirmed_pickup', '确认取件'), ('delayed_pickup', '延迟取件'), ('rejected', '拒收')], default='no_response', max_length=20, verbose_name='客户回应'),
        ),
        migrations.RunPython(migrate_empty_responses),
    ]
