# Generated by Django 5.1.15 on 2026-06-02 07:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='器械包编号')),
                ('name', models.CharField(max_length=200, verbose_name='器械包名称')),
                ('category', models.CharField(choices=[('surgical', '手术包'), ('treatment', '诊疗包'), ('examination', '检查包')], default='treatment', max_length=20, verbose_name='分类')),
                ('contents', models.TextField(help_text='每行一项器械名称', verbose_name='包含器械清单')),
                ('status', models.CharField(choices=[('registered', '在库'), ('in_use', '使用中'), ('cleaning', '清洗中'), ('sterilizing', '灭菌中'), ('pending_release', '待放行'), ('expired', '已过期'), ('recalled', '已召回')], default='registered', max_length=20, verbose_name='当前状态')),
                ('clinic', models.CharField(blank=True, default='', max_length=100, verbose_name='所属诊室')),
                ('sterilization_expiry_days', models.PositiveIntegerField(default=180, verbose_name='灭菌有效期(天)')),
                ('last_sterilized_at', models.DateTimeField(blank=True, null=True, verbose_name='最近灭菌时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '器械包',
                'verbose_name_plural': '器械包',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryRecall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('expired', '过期召回'), ('suspected_contamination', '可疑污染'), ('batch_issue', '批次问题'), ('other', '其他')], max_length=30, verbose_name='召回原因')),
                ('initiator', models.CharField(max_length=100, verbose_name='发起人')),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发起时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('recalled', '已召回'), ('destroyed', '已销毁')], default='pending', max_length=20, verbose_name='召回状态')),
                ('handler', models.CharField(blank=True, default='', max_length=100, verbose_name='处理人')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='tracker.instrumentpackage', verbose_name='器械包')),
            ],
            options={
                'verbose_name': '过期召回',
                'verbose_name_plural': '过期召回',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=100, verbose_name='患者编号')),
                ('patient_name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('doctor', models.CharField(max_length=100, verbose_name='使用医生')),
                ('clinic', models.CharField(max_length=100, verbose_name='使用诊室')),
                ('procedure', models.CharField(max_length=200, verbose_name='诊疗项目')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='使用时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_usages', to='tracker.instrumentpackage', verbose_name='器械包')),
            ],
            options={
                'verbose_name': '诊疗使用记录',
                'verbose_name_plural': '诊疗使用记录',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('manual', '手工清洗'), ('ultrasonic', '超声清洗'), ('mechanical', '机械清洗')], max_length=20, verbose_name='清洗方式')),
                ('cleaning_agent', models.CharField(blank=True, default='', max_length=200, verbose_name='清洗剂')),
                ('cleaner', models.CharField(max_length=100, verbose_name='清洗人')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格')], default='qualified', max_length=20, verbose_name='清洗结果')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='tracker.instrumentpackage', verbose_name='器械包')),
            ],
            options={
                'verbose_name': '清洗记录',
                'verbose_name_plural': '清洗记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SterilizationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('method', models.CharField(choices=[('high_pressure_steam', '高压蒸汽灭菌'), ('eto', '环氧乙烷灭菌'), ('low_temp_plasma', '低温等离子灭菌')], max_length=30, verbose_name='灭菌方式')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='灭菌温度(℃)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='灭菌压力(kPa)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='灭菌时长(分钟)')),
                ('result', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待检测')], default='pending', max_length=20, verbose_name='灭菌结果')),
                ('physical_test', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待检测')], default='pending', max_length=20, verbose_name='物理监测')),
                ('chemical_test', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待检测')], default='pending', max_length=20, verbose_name='化学监测')),
                ('biological_test', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待检测')], default='pending', max_length=20, verbose_name='生物监测')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_packages', models.ManyToManyField(blank=True, related_name='sterilization_batches', to='tracker.instrumentpackage', verbose_name='器械包')),
            ],
            options={
                'verbose_name': '灭菌批次',
                'verbose_name_plural': '灭菌批次',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auditor', models.CharField(max_length=100, verbose_name='审核人')),
                ('packaging_intact', models.BooleanField(default=True, verbose_name='包装完好')),
                ('indicator_changed', models.BooleanField(default=True, verbose_name='化学指示卡变色')),
                ('label_clear', models.BooleanField(default=True, verbose_name='标识清晰')),
                ('seal_intact', models.BooleanField(default=True, verbose_name='封口完好')),
                ('audit_result', models.CharField(choices=[('approved', '通过'), ('rejected', '不通过')], max_length=20, verbose_name='审核结果')),
                ('audited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_audits', to='tracker.instrumentpackage', verbose_name='器械包')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_audits', to='tracker.sterilizationbatch', verbose_name='灭菌批次')),
            ],
            options={
                'verbose_name': '放行审核',
                'verbose_name_plural': '放行审核',
                'ordering': ['-audited_at'],
            },
        ),
        migrations.CreateModel(
            name='InfectionInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('instrument', '器械包抽查'), ('batch', '灭菌批次抽查'), ('environment', '环境监测')], max_length=20, verbose_name='抽查类型')),
                ('inspector', models.CharField(max_length=100, verbose_name='抽查人')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='抽查时间')),
                ('result', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格')], default='qualified', max_length=20, verbose_name='抽查结果')),
                ('findings', models.TextField(blank=True, default='', verbose_name='发现问题')),
                ('corrective_action', models.TextField(blank=True, default='', verbose_name='纠正措施')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='tracker.instrumentpackage', verbose_name='器械包')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='tracker.sterilizationbatch', verbose_name='灭菌批次')),
            ],
            options={
                'verbose_name': '院感抽查',
                'verbose_name_plural': '院感抽查',
                'ordering': ['-inspected_at'],
            },
        ),
    ]
