# Generated by Django 5.1.15 on 2026-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectioninspection',
            name='follow_up_notes',
            field=models.TextField(blank=True, default='', verbose_name='整改跟进记录'),
        ),
        migrations.AddField(
            model_name='infectioninspection',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='整改完成时间'),
        ),
        migrations.AddField(
            model_name='infectioninspection',
            name='handled_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='整改人'),
        ),
        migrations.AddField(
            model_name='infectioninspection',
            name='handling_status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('resolved', '已完成')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
    ]
