# Generated by Django 5.0 on 2026-06-11 10:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('duration_hours', models.PositiveIntegerField(default=8, verbose_name='课时（小时）')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('employee', '员工'), ('training_admin', '培训管理员'), ('instructor', '讲师'), ('hr', 'HR')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=50, unique=True, verbose_name='证书编号')),
                ('status', models.CharField(choices=[('pending', '待发证'), ('issued', '已发证'), ('revoked', '已撤回'), ('rejected', '发证驳回')], default='pending', max_length=20, verbose_name='证书状态')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('revoked_date', models.DateField(blank=True, null=True, verbose_name='撤回日期')),
                ('revoke_reason', models.CharField(blank=True, max_length=500, verbose_name='撤回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='发证HR')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL, verbose_name='撤回人')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='training.certificate', verbose_name='证书')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '证书历史记录',
                'verbose_name_plural': '证书历史记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='training.department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='报名状态')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='training.enrollment', verbose_name='报名记录'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='考试分数')),
                ('status', models.CharField(choices=[('not_taken', '未考试'), ('passed', '已通过'), ('failed', '未通过')], default='not_taken', max_length=20, verbose_name='考试状态')),
                ('failure_reason', models.CharField(blank=True, choices=[('score_too_low', '分数不足'), ('absent_too_much', '缺勤过多'), ('cheating', '作弊'), ('other', '其他')], max_length=50, null=True, verbose_name='未通过原因')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考试日期')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exams', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='training.enrollment', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩',
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='培训地点')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='最大人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='training.course', verbose_name='课程')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='讲师')),
            ],
            options={
                'verbose_name': '培训排班',
                'verbose_name_plural': '培训排班',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingschedule', verbose_name='培训排班'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='签到日期')),
                ('status', models.CharField(choices=[('present', '已签到'), ('absent', '缺勤'), ('late', '迟到'), ('not_checked', '未签到')], default='not_checked', max_length=20, verbose_name='签到状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.enrollment', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-check_date'],
                'unique_together': {('enrollment', 'check_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('schedule', 'employee')},
        ),
    ]
